Repository Skyrat-SS13/Skyrat13, pull requests merged in 2020-04, with the labels that each got.

#1045 [PR FIX: 1037]holodeck WRESTLING
  _maps/map_files/generic/CentCom.dmm
  code/datums/martial/wrestling.dm
  code/game/area/areas/holodeck.dm
Labels: Feature, Map Edit

#950 [Testmerge Ready, Fullmerge Ready] Charlie Station Overhaul
  _maps/RandomRuins/SpaceRuins/forgottenship.dmm
  code/datums/ruins/space.dm
  modular_skyrat/_maps/RandomRuins/SpaceRuins/oldstation.dmm
  modular_skyrat/code/datums/ruins/space.dm
  modular_skyrat/code/game/objects/items/cards_ids.dm
  modular_skyrat/code/game/objects/structures/ghost_role_spawners.dm
  modular_skyrat/code/modules/mining/equipment/kinetic_crusher.dm
  modular_skyrat/code/modules/mob/living/simple_animal/hostile/megafauna/colossus.dm
  modular_skyrat/code/modules/ruins/spaceruin_code/forgottenship.dm
  modular_skyrat/code/modules/ruins/spaceruin_code/oldstation.dm
  tgstation.dme
Labels: Map Edit

#1032 Headsets now require you to be capable of using items to operate.
  code/game/objects/items/devices/radio/radio.dm
  modular_skyrat/code/game/objects/items/devices/radio/radio.dm
  tgstation.dme
Labels: Tweak

#1048 [Modular]Vendor Prize Limit
  modular_skyrat/code/game/machinery/computer/arcade/arcade.dm
Labels: Feature

#1008 More character text fluff(records, background, skills) and also better examine for species
  code/datums/datacore.dm
  code/game/machinery/computer/medical.dm
  code/game/machinery/computer/security.dm
  code/modules/client/preferences.dm
  code/modules/mob/living/carbon/human/examine.dm
  modular_citadel/code/modules/client/preferences_savefile.dm
  modular_skyrat/code/_HELPERS/text.dm
  modular_skyrat/code/modules/mob/living/carbon/human/human.dm
  tgstation.dme
Labels: Feature

#1051 [Modular] Addition of shrink module
  code/game/objects/items/robot/robot_upgrades.dm
  code/modules/research/designs/mechfabricator_designs.dm
  modular_skyrat/code/game/objects/items/robot/robot_upgrades.dm
  modular_skyrat/code/modules/mob/living/silicon/robot/robot.dm
  modular_skyrat/code/modules/research/designs/mechfabricator_designs.dm
  modular_skyrat/code/modules/research/techweb/all_nodes.dm
Labels: Feature

#1052 Xeno-Hybrid and Ash Walker edits
  modular_skyrat/code/modules/mob/living/carbon/human/species_types/furrypeople.dm
  modular_skyrat/code/modules/mob/living/carbon/human/species_types/lizardpeople.dm
  tgstation.dme
Labels: Balance/Rebalance, Tweak

#1064 Fixes the fucking SEVA and Exo suits
  modular_skyrat/code/modules/mining/equipment/explorer_gear.dm
  modular_skyrat/icons/mob/epic_mining.dmi
  modular_skyrat/icons/mob/epic_mining_digi.dmi
  modular_skyrat/icons/mob/head.dmi
  modular_skyrat/icons/mob/head_muzzled.dmi
  modular_skyrat/icons/mob/mask.dmi
  modular_skyrat/icons/mob/mask_muzzled.dmi
  modular_skyrat/icons/mob/suit.dmi
  modular_skyrat/icons/mob/suit_digi.dmi
  modular_skyrat/icons/obj/clothing/epic_mining.dmi
  modular_skyrat/icons/obj/clothing/hats.dmi
  modular_skyrat/icons/obj/clothing/masks.dmi
  modular_skyrat/icons/obj/clothing/suits.dmi
Labels: Fix

#1066 [Modular] Hurtsposals (Disposals Hurt)
  code/modules/recycling/disposal/pipe.dm
  modular_skyrat/code/modules/recycling/disposal/pipe.dm
  tgstation.dme
Labels: Feature

#1069 Added a "dad" silicon lawset.
  modular_skyrat/code/datums/ai_laws.dm
  modular_skyrat/code/game/objects/items/AI_modules.dm
  modular_skyrat/code/modules/research/designs/AI_module_designs.dm
  modular_skyrat/code/modules/research/techweb/all_nodes.dm
  tgstation.dme
Labels: Feature

#1070 Fixed the auto-announcer.
  modular_skyrat/code/game/objects/items/devices/radio/radio.dm
Labels: Fix

#1075 Marked Jake as a codeowner for the purposes of automatic review request in map-affecting PRs.
  .github/CODEOWNERS
Labels: GitHub

#891 Adds a craftable double stunbaton (makeshift electrostaff that sucks)
  modular_skyrat/code/datums/components/crafting/recipes/recipes_weapon_and_ammo.dm
  modular_skyrat/code/game/objects/items/weaponry.dm
  modular_skyrat/icons/mob/backstaff.dmi
  modular_skyrat/icons/mob/inhands/staff_lefthand.dmi
  modular_skyrat/icons/mob/inhands/staff_righthand.dmi
  modular_skyrat/icons/obj/staff.dmi
Labels: Feature, Needs Review, Sprites

#1011 Lowers syndi bomb explosion and TC cost. Adds in a new bomb beacon, as explosive as old syndi bomb and costs 15 TC
  modular_skyrat/code/game/machinery/syndicatebeacon.dm
  modular_skyrat/code/game/machinery/syndicatebomb.dm
  modular_skyrat/code/modules/uplink/uplink_explosives.dm
  tgstation.dme
Labels: Balance/Rebalance, Feature

#1023 Blaurung - Ash Drake Varient/RP Drake
  icons/mob/lavaland/glaurung.dmi
  modular_skyrat/code/modules/language/dragon.dm
  modular_skyrat/code/modules/mining/lavaland/necropolis_chests.dm
  modular_skyrat/code/modules/mob/living/simple_animal/hostile/megafauna/glaurung.dm
  tgstation.dme
Labels: Sprites

#1089 [Fix]Modular Map Fix
  _maps/_basemap.dm
  _maps/map_files/BoxStation/BoxStation_Skyrat.dmm
Labels: Fix, Map Edit

#1106 [READY] Fixes BobJoga's Shomtgun Shellms
  modular_skyrat/code/modules/projectiles/ammunition/ballistic/shotgun.dm
  modular_skyrat/icons/obj/shomtgun.dmi
Labels: Feature, Fix, Needs Review

#1110 [Tweak]Prison Botany Nerf & Surgery Sec Removal
  _maps/map_files/BoxStation/BoxStation_Skyrat.dmm
  _maps/map_files/Deltastation/DeltaStation2_Skyrat.dmm
  _maps/map_files/MetaStation/MetaStation_Skyrat.dmm
  _maps/map_files/PubbyStation/PubbyStation_Skyrat.dmm
Labels: Balance/Rebalance, Map Edit, Removal

#1117 old station fixes
  code/datums/ruins/space.dm
  modular_skyrat/_maps/RandomRuins/SpaceRuins/oldstation.dmm
Labels: Fix

#1120 [READY] Cuts down on a lot of ick ock brain damage lines and adds a bunch of new ones
  strings/traumas.json
Labels: Feature, Needs Review, Removal, Tweak

#1124 [Modular]More Shaker Reagents
  modular_skyrat/code/modules/reagents/reagents_containers/borghydro.dm
Labels: Feature

#1118 [Tweaks]More Perma Changes...
  _maps/map_files/BoxStation/BoxStation_Skyrat.dmm
  _maps/map_files/Deltastation/DeltaStation2_Skyrat.dmm
  _maps/map_files/MetaStation/MetaStation_Skyrat.dmm
  _maps/map_files/PubbyStation/PubbyStation_Skyrat.dmm
  modular_skyrat/code/_DEFINES/machines.dm
  modular_skyrat/code/game/objects/items/circuitboards/machine_circuitboards.dm
  modular_skyrat/code/modules/cargo/packs.dm
  modular_skyrat/code/modules/hydroponics/biogenerator_prisoner.dm
  modular_skyrat/code/modules/jobs/job_types/prisoner.dm
  modular_skyrat/code/modules/research/designs/biogenerator_designs_prisoner.dm
  modular_skyrat/code/modules/research/designs/machine_desings/machine_designs_service.dm
  modular_skyrat/code/modules/research/techweb/_techweb.dm
  modular_skyrat/code/modules/research/techweb/all_nodes.dm
  modular_skyrat/code/modules/vending/dinnerwareprisoner.dm
  modular_skyrat/code/modules/vending/nutrimaxprisoner.dm
  tgstation.dme
Labels: Feature, Map Edit, Tweak

#1115 Changes to traitor objectives.
  code/datums/mind.dm
  code/modules/antagonists/traitor/classes/assassin.dm
  code/modules/antagonists/traitor/classes/human.dm
  code/modules/antagonists/traitor/classes/subterfuge.dm
  modular_skyrat/code/game/gamemodes/objective.dm
  modular_skyrat/code/game/objects/items/implants/implant_blackmail.dm
  strings/flavor_objectives/traitor.txt
  tgstation.dme
Labels: Feature, Removal, Tweak

#1126 [Modular] Corvid Beak
  modular_skyrat/code/modules/mob/dead/new_player/sprite_accessories/snouts.dm
  modular_skyrat/icons/mob/bird_snout.dmi
Labels: Feature

#1113 [Modular] [READY] Roro!
  _maps/RandomRuins/SpaceRuins/DJstation.dmm
  _maps/map_files/BoxStation/BoxStation_Skyrat.dmm
  _maps/map_files/Deltastation/DeltaStation2_Skyrat.dmm
  _maps/map_files/KiloStation/KiloStation_Skyrat.dmm
  _maps/map_files/LambdaStation/lambda_Skyrat.dmm
  _maps/map_files/MetaStation/MetaStation_Skyrat.dmm
  _maps/map_files/OmegaStation/OmegaStation_Skyrat.dmm
  _maps/map_files/PubbyStation/PubbyStation_Skyrat.dmm
  modular_skyrat/code/modules/mob/living/simple_animal/friendly/roro.dm
  modular_skyrat/icons/mob/roro.dmi
  modular_skyrat/sound/voice/roro_rogue.ogg
  tgstation.dme
Labels: Feature, Map Edit, Needs Review

#1108 Tiger Carp Frenzy (Sprite, Mob, Event)
  code/game/gamemodes/dynamic/dynamic_rulesets_events.dm
  code/modules/events/tiger_carp_frenzy.dm
  code/modules/mob/living/simple_animal/hostile/carp.dm
  icons/mob/animal.dmi
  tgstation.dme
Labels: Administration, Feature, Sprites, Tweak

#1109 [Modular] [READY] Nanite Horrors, a replacement for your bog-standard Romerol Zombies.
  modular_skyrat/code/modules/mob/living/carbon/human/species_types/zombies.dm
  modular_skyrat/code/modules/reagents/chemistry/reagents/other_reagents.dm
  modular_skyrat/code/modules/reagents/reagents_containers/reagent_containers/bottle.dm
  modular_skyrat/code/modules/surgery/organs/tongue.dm
  modular_skyrat/code/modules/uplink/uplink_stealth.dm
  modular_skyrat/code/modules/zombie/items.dm
  modular_skyrat/code/modules/zombie/organs.dm
  modular_skyrat/icons/mob/human.dmi
  modular_skyrat/icons/mob/inhands/weapons/claws_lefthand.dmi
  modular_skyrat/icons/mob/inhands/weapons/claws_righthand.dmi
  modular_skyrat/icons/mob/simple_human.dmi
  modular_skyrat/icons/mob/zombie_parts.dmi
  modular_skyrat/icons/obj/items/claw.dmi
  modular_skyrat/sound/zombie/zombie_attack1.ogg
  modular_skyrat/sound/zombie/zombie_attack2.ogg
  modular_skyrat/sound/zombie/zombie_attack3.ogg
  modular_skyrat/sound/zombie/zombie_die1.ogg
  modular_skyrat/sound/zombie/zombie_die2.ogg
  modular_skyrat/sound/zombie/zombie_die3.ogg
  modular_skyrat/sound/zombie/zombie_say1.ogg
  modular_skyrat/sound/zombie/zombie_say2.ogg
  modular_skyrat/sound/zombie/zombie_say3.ogg
  modular_skyrat/sound/zombie/zombie_say4.ogg
  modular_skyrat/sound/zombie/zombie_say5.ogg
  modular_skyrat/sound/zombie/zombie_say6.ogg
  tgstation.dme
Labels: Feature, Needs Review, Tweak

#1062 Update deep_fryer.dm
  code/modules/food_and_drinks/kitchen_machinery/deep_fryer.dm
Labels: Removal

#1152 [READY] Fixing the Permabrig Visitation Visitor-Side cameras on all maps
  _maps/map_files/BoxStation/BoxStation_Skyrat.dmm
  _maps/map_files/Deltastation/DeltaStation2_Skyrat.dmm
  _maps/map_files/MetaStation/MetaStation_Skyrat.dmm
  _maps/map_files/PubbyStation/PubbyStation_Skyrat.dmm
  tgstation.dme
Labels: Fix, Map Edit, Needs Review

#1160 Makes visible(based on sight) messages always appear to mobs in range of 1 despite in darkness
  code/modules/mob/mob.dm
Labels: Fix

#1163 Removes cigarettes from paramedics mouths
  code/modules/jobs/job_types/paramedic.dm
Labels: Removal

#1154 Added a new horn
  modular_skyrat/code/modules/mob/dead/new_player/sprite_accessories/horns.dm
  modular_skyrat/icons/mob/horns.dmi
  tgstation.dme
Labels: Feature, Sprites

#1165 [READY] [HOTFIX] Fixes new Medbay vent on Box that caused 200+ runtimes
  _maps/map_files/BoxStation/BoxStation_Skyrat.dmm
Labels: Fix, Map Edit, Needs Review

#1168 Reverts modular shotgun stuff
  modular_skyrat/code/modules/projectiles/ammunition/ballistic/shotgun.dm
  modular_skyrat/icons/obj/shomtgun.dmi
  tgstation.dme
Labels: Revert

#1176 [FIX] FIXING THE FUCKING ROOMBA
  modular_skyrat/code/modules/mob/living/simple_animal/friendly/roro.dm
Labels: Fix

#1166 Meta Station Security Rebuild + General tweaks + Xyel Fanclub
  _maps/RandomRuins/StationRuins/Box/Engine/engine_singulo.dmm
  _maps/map_files/MetaStation/MetaStation_Skyrat.dmm
  code/game/objects/effects/spawners/misc_lootdrop.dm
  modular_skyrat/code/modules/vending/nutrimaxprisoner.dm
  tgstation.dme
Labels: Balance/Rebalance, Feature, Fix, Map Edit, Tweak

#1190 Character Customisation: The Floofening (New Sprites) Modular Edition
  modular_skyrat/code/modules/mob/dead/new_player/sprite_accessories/body_markings.dm
  modular_skyrat/code/modules/mob/dead/new_player/sprite_accessories/snouts.dm
  modular_skyrat/code/modules/mob/dead/new_player/sprite_accessories/tails.dm
  modular_skyrat/icons/mob/mam_snouts.dmi
  modular_skyrat/icons/mob/skyrat_markings.dmi
  modular_skyrat/icons/mob/tails.dmi
  tgstation.dme
Labels: Feature, Removal

#1185 [READY] Bugfixes and QOL Changes to many things + Cargo Access fixes for Blueshields
  _maps/RandomZLevels/moonoutpost19.dmm
  _maps/map_files/BoxStation/BoxStation_Skyrat.dmm
  _maps/map_files/Deltastation/DeltaStation2_Skyrat.dmm
  _maps/map_files/KiloStation/KiloStation_Skyrat.dmm
  _maps/map_files/PubbyStation/PubbyStation_Skyrat.dmm
Labels: Feature, Fix, Map Edit, Needs Review, Removal, Tweak

#1175 Allows prisoners to send wood planks, fabrics and other sellables via the plate shoot
  modular_skyrat/code/game/machinery/lpchutes.dm
Labels: Feature

#1173 Neo Jelly OD Threshold.
  code/modules/reagents/chemistry/reagents/medicine_reagents.dm
Labels: Balance/Rebalance

#1177 [READY] Adds machine language to IPCs and lizsynths
  code/modules/surgery/organs/tongue.dm
  modular_skyrat/code/modules/mob/living/carbon/human/species_types/ipc.dm
  modular_skyrat/code/modules/mob/living/carbon/human/species_types/synthliz.dm
Labels: Feature, Needs Review

#1180 [Addition] [Semi-Modular] Two new Peacekeeper Cyborg looks!
  code/modules/mob/living/silicon/robot/robot_modules.dm
  modular_skyrat/code/modules/mob/living/silicon/robot/robot_modules.dm
  modular_skyrat/icons/mob/customrobot.dmi
Labels: Feature, Tweak

#1193 [READY] Brig phys changes
  code/modules/jobs/jobs.dm
  modular_skyrat/code/modules/jobs/job_types/brig_physician.dm
Labels: Needs Review, Tweak

#1200 Fixes up cable restraints
  code/modules/power/cable.dm
Labels: Fix

#1207 Buffs the CMO's hypospray to relevancy
  code/modules/reagents/reagent_containers/hypospray.dm
Labels: Balance/Rebalance

#1215 Adds four new player customization options
  modular_skyrat/code/modules/mob/dead/new_player/sprite_accessories/ears.dm
  modular_skyrat/code/modules/mob/dead/new_player/sprite_accessories/hair_head.dm
  modular_skyrat/code/modules/mob/dead/new_player/sprite_accessories/tails.dm
  modular_skyrat/icons/mob/human_face.dmi
  modular_skyrat/icons/mob/mam_ears.dmi
  modular_skyrat/icons/mob/tails.dmi
  tgstation.dme
Labels: Feature

#1220 Swaps the inhand sprites for the BSGUN
  modular_skyrat/icons/mob/inhands/weapons/blueshieldgun_lefthand.dmi
  modular_skyrat/icons/mob/inhands/weapons/blueshieldgun_righthand.dmi
Labels: Fix

#1221 Removes the Roblox Sword (From Public Aquisition)
  modular_skyrat/code/game/objects/items/weaponry.dm
  modular_skyrat/code/modules/uplink/uplink_dangerous.dm
Labels: Removal

#1248 [READY] Bandaid Fix for missing Sec Clothing's Alternate Sprites
  modular_skyrat/code/modules/clothing/refactor.dm
Labels: Fix, Needs Review

#1247 [READY] MetaStation Tweaks and Fixes
  _maps/map_files/MetaStation/MetaStation_Skyrat.dmm
Labels: Feature, Fix, Map Edit, Needs Review, Removal, Tweak

#1198 Removes BoxStationSnow
  _maps/map_files/BoxStationSnow/BoxStationSnow.dmm
Labels: Map Edit, Removal

#1249 Makes HEV hardsuit into a different more expensive pack
  modular_skyrat/code/modules/cargo/packs/special.dm
Labels: Feature

#1262 [READY] Added 2 Extra Paramedic Spawns on Box to fix Spawning Issue
  _maps/map_files/BoxStation/BoxStation_Skyrat.dmm
Labels: Fix, Map Edit, Needs Review

#1217 Strange Reagent revives based on dosage instead of flat value.
  code/modules/reagents/chemistry/reagents/medicine_reagents.dm
  modular_skyrat/code/modules/reagents/chemistry/reagents/medicine_reagents.dm
  tgstation.dme
Labels: Balance/Rebalance

#1164 [READY] Edited the order of items in several vending machines
  code/modules/vending/drinnerware.dm
  code/modules/vending/medical.dm
  code/modules/vending/medical_wall.dm
  code/modules/vending/security.dm
  modular_skyrat/code/modules/vending/dinnerwareprisoner.dm
Labels: Needs Review, Tweak

#1266 [READY] Changes Formatting of Alkali Code to fix NTOS Crashes
  code/datums/diseases/advance/symptoms/fire.dm
Labels: Fix, Needs Review

#1280 [READY] Byond 512 compatibility PR - altetnarive
  code/__DEFINES/lighting.dm
  code/_onclick/hud/plane_master.dm
  code/game/atoms_movable.dm
  code/game/objects/effects/effects.dm
  code/game/objects/items.dm
  code/modules/antagonists/bloodsucker/bloodsucker_life.dm
  code/modules/instruments/songs/_song.dm
  code/modules/instruments/songs/play_synthesized.dm
  code/modules/lighting/emissive_blocker.dm
  code/modules/mob/living/carbon/human/human_defines.dm
  code/modules/mob/living/carbon/monkey/monkey.dm
  code/modules/mob/living/silicon/robot/robot.dm
  code/modules/mob/mob_defines.dm
  code/modules/reagents/chemistry/machinery/chem_master.dm
Labels: Needs Review

#1183 [Map Edit: Box] Maint Bar Change
  _maps/map_files/BoxStation/BoxStation_Skyrat.dmm
Labels: Feature, Map Edit, Removal

#1083 [Modular] [READY] From the Rim of Space to the ends of the Station (Power Armor for Robotics)
  modular_skyrat/code/datums/components/crafting/recipes/recipes_clothing.dm
  modular_skyrat/code/game/mecha/mecha_parts.dm
  modular_skyrat/code/modules/clothing/spacesuits/hardsuit.dm
  modular_skyrat/code/modules/research/designs/mechfabricator_designs.dm
  modular_skyrat/code/modules/research/techweb/all_nodes.dm
  modular_skyrat/icons/mecha/mech_construct.dmi
  modular_skyrat/icons/mecha/mech_construction.dmi
  modular_skyrat/icons/mob/clothing/head.dmi
  modular_skyrat/icons/mob/clothing/suit.dmi
  modular_skyrat/icons/obj/clothing/hats.dmi
  modular_skyrat/icons/obj/clothing/suits.dmi
  modular_skyrat/sound/misc/suitmalf.ogg
  tgstation.dme
Labels: Do Not Merge, Feature, Needs Review

#1298 [READY] [HOTFIX] Fixed Access for Discoball in Maint Bar & North Evidence Storage Door
  _maps/map_files/BoxStation/BoxStation_Skyrat.dmm
Labels: Fix, Map Edit, Needs Review

#1292 Adds quality cobra hoods for most species and a colored belly marking for lizards
  modular_skyrat/code/modules/mob/dead/new_player/sprite_accessories/antenna.dm
  modular_skyrat/code/modules/mob/dead/new_player/sprite_accessories/body_markings.dm
  modular_skyrat/code/modules/mob/dead/new_player/sprite_accessories/ears.dm
  modular_skyrat/code/modules/mob/dead/new_player/sprite_accessories/frills.dm
  modular_skyrat/icons/mob/antenna.dmi
  modular_skyrat/icons/mob/frills.dmi
  modular_skyrat/icons/mob/mam_ears.dmi
  modular_skyrat/icons/mob/skyrat_markings.dmi
  tgstation.dme
Labels: Feature

#1293 Mirrors part 3
  code/__DEFINES/dcs/signals.dm
  code/__DEFINES/dynamic.dm
  code/__DEFINES/movespeed_modification.dm
  code/__HELPERS/global_lists.dm
  code/__HELPERS/roundend.dm
  code/_globalvars/lists/mapping.dm
  code/controllers/subsystem/persistence.dm
  code/controllers/subsystem/vote.dm
  code/datums/action.dm
  code/datums/dash_weapon.dm
  code/datums/elements/spellcasting.dm
  code/datums/mutations/combined.dm
  code/game/area/areas/holodeck.dm
  code/game/gamemodes/dynamic/dynamic.dm
  code/game/gamemodes/dynamic/dynamic_rulesets_latejoin.dm
  code/game/gamemodes/dynamic/dynamic_storytellers.dm
  code/game/machinery/launch_pad.dm
  code/game/objects/items/devices/scanners.dm
  code/game/objects/items/robot/robot_upgrades.dm
  code/modules/antagonists/changeling/changeling_power.dm
  code/modules/antagonists/changeling/powers/tiny_prick.dm
  code/modules/antagonists/clockcult/clock_helpers/hierophant_network.dm
  code/modules/antagonists/clockcult/clock_items/clock_weapons/_call_weapon.dm
  code/modules/antagonists/clockcult/clock_mobs/_eminence.dm
  code/modules/antagonists/clockcult/clock_scriptures/scripture_scripts.dm
  code/modules/antagonists/cult/blood_magic.dm
  code/modules/antagonists/cult/cult_comms.dm
  code/modules/antagonists/cult/cult_items.dm
  code/modules/antagonists/cult/rune_spawn_action.dm
  code/modules/antagonists/traitor/equipment/Malf_Modules.dm
  code/modules/clothing/spacesuits/chronosuit.dm
  code/modules/holodeck/area_copy.dm
  code/modules/holodeck/computer.dm
  code/modules/mob/living/carbon/alien/humanoid/alien_powers.dm
  code/modules/mob/living/carbon/human/species_types/golems.dm
  code/modules/mob/living/carbon/human/species_types/jellypeople.dm
  code/modules/mob/living/carbon/life.dm
  code/modules/mob/living/say.dm
  code/modules/mob/living/simple_animal/hostile/giant_spider.dm
  code/modules/mob/living/simple_animal/slime/powers.dm
  code/modules/projectiles/gun.dm
  code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
  code/modules/reagents/chemistry/reagents/medicine_reagents.dm
  code/modules/reagents/chemistry/reagents/other_reagents.dm
  code/modules/spells/spell.dm
  code/modules/spells/spell_types/aimed.dm
  code/modules/spells/spell_types/lightning.dm
  code/modules/spells/spell_types/mime.dm
  code/modules/surgery/organs/liver.dm
  code/modules/surgery/organs/organ_internal.dm
  code/modules/surgery/organs/vocal_cords.dm
  modular_citadel/code/modules/reagents/chemistry/reagents/enlargement.dm
Labels: Feature

#1306 [READY] [HOTFIX] Adds Brig Physician Spawn to Meta's Brig
  _maps/map_files/MetaStation/MetaStation_Skyrat.dmm
Labels: Fastmerge Request, Fix, Map Edit, Needs Review

#1314 [HOTFIX] [SPEEDMERGE] Fixes distribution and scrubbers being the same pipenet.
  _maps/map_files/BoxStation/BoxStation_Skyrat.dmm
Labels: Fix, Map Edit, Removal

#1326 Jukebox search function
  modular_skyrat/code/game/machinery/dance_machine.dm
  tgstation.dme
Labels: Feature

#1325 Small traitor item balancing and fixes.
  modular_skyrat/code/game/objects/items/weaponry.dm
  modular_skyrat/code/modules/uplink/uplink_dangerous.dm
  modular_skyrat/code/modules/uplink/uplink_devices.dm
Labels: Balance/Rebalance, Fix

#1324 Human wine
  modular_skyrat/code/modules/hydroponics/fermenting_barrel.dm
  tgstation.dme
Labels: Tweak

#1300 [READY] Modifications to the Issue Template
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: GitHub, Needs Review, Tweak, documentation

#1301 Vendor Request
  code/modules/reagents/reagent_containers/pill.dm
  code/modules/vending/kinkmate.dm
  modular_skyrat/code/game/objects/items/weaponry.dm
  modular_skyrat/code/modules/reagents/reagents_containers/pill.dm
  modular_skyrat/code/modules/vending/kinkmate.dm
  tgstation.dme
Labels: Tweak

#1313 Reminds you about the blackout policy when you pop out of cloner.
  code/game/machinery/cloning.dm
Labels: Feature

#1302 Serious Miasma Balance Tweaks
  code/modules/atmospherics/gasmixtures/gas_types.dm
  code/modules/mob/living/carbon/life.dm
  code/modules/surgery/organs/lungs.dm
  modular_skyrat/code/modules/atmospherics/gasmixtures/gas_types.dm
  modular_skyrat/code/modules/mob/living/carbon/life.dm
  tgstation.dme
Labels: Balance/Rebalance

#1312 Removes greentext from traitor and changeling
  code/modules/antagonists/changeling/changeling.dm
  code/modules/antagonists/traitor/datum_traitor.dm
  modular_skyrat/code/modules/antagonists/changeling/changeling.dm
  modular_skyrat/code/modules/antagonists/traitor/datum_traitor.dm
  tgstation.dme
Labels: Removal

#1309 Makes disguised syndicate borgs not obvious
  code/modules/mob/living/silicon/robot/examine.dm
  modular_skyrat/code/game/objects/items/devices/radio/radio.dm
Labels: Fix

#1334 [PR CLONE]3 new and somewhat gimmicky AI modules.
  modular_skyrat/code/datums/ai_laws.dm
  modular_skyrat/code/game/objects/items/AI_modules.dm
  modular_skyrat/code/modules/research/designs/AI_module_designs.dm
  modular_skyrat/code/modules/research/techweb/all_nodes.dm
Labels: Feature

#1338 [PR CLONE]Goat Simulator: Waste of Space
  modular_skyrat/code/game/objects/items/plushes/plushes.dm
Labels: Balance/Rebalance

#1339 [PR CLONE]Exclusive traitor assistant item: The true DAB.
  modular_skyrat/code/modules/uplink/uplink_clothing.dm
  tgstation.dme
Labels: Feature

#1341 [PR CLONE]New Traitor Bundle: Motherbase Shipment
  modular_skyrat/code/modules/uplink/uplink_bundles.dm
Labels: Feature

#1347 Buffs Syndicate Sleeper
  code/game/machinery/Sleeper.dm
  modular_skyrat/code/game/machinery/Sleeper.dm
  tgstation.dme
Labels: Feature

#1357 Robotics Power Armor MK. II
  modular_skyrat/code/datums/components/crafting/recipes/recipes_clothing.dm
  modular_skyrat/code/game/mecha/mecha_construction_paths.dm
  modular_skyrat/code/game/mecha/mecha_parts.dm
  modular_skyrat/code/modules/clothing/spacesuits/hardsuit.dm
  modular_skyrat/code/modules/research/designs/machine_designs.dm
  modular_skyrat/code/modules/research/designs/machine_desings/machine_designs_service.dm
  modular_skyrat/code/modules/research/designs/mechfabricator_designs.dm
  modular_skyrat/code/modules/research/designs/weapon_designs.dm
  modular_skyrat/code/modules/research/techweb/all_nodes.dm
  modular_skyrat/icons/mecha/mech_construct.dmi
  modular_skyrat/icons/mecha/mech_construction.dmi
  modular_skyrat/icons/mob/clothing/head.dmi
  modular_skyrat/icons/mob/clothing/head_muzzled.dmi
  modular_skyrat/icons/mob/clothing/suit.dmi
  modular_skyrat/icons/mob/clothing/suit_digi.dmi
  modular_skyrat/icons/obj/clothing/hats.dmi
  modular_skyrat/icons/obj/clothing/suits.dmi
  tgstation.dme
Labels: Tweak

#1364 Snake fitted suits
  modular_skyrat/code/modules/clothing/refactor.dm
  modular_skyrat/icons/mob/suits_taur.dmi
Labels: Code Improvement, Sprites

#1365 Nerfs/Reworks the Scrubber Event
  code/modules/events/vent_clog.dm
  modular_skyrat/code/modules/events/vent_clog.dm
  tgstation.dme
Labels: Balance/Rebalance

#1261 Removes Pistols from Shoes
  code/datums/components/storage/concrete/pockets.dm
Labels: Balance/Rebalance, Removal

#1346 Shows who is handling the ticket in ticket stat
  code/modules/admin/verbs/adminhelp.dm
  code/modules/admin/verbs/adminpm.dm
Labels: Feature

#1172 Reverts the radio changes due to a bug
  code/game/objects/items/devices/radio/radio.dm
  modular_skyrat/code/game/objects/items/devices/radio/radio.dm
Labels: Revert

#1401 Wrath ruin bugfix
  modular_skyrat/code/modules/ruins/lavalandruin_code/misc.dm
Labels: Fix

#1367 [Modular] Plushie Back
  modular_citadel/code/modules/custom_loadout/custom_items.dm
  modular_skyrat/code/game/objects/items/plushies.dm
  modular_skyrat/code/modules/custom_loadout/custom_items.dm
  modular_skyrat/icons/obj/custom.dmi
  modular_skyrat/icons/obj/plushies.dmi
  tgstation.dme
Labels: Feature, Sprites

#1268 [Ready] Dynamic changes
  code/game/gamemodes/dynamic/dynamic.dm
  code/game/gamemodes/dynamic/dynamic_storytellers.dm
Labels: Needs Review

#1433 [Modular] More plush
  modular_skyrat/code/game/objects/items/plushies.dm
  modular_skyrat/icons/obj/plushies.dmi
  tgstation.dme
Labels: Feature

#1435 [FEEDBACK WANTED!!!] Changes ahelp language to be more forgiving and kind + Extra transparency
  code/modules/admin/verbs/adminhelp.dm
Labels: Tweak, enhancement

#1398 [READY] Box Station Departures Rework and General Bugfixes and Tweaks to both Box and Ghost Cafe
  _maps/map_files/BoxStation/BoxStation_Skyrat.dmm
  _maps/map_files/generic/CentCom_Skyrat.dmm
Labels: Feature, Fix, Map Edit, Needs Review, Removal, Tweak

#1440 Ports construction bags from TG
  modular_skyrat/code/game/objects/items/storage/bags.dm
  modular_skyrat/code/modules/vending/engivend.dm
  modular_skyrat/icons/obj/tools.dmi
  tgstation.dme
Labels: Feature

#1442 Finally restores balance of my mentality [Plushie]
  modular_skyrat/code/game/objects/items/plushies.dm
  modular_skyrat/icons/obj/plushies.dmi
Labels: Feature

#1458 Fixes some weird mining suit icon problems
  modular_skyrat/code/modules/mining/equipment/explorer_gear.dm
  modular_skyrat/icons/mob/clothing/mask_muzzled.dmi
Labels: Fix

#1446 Power armor mob overlay fixing (No, i didn't fix the digi and muzzled sprites, Michael is the one to blame) and other stuff
  modular_skyrat/code/datums/status_effects/buffs.dm
  modular_skyrat/code/modules/clothing/refactor.dm
  modular_skyrat/code/modules/clothing/spacesuits/hardsuit.dm
  modular_skyrat/icons/obj/clothing/hats.dmi
  modular_skyrat/icons/obj/clothing/suits.dmi
Labels: Fix

#1445 Fixes soft caps not reskinning properly
  modular_skyrat/code/modules/clothing/head/soft_caps.dm
Labels: Fix

#1463 Requestedminingstuff
  modular_skyrat/code/modules/clothing/spacesuits/hardsuit.dm
  modular_skyrat/code/modules/mining/equipment/explorer_gear.dm
  modular_skyrat/code/modules/mining/machine_vending.dm
  modular_skyrat/code/modules/reagents/reagent_containers/patch.dm
  tgstation.dme
Labels: Feature, Tweak

#1437 Fixes issue #1428 + adds another armor reskin
  modular_skyrat/code/modules/clothing/head/jobs.dm
  modular_skyrat/code/modules/clothing/refactor.dm
  modular_skyrat/code/modules/clothing/under/jobs/security.dm
  modular_skyrat/icons/mob/clothing/suit.dmi
  modular_skyrat/icons/obj/clothing/hats.dmi
  modular_skyrat/icons/obj/clothing/suits.dmi
  modular_skyrat/icons/obj/clothing/uniform.dmi
  tgstation.dme
Labels: Feature, Fix

#1206 Nerfs Synthflesh to /tg/'s current synthflesh, but not as bad.
  code/modules/reagents/chemistry/reagents/medicine_reagents.dm
  modular_skyrat/code/modules/reagents/chemistry/reagents/medicine_reagents.dm
Labels: Balance/Rebalance

#1212 powersink power needed to 100 MW from 10 GW, drain from 1.6 MW to 1 MW
  code/game/objects/items/devices/powersink.dm
Labels: Balance/Rebalance

#1219 Adds Blocking Spawners
  modular_skyrat/code/game/objects/effects/spawners/blocking_spawner.dm
  tgstation.dme
Labels: Feature, Tweak

#1144 [Modular]Handheld Mirror
  modular_skyrat/code/game/objects/items/hhmirror.dm
  modular_skyrat/code/modules/client/loadout/backpack.dm
  modular_skyrat/icons/obj/hhmirror.dmi
  tgstation.dme
Labels: Feature

#1299 Quintupled Maint Loot spawns but increased the variety by a billion percent.
  code/_globalvars/lists/maintenance_loot.dm
  code/game/objects/effects/spawners/lootdrop.dm
  modular_skyrat/code/_globalvars/lists/maintenance_loot.dm
  tgstation.dme
Labels: Balance/Rebalance

#1327 New ripley variant: Killdozer
  modular_skyrat/code/game/mecha/equipment/killdozer.dm
  modular_skyrat/code/game/mecha/mech_fabricator.dm
  modular_skyrat/code/game/mecha/mecha_construction_paths.dm
  modular_skyrat/code/game/mecha/mecha_wreckage.dm
  modular_skyrat/code/game/mecha/working/ripley.dm
  modular_skyrat/code/modules/research/designs/mechfabricator_designs.dm
  modular_skyrat/code/modules/research/techweb/all_nodes.dm
  modular_skyrat/icons/mecha/mech_construction.dmi
  modular_skyrat/icons/mecha/sometimesreasonablemenmustdounreasonablethings.dmi
  tgstation.dme
Labels: Config Update, Feature, Removal, Sound, Sprites

#1414 More AI status displays
  code/game/machinery/status_display.dm
  code/modules/mob/living/silicon/ai/ai.dm
  icons/obj/status_display.dmi
Labels: Sprites

#1332 New traitor item: Morph cube
  modular_skyrat/code/game/objects/items/devices/morphcube.dm
  modular_skyrat/code/modules/uplink/uplink_dangerous.dm
  tgstation.dme
Labels: Feature

#1290 [Map Edit: Box] Science and Geneticist Change
  _maps/map_files/BoxStation/BoxStation_Skyrat.dmm
Labels: Feature, Map Edit

#1461 [READY] Made Biogens easily accessible by Cooks on Delta and Box
  _maps/map_files/BoxStation/BoxStation_Skyrat.dmm
  _maps/map_files/Deltastation/DeltaStation2_Skyrat.dmm
  _maps/map_files/KiloStation/KiloStation_Skyrat.dmm
  _maps/map_files/MetaStation/MetaStation_Skyrat.dmm
  _maps/map_files/PubbyStation/PubbyStation_Skyrat.dmm
  modular_skyrat/code/game/objects/items/circuitboards/machine_circuitboards.dm
  modular_skyrat/code/modules/reagents/chemistry/machinery/chem_dispenser.dm
  modular_skyrat/code/modules/research/designs/machine_designs.dm
  modular_skyrat/code/modules/research/designs/machine_desings/machine_designs_service.dm
  modular_skyrat/code/modules/research/techweb/all_nodes.dm
  tgstation.dme
Labels: Map Edit, Needs Review, Tweak

#1487 [HOTFIX] [READY] Replaces indestructible walls in Lavaland Syndiebase Xenobio + More Turrets and reinforcements
  modular_skyrat/_maps/RandomRuins/LavaRuins/lavaland_surface_syndicate_base1.dmm
Labels: Fix, Needs Review

#1501 Makes liver respect toxpwr of toxins and reduced the boozepwr exponential (fix to livers)
  code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
  code/modules/surgery/organs/liver.dm
Labels: Balance/Rebalance, Tweak

#1500 Makes cobra ears for anthro better
  modular_skyrat/icons/mob/mam_ears.dmi
Labels: Fix

#1498 Modularizes the traitor stuff that Citadel removed
  modular_skyrat/code/game/objects/items/storage/uplink_kits.dm
  modular_skyrat/code/modules/uplink/uplink_badass.dm
  modular_skyrat/code/modules/uplink/uplink_dangerous.dm
  modular_skyrat/code/modules/uplink/uplink_roles.dm
  tgstation.dme
Labels: Tweak

#1507 Several petty/nitpicky changes to Box, Delta and Pubby
  _maps/map_files/BoxStation/BoxStation_Skyrat.dmm
  _maps/map_files/Deltastation/DeltaStation2_Skyrat.dmm
  _maps/map_files/MetaStation/MetaStation_Skyrat.dmm
Labels: Map Edit, Removal, Tweak

#1510 [Map Edit: Box]
  _maps/map_files/BoxStation/BoxStation_Skyrat.dmm
Labels: Fix, Map Edit

#1471 Fixes WT-550 reskinning, Power Armor anthro sprites and minor buff, + other power armor stuff
  code/modules/projectiles/guns/ballistic/automatic.dm
  modular_skyrat/code/modules/clothing/spacesuits/hardsuit.dm
  modular_skyrat/code/modules/projectiles/guns/ballistic/automatic.dm
  modular_skyrat/code/modules/research/designs/mechfabricator_designs.dm
  modular_skyrat/icons/mob/clothing/head.dmi
  modular_skyrat/icons/mob/clothing/head_muzzled.dmi
  modular_skyrat/icons/mob/clothing/suit.dmi
  modular_skyrat/icons/mob/clothing/suit_digi.dmi
Labels: Balance/Rebalance, Fix, Refactor

#1515 [READY] [SPEEDMERGE] She Comes.
  modular_skyrat/code/modules/mob/dead/new_player/sprite_accessories/hair_head.dm
  modular_skyrat/icons/mob/human_face.dmi
Labels: Feature, Needs Review, Sprites

#1518 Adding donator items.
  modular_skyrat/code/modules/client/loadout/__donator.dm
  modular_skyrat/code/modules/custom_loadout/custom_items.dm
  modular_skyrat/icons/mob/clothing/hands.dmi
  modular_skyrat/icons/mob/clothing/suit.dmi
  modular_skyrat/icons/mob/clothing/uniform.dmi
  modular_skyrat/icons/mob/large-worn-icons/32x64/head.dmi
  modular_skyrat/icons/obj/clothing/gloves.dmi
  modular_skyrat/icons/obj/clothing/hats.dmi
  modular_skyrat/icons/obj/clothing/suits.dmi
  modular_skyrat/icons/obj/clothing/uniform.dmi
  tgstation.dme
Labels: Feature

#1527 [Map Fix: Box] That vent
  _maps/map_files/BoxStation/BoxStation_Skyrat.dmm
Labels: Map Edit, Removal

#1472 Clothing modification kit no longer required for reskins, more reskin fixes
  modular_skyrat/code/game/mecha/mecha_construction_paths.dm
  modular_skyrat/code/game/mecha/mecha_parts.dm
  modular_skyrat/code/game/mecha/working/ripley.dm
  modular_skyrat/code/modules/clothing/refactor.dm
  modular_skyrat/code/modules/clothing/spacesuits/hardsuit.dm
  modular_skyrat/code/modules/mining/equipment/explorer_gear.dm
  modular_skyrat/icons/obj/clothing/uniform.dmi
Labels: Fix, Removal

#1483 [Map Edit: Mining Outpost] Trading Center
  _maps/RandomRuins/StationRuins/Lavaland/Mining_Station/Mining_Station_Public_01_Skyrat.dmm
Labels: Feature, Map Edit

#1506 [Not Modular]Borg Speed, and Water
  code/modules/mob/living/silicon/robot/robot.dm
  modular_skyrat/code/modules/mob/living/silicon/robot/robot.dm
  modular_skyrat/code/modules/reagents/reagents_containers/borghydro.dm
Labels: Feature, Tweak

#1514 Global projectile speed config modifier
  code/controllers/configuration/entries/game_options.dm
  code/modules/projectiles/projectile.dm
  config/game_options.txt
Labels: Config Update

#1538 [READY] [SPEEDMERGE] Fixing Viper (The Hair that i added recently)
  modular_skyrat/icons/mob/human_face.dmi
Labels: Fix, Needs Review

#1539 [READY] Changes Maint Loot spawner Lootcount from 5 to 2
  code/game/objects/effects/spawners/lootdrop.dm
Labels: Balance/Rebalance, Needs Review

#1460 Tons of Charlie Station Changes, Tweaks and Fixes
  modular_skyrat/_maps/RandomRuins/SpaceRuins/oldstation.dmm
Labels: Balance/Rebalance, Feature, Fix, Removal, TESTMERGE REQUESTED, Tweak

#1485 Update Mapmerge
  tools/mapmerge2/dmi.py
  tools/mapmerge2/dmm.py
  tools/mapmerge2/requirements.txt
  tools/mapmerge2/update_paths.py
Labels: Tools

#1569 Dynamic added_threat tweak
  code/game/gamemodes/dynamic/dynamic.dm
Labels: Tweak

#1350 Changes collar bans to use a trauma instead
  code/__DEFINES/admin.dm
  code/game/gamemodes/game_mode.dm
  code/game/machinery/cloning.dm
  code/modules/admin/admin.dm
  code/modules/admin/topic.dm
  modular_skyrat/code/controllers/subsystem/collarbans.dm
  modular_skyrat/code/game/objects/items/devices/radio/electropack.dm
  modular_skyrat/code/modules/admin/pacify_ban.dm
  tgstation.dme
Labels: Fix

#1486 allows for a minimum cryo afk time
  code/game/machinery/cryopod.dm
  config/skyrat/skyrat_config.txt
  modular_skyrat/code/controllers/configuration/entries/skyrat_config.dm
  modular_skyrat/code/game/machinery/cryopod.dm
  tgstation.dme
Labels: Config Update, Feature

#1558 Maintenance trash/loot piles.
  modular_skyrat/code/game/objects/structures/trash_pile.dm
  modular_skyrat/icons/obj/trash_piles.dmi
  tgstation.dme
Labels: Feature

#1495 Gondola Meat Alternative PR
  code/modules/reagents/chemistry/reagents/other_reagents.dm
  modular_skyrat/code/modules/reagents/chemistry/reagents/other_reagents.dm
  modular_skyrat/code/modules/reagents/chemistry/recipes/slime_extracts.dm
  tgstation.dme
Labels: Balance/Rebalance

#1493 Skyrat Boxstation Maint Loot Improvements
  _maps/map_files/BoxStation/BoxStation_Skyrat.dmm
  code/game/machinery/deployable.dm
Labels: Feature, Map Edit

#1586 Changes to dynamic protected roles
  code/game/gamemodes/dynamic/dynamic_rulesets_midround.dm
  code/game/gamemodes/dynamic/dynamic_rulesets_roundstart.dm
Labels: Tweak

#1570 Maintenance Loot Feedback PR
  modular_skyrat/code/_globalvars/lists/maintenance_loot.dm
  modular_skyrat/code/game/objects/effects/spawners/lootdrop.dm
  tgstation.dme
Labels: Balance/Rebalance

#764 [READY] [Modular] Mech-fabs can now be attached to bluespace storage silos.
  code/game/mecha/mech_fabricator.dm
  modular_skyrat/code/game/mecha/mech_fabricator.dm
Labels: Needs Review, Tweak

#1522 [READY][ACTUALLYMODULARTHISTIME] Naga cyber-tail, slightly thicker displays, and longer synth snoots!
  modular_skyrat/code/modules/mob/dead/new_player/sprite_accessories/snouts.dm
  modular_skyrat/code/modules/mob/dead/new_player/sprite_accessories/tails.dm
  modular_skyrat/icons/mob/mam_taur.dmi
  modular_skyrat/icons/mob/synthliz_snouts.dmi
  modular_skyrat/icons/mob/synthliz_tails.dmi
Labels: Code Improvement, Feature, Needs Review, Sprites

#1576 IC Admin Quick Spawn
  code/datums/helper_datums/teleport.dm
  code/modules/admin/verbs/debug.dm
  code/modules/mob/dead/observer/observer.dm
  icons/mob/actions/actions_spells.dmi
  modular_citadel/code/modules/spells/spell.dm
  modular_skyrat/code/modules/mob/dead/observer/observer.dm
  tgstation.dme
Labels: Administration, Sprites

#1596 Revert "."
  modular_citadel/code/modules/client/loadout/__donator.dm
  modular_skyrat/code/game/objects/items/plushies.dm
  modular_skyrat/code/game/objects/items/storage/bags.dm
  modular_skyrat/code/modules/vending/engivend.dm
  modular_skyrat/icons/obj/plushies.dmi
  modular_skyrat/icons/obj/tools.dmi
  tgstation.dme
Labels: Revert

#1599 Fixes Plasma/Uranium Objects Made Via Exosuit Fabricator
  modular_skyrat/code/game/mecha/mech_fabricator.dm
Labels: Fix

#1598 [ready] Update dynamic_rulesets_midround.dm
  code/controllers/configuration/entries/game_options.dm
  code/game/gamemodes/dynamic/dynamic.dm
  code/game/gamemodes/dynamic/dynamic_rulesets_midround.dm
  code/modules/projectiles/projectile.dm
Labels: Code Improvement, Config Update, Needs Review

#1592 Eye modules disable when unconscious
  modular_skyrat/code/modules/surgery/organs/eyes.dm
  tgstation.dme
Labels: Code Improvement, Feature

#1584 [READY] [HOTFIX] Install a copy of Counter Strike Source on Snowdin
  _maps/RandomZLevels/away_mission/snowdin.dmm
Labels: Fix, Map Edit, Needs Review

#1585 [FIX] Explorer digitigrade & taur fix
  modular_skyrat/code/modules/mining/equipment/explorer_gear.dm
Labels: Fix

#1602 Trashpile fixes and tweaks.
  modular_skyrat/code/game/objects/structures/trash_pile.dm
Labels: Fix, Tweak

#1603 [Map Edit: Box] Atmos fixes
  _maps/map_files/BoxStation/BoxStation_Skyrat.dmm
Labels: Feature, Map Edit, Removal

#1504 [Map Edit: Box, Delta, Pubby, Meta] Two Surgery Tables
  _maps/map_files/BoxStation/BoxStation_Skyrat.dmm
  _maps/map_files/Deltastation/DeltaStation2_Skyrat.dmm
  _maps/map_files/MetaStation/MetaStation_Skyrat.dmm
  _maps/map_files/PubbyStation/PubbyStation_Skyrat.dmm
Labels: Currently Testmerged, Feature, Map Edit

#1623 IC-Friendly admin spawner enhancements
  code/datums/mind.dm
  code/game/objects/items/storage/boxes.dm
  modular_citadel/code/game/objects/items/cards_ids.dm
  modular_citadel/code/modules/clothing/outfits/standard.dm
  modular_citadel/code/modules/spells/spell.dm
  modular_skyrat/code/modules/mob/dead/observer/observer.dm
  tgstation.dme
Labels: Administration

#1624 Better admin tickets
  code/modules/admin/verbs/adminhelp.dm
  code/modules/admin/verbs/adminpm.dm
Labels: Administration

#1628 Removes botany chem dispensers but adds botany supplies box with chems and more..
  _maps/map_files/BoxStation/BoxStation_Skyrat.dmm
  _maps/map_files/Deltastation/DeltaStation2_Skyrat.dmm
  _maps/map_files/KiloStation/KiloStation_Skyrat.dmm
  _maps/map_files/MetaStation/MetaStation_Skyrat.dmm
  _maps/map_files/PubbyStation/PubbyStation_Skyrat.dmm
  modular_skyrat/code/game/objects/items/circuitboards/machine_circuitboards.dm
  modular_skyrat/code/game/objects/items/storage/boxes.dm
  modular_skyrat/code/game/objects/structures/crates_lockers/closets/secure/hydroponics.dm
  modular_skyrat/code/modules/reagents/chemistry/machinery/chem_dispenser.dm
  modular_skyrat/code/modules/reagents/reagent_containers/bottle.dm
  modular_skyrat/code/modules/research/designs/machine_desings/machine_designs_service.dm
  modular_skyrat/code/modules/research/techweb/all_nodes.dm
  tgstation.dme
Labels: Feature, Map Edit, Removal

#1568 plasmafolk genital selection enabling
  code/modules/mob/living/carbon/human/species_types/plasmamen.dm
Labels: Tweak

#1626 [Box]Replaces blast doors in lawyer/blueshield office with auctall shutters
  _maps/map_files/BoxStation/BoxStation_Skyrat.dmm
Labels: Map Edit, Tweak
