Repository Skyrat-SS13/Skyrat13, pull requests merged in 2020-10, with the labels that each got.

#3589 Fixes an ancient botany bug
  code/modules/hydroponics/hydroponics.dm
Labels: Fix

#3597 [Fix] Boxstation Fixes
  _maps/map_files/BoxStation/BoxStation_Skyrat.dmm
Labels: Fix, Map Edit

#3598 EORG will no longer teleport ghosts
  modular_skyrat/code/_HELPERS/roundend.dm
Labels: Fix

#3595 Fixes the synth chassis restoration surgery
  modular_skyrat/code/modules/surgery/robot_chassis_restoration.dm
Labels: Fix

#3605 Removes tools from the boxstation kinkmate vendor.
  _maps/map_files/BoxStation/BoxStation_Skyrat.dmm
Labels: Map Edit, Removal

#3604 Bloodsucker tweaks to make them less restrictive for roleplay
  code/modules/antagonists/bloodsucker/bloodsucker_sunlight.dm
  code/modules/mob/living/carbon/human/species_types/vampire.dm
Labels: Tweak

#3609 Deer toy
  code/game/objects/items/plushes.dm
  icons/obj/plushes.dmi
  modular_skyrat/sound/voice/deerplush.ogg
Labels: Feature, Sprites

#3608 Makes vampires able to forcefully level up++
  code/modules/antagonists/bloodsucker/bloodsucker_sunlight.dm
  code/modules/antagonists/bloodsucker/datum_bloodsucker.dm
  code/modules/antagonists/bloodsucker/powers/forcelevel.dm
  tgstation.dme
Labels: Feature, Tweak

#3611 Tile Floofing 2
  modular_skyrat/code/game/objects/items/stacks/tiles/tile_reskinning.dm
  modular_skyrat/icons/obj/tiles.dmi
Labels: Code Improvement, Fix, hacktoberfest-accepted

#3616 [Fix] Mining conscription access no longer give mining bay access
  code/modules/mining/machine_vending.dm
Labels: Fix

#3619 Fixes xeno microbes and reagent splits etc.
  code/modules/reagents/chemistry/reagents/other_reagents.dm
Labels: Fix

#3630 Fixes dynamic lighting not counting for visible messages
  code/modules/lighting/lighting_turf.dm
Labels: Fix

#3632 Adds Mining Tech/Foreman Icons For ID Cards And SecHUD
  icons/obj/card.dmi
  modular_skyrat/code/modules/jobs/access.dm
  modular_skyrat/icons/mob/hud.dmi
Labels: Feature, Sprites

#3635 Gives everything more /tg/ look
  icons/mob/clothing/taur_canine.dmi
  icons/mob/clothing/taur_naga.dmi
  modular_skyrat/icons/mob/clothing/head.dmi
  modular_skyrat/icons/mob/clothing/head_muzzled.dmi
  modular_skyrat/icons/mob/clothing/head_vox.dmi
  modular_skyrat/icons/mob/clothing/mask.dmi
  modular_skyrat/icons/mob/clothing/mask_muzzled.dmi
  modular_skyrat/icons/mob/clothing/mask_vox.dmi
  modular_skyrat/icons/mob/clothing/suit.dmi
  modular_skyrat/icons/mob/clothing/suit_digi.dmi
  modular_skyrat/icons/mob/clothing/taur_naga.dmi
  modular_skyrat/icons/obj/clothing/hats.dmi
  modular_skyrat/icons/obj/clothing/masks.dmi
  modular_skyrat/icons/obj/clothing/suits.dmi
  modular_skyrat/icons/obj/computermath.dmi
  modular_skyrat/icons/obj/radio.dmi
  modular_skyrat/icons/obj/tools.dmi
Labels: Sprites

#3628 high luminosity eyes unconsciousness stupidity
  code/__DEFINES/modular_skyrat/signals.dm
  code/datums/status_effects/debuffs.dm
  modular_skyrat/code/modules/surgery/organs/organ_types/subtypes/eyes/eyes_robotic.dm
Labels: Fix

#3620 Adds a antag species blacklist and applies it to mostly robotic species.
  code/game/gamemodes/bloodsucker/bloodsucker.dm
  code/game/gamemodes/changeling/changeling.dm
  code/game/gamemodes/game_mode.dm
Labels: Feature, Tweak

#3637 Deletes combat knife cargo order.
  code/modules/cargo/packs/goodies.dm
Labels: Removal

#3636 [Halloween] Jacq fixes 2020 edition
  code/modules/holiday/halloween/jacqueen.dm
Labels: Fix, Tweak

#3638 VR Preferences Fix
  code/__DEFINES/_flags/_flags.dm
  code/__HELPERS/_lists.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/vore/eating/living.dm
  code/modules/vore/eating/vorepanel.dm
Labels: Fix
