Repository Skyrat-SS13/Skyrat13, pull requests merged in 2020-09, with the labels that each got.

#3492 Check the bloodsucker flag Dynamic!!
  code/game/gamemodes/dynamic/dynamic_rulesets_latejoin.dm
Labels: Fix

#3504 Small Bobmed QoL changes
  code/game/objects/items/tools/weldingtool.dm
  code/modules/power/cable.dm
  modular_skyrat/code/datums/wounds/disembowel.dm
  modular_skyrat/code/datums/wounds/dismember.dm
Labels: Fix

#3505 Full heals remove embedded objects
  modular_skyrat/code/modules/mob/living/carbon/carbon.dm
Labels: Fix

#3495 RUNTIME IN UNSORTED.DM LINE 1093
  code/__HELPERS/icons.dm
  code/modules/asset_cache/asset_cache_client.dm
  code/modules/client/client_defines.dm
  interface/skin.dmf
Labels: Fix

#3503 Tech Armor Fixes
  code/modules/clothing/suits/armor.dm
  icons/mob/clothing/head.dmi
  icons/mob/clothing/head_muzzled.dmi
  icons/mob/clothing/suit.dmi
  icons/mob/clothing/suit_digi.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/suits.dmi
  modular_skyrat/code/game/objects/structures/crates_lockers/closets/secure/security.dm
Labels: Feature, Fix, Sprites

#3502 Fixed rogue pixels on digi sprites
  icons/mob/clothing/uniform_digi.dmi
  modular_skyrat/icons/mob/clothing/uniform_digi.dmi
Labels: Fix, Sprites

#3498 Ports updates to railings from tg
  _maps/map_files/debug/multiz.dmm
  code/__HELPERS/unsorted.dm
  code/game/objects/items/stacks/rods.dm
  code/game/objects/structures/fluff.dm
  code/game/objects/structures/railings.dm
  tgstation.dme
Labels: Feature, Map Edit

#3510 Fixes synthflesh
  modular_skyrat/code/modules/reagents/chemistry/reagents/medicine_reagents.dm
Labels: Fix

#3475 Box Medical Revert/Revamp
  _maps/map_files/BoxStation/BoxStation_Skyrat.dmm
Labels: Map Edit, Revert, Tweak

#3514 Belly body markings fix
  modular_skyrat/icons/mob/skyrat_markings.dmi
Labels: Fix

#3513 Various bugfixes and minor tweaks
  code/__DEFINES/construction.dm
  code/game/objects/items/RCD.dm
  code/game/objects/items/storage/belt.dm
  code/game/objects/items/storage/boxes.dm
  code/modules/antagonists/changeling/powers/mutations.dm
  code/modules/clothing/outfits/ert.dm
  code/modules/clothing/spacesuits/miscellaneous.dm
  code/modules/mob/living/life.dm
  code/modules/mob/living/living.dm
  modular_citadel/code/modules/clothing/outfits/standard.dm
  modular_skyrat/code/datums/traits/negative.dm
Labels: Fix, Tweak

#3515 Finally, good Robotics.
  _maps/map_files/BoxStation/BoxStation_Skyrat.dmm
Labels: Map Edit

#3519 Fixes SCP underwear
  code/__DEFINES/misc.dm
  modular_skyrat/code/modules/clothing/underwear/_underwear.dm
Labels: Fix

#3308 fixes funny descriptor code
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  modular_skyrat/code/datums/descriptors/_descriptor.dm
  modular_skyrat/code/datums/descriptors/descriptor_types/build.dm
  modular_skyrat/code/datums/descriptors/descriptor_types/height.dm
  modular_skyrat/code/modules/mob/living/carbon/human/species.dm
  tgstation.dme
Labels: Stale

#3493 You can now pick up simplemob bots
  modular_skyrat/code/modules/mob/living/simple_animal/bot/bot.dm
  modular_skyrat/code/modules/mob/living/simple_animal/bot/secbot.dm
  tgstation.dme
Labels: Feature

#3521 fixes floating hats with the zoomba borg skin
  code/modules/mob/living/silicon/robot/robot_modules.dm
Labels: Fix

#3529 Fixes a single warning on VSCode, underwear now appears proper on the clothesmate
  modular_skyrat/code/datums/diseases/advance/symptoms/heal.dm
  modular_skyrat/code/modules/clothing/underwear/shirts.dm
  modular_skyrat/code/modules/vending/clothesmate.dm
  modular_skyrat/icons/mob/clothing/underwear.dmi
  tgstation.dme
Labels: Fix

#3443 Emagged/Hacked cyborgs can no longer be detonated / locked down
  code/modules/mob/living/silicon/robot/robot.dm
Labels: Balance/Rebalance

#3522 2 Pirate bugfixes
  code/modules/events/pirates.dm
Labels: Fix

#3526 Removes the SWAT bepis node, moves its contents to a new cargo pack, except for the baton
  modular_skyrat/code/modules/cargo/packs/bloat.dm
  modular_skyrat/code/modules/research/designs/weapon_designs.dm
  modular_skyrat/code/modules/research/techweb/all_nodes.dm
  modular_skyrat/code/modules/research/techweb/nodes/bepis_nodes.dm
Labels: Feature, Removal

#3517 things contaminated with radiation now glow
  code/__DEFINES/layers_planes.dm
  code/datums/components/radioactive.dm
  code/datums/radiation_wave.dm
  code/modules/clothing/glasses/engine_goggles.dm
Labels: Feature

#3524 Scrubs out all credit cost related code on cloning
  modular_skyrat/code/game/machinery/cloning.dm
  modular_skyrat/code/game/machinery/computer/cloning.dm
  modular_skyrat/code/game/machinery/exp_cloner.dm
Labels: Tweak

#3533 Adds Psychologist, Mining Foreman and Mining Technician into related loadout role defines
  modular_skyrat/code/modules/client/loadout/_defines.dm
Labels: Fix

#3527 Species that can't scar shouldn't scar
  modular_skyrat/code/datums/wounds/scars/_scars.dm
Labels: Fix

#3532 Reverts shotgun buffs and uses TG's wound stats
  code/modules/projectiles/projectile/bullets/shotgun.dm
Labels: Balance/Rebalance, Revert

#3485 Blueshield Weapon Beacon/Bugfixes
  modular_skyrat/code/game/objects/structures/crates_lockers/closets/secure/security.dm
  modular_skyrat/code/modules/clothing/suits/armor.dm
  modular_skyrat/code/modules/jobs/job_types/blueshield.dm
  modular_skyrat/code/modules/projectiles/guns/energy/nuclear.dm
  modular_skyrat/icons/mob/clothing/suit_digi.dmi
  modular_skyrat/icons/mob/inhands/weapons/guns_lefthand.dmi
  modular_skyrat/icons/mob/inhands/weapons/guns_righthand.dmi
  modular_skyrat/icons/obj/clothing/suits.dmi
  modular_skyrat/icons/obj/guns/energy.dmi
Labels: Feature

#3547 Revert "Replaces the Malfunctioning AI Nuclear annoucement" (Ear-Rape Removal)
  sound/announcer/classic/aimalf.ogg
Labels: Revert, Sound

#3379 Nerfs some funny PKA mods
  code/modules/projectiles/guns/energy/kinetic_accelerator.dm
  modular_skyrat/code/modules/projectiles/guns/energy/kinetic_accelerator.dm
Labels: Balance/Rebalance

#3103 [s] wow toys are pretty realistic nowadays
  code/game/objects/items/toys.dm
Labels: Stale

#3525 Improvements to unconsciouness messages on examine
  code/modules/mob/living/carbon/examine.dm
  code/modules/mob/living/carbon/human/examine.dm
Labels: Balance/Rebalance

#3390 [READY]Lizard has Brim now
  code/modules/mob/living/carbon/human/dummy.dm
  code/modules/surgery/organs/tails.dm
Labels: Fix, Needs Review

#3434 Blob Nerf
  code/__DEFINES/antagonists.dm
  code/_onclick/hud/blob_overmind.dm
  code/modules/antagonists/blob/blob/blobs/blob_mobs.dm
  code/modules/antagonists/blob/blob/blobs/core.dm
  code/modules/antagonists/blob/blob/blobs/factory.dm
  code/modules/antagonists/blob/blob/blobs/node.dm
  code/modules/antagonists/blob/blob/blobs/resource.dm
  code/modules/antagonists/blob/blob/powers.dm
  code/modules/antagonists/blob/blob/theblob.dm
Labels: Balance/Rebalance, Fix

#3549 Removes spacevine space spreading, removes spacevine door opening, adds spacevine player scalling
  code/modules/events/spacevine.dm
Labels: Balance/Rebalance, Removal

#3478 [READY] Reworks rewind camera
  code/modules/research/xenobiology/crossbreeding/burning.dm
  modular_skyrat/code/modules/research/xenobiology/crossbreeding/burning.dm
Labels: Balance/Rebalance, Needs Review

#3449 All station goals, all the time (& 2 bugfixes)
  code/game/gamemodes/game_mode.dm
  code/modules/power/tesla/energy_ball.dm
  modular_skyrat/code/modules/mob/living/simple_animal/parrot.dm
Labels: Fix, Tweak

#3561 Changed Terror spider's key
  code/__DEFINES/say.dm
Labels: Fix

#3560 Fixes not being able to remove scars in the scar setup
  code/modules/client/preferences.dm
Labels: Fix

#3564 Fixes cobblestone & grass making lattices upon explosions
  modular_skyrat/code/game/turfs/open/floor/planetfloor.dm
  modular_skyrat/code/game/turfs/open/floor/plating/lavaland_jungle.dm
Labels: Fix

#3563 Crayon edit
  code/game/objects/items/crayons.dm
  icons/obj/crayons.dmi
Labels: Feature, Good First PR, Sprites, Tweak

#3567 Chess - Sprite Improvement
  icons/obj/chess.dmi
Labels: Feature, Sprites

#3570 Fixes sticky tape prefix spam
  modular_skyrat/code/game/objects/items/stacks/tape.dm
Labels: Fix

#3557 Combat music again
  code/__DEFINES/sound.dm
  code/controllers/subsystem/processing/quirks.dm
  code/datums/components/combat_mode.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/mob/living/living_combat.dm
  modular_skyrat/sound/music/deathsquads.ogg
  modular_skyrat/sound/music/hot_plates.ogg
  modular_skyrat/sound/music/thunderdome.ogg
Labels: Sound

#3568 Splits *clap emote up
  code/modules/mob/living/carbon/emote.dm
  sound/misc/golfclap.ogg
Labels: Feature, Sound, Tweak

#3520 cloning other people no longer gives you a bad mood event
  modular_skyrat/code/datums/mood_events/generic_negative_events.dm
  modular_skyrat/code/game/machinery/computer/cloning.dm
Labels: Balance/Rebalance

#3562 Moves Cafe Teleport
  _maps/map_files/generic/CentCom_Skyrat.dmm
Labels: Map Edit, Tweak

#3574 TGUI item information
  code/__DEFINES/modular_skyrat/signals.dm
  code/_onclick/hud/human.dm
  modular_skyrat/code/_onclick/hud/iteminfo.dm
  modular_skyrat/code/datums/elements/item_info.dm
  modular_skyrat/code/game/objects/items.dm
  modular_skyrat/code/game/objects/obj.dm
  modular_skyrat/code/modules/mob/living/carbon/carbon.dm
  modular_skyrat/icons/mob/screen_gen.dmi
  tgstation.dme
  tgui-next/packages/tgui/interfaces/ItemInfo.js
  tgui-next/packages/tgui/routes.js
Labels: Feature, UI

#3590 [Fastmerge] [Fix] [Phone PR] Fixes accidental bug with biolumi lights
  modular_skyrat/code/game/objects/structures/flora.dm
Labels: Fix

#3500 Improvised Weapons... Part 3?
  code/datums/components/crafting/guncrafting.dm
  code/datums/components/crafting/recipes/recipes_weapon_and_ammo.dm
  code/game/gamemodes/gangs/gang_items.dm
  code/game/objects/effects/spawners/lootdrop.dm
  code/modules/projectiles/ammunition/energy/laser.dm
  code/modules/projectiles/guns/ballistic/pistol.dm
  code/modules/projectiles/guns/ballistic/revolver.dm
  code/modules/projectiles/guns/ballistic/shotgun.dm
  code/modules/projectiles/guns/energy/laser.dm
  code/modules/projectiles/projectile/beams.dm
  code/modules/projectiles/projectile/bullets/pistol.dm
  icons/mob/inhands/weapons/guns_lefthand.dmi
  icons/mob/inhands/weapons/guns_righthand.dmi
  modular_skyrat/code/modules/projectiles/guns/ballistic/revolver.dm
  modular_skyrat/code/modules/projectiles/guns/ballistic/shotgun.dm
  modular_skyrat/icons/mob/inhands/64x_guns_left.dmi
  modular_skyrat/icons/mob/inhands/64x_guns_right.dmi
  modular_skyrat/icons/mob/inhands/weapons/64x_guns_left.dmi
  modular_skyrat/icons/mob/inhands/weapons/64x_guns_right.dmi
  modular_skyrat/icons/obj/guns/projectile40x32.dmi
  modular_skyrat/sound/weapons/bolt_in.ogg
  modular_skyrat/sound/weapons/bolt_out.ogg
Labels: Feature, Sprites

#3579 Kneecaps fusion temperature limit
  code/__DEFINES/reactions.dm
  code/modules/atmospherics/gasmixtures/reactions.dm
Labels: Balance/Rebalance

#3538 Nerfs sonic jackhammer
  code/game/turfs/simulated/wall/reinf_walls.dm
  code/game/turfs/simulated/walls.dm
  code/modules/mining/equipment/mining_tools.dm
Labels: Tweak

#3558 Boxstation Security - New Prison & Aesthetic Overhaul
  _maps/map_files/BoxStation/BoxStation_Skyrat.dmm
Labels: Enhancement, Feature, Fix, Map Edit, Tweak

#3586 Various QoL changes for drones
  code/__DEFINES/say.dm
  code/datums/saymode.dm
  code/modules/keybindings/keybind/robot.dm
  code/modules/language/language_holder.dm
  code/modules/mob/living/simple_animal/friendly/drone/_drone.dm
Labels: Balance/Rebalance, Feature, Tweak

#3594 [Fix] Boxstation Bugfixing - Posters & Prisons
  _maps/map_files/BoxStation/BoxStation_Skyrat.dmm
Labels: Fix, Map Edit
