Repository Skyrat-SS13/Skyrat13, pull requests merged in 2020-02, with the labels that each got.

#3 Removes namelessness.
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
Labels: Removal

#4 A bit of basic stuff ported.
  code/controllers/subsystem/input.dm
  code/game/world.dm
  code/modules/client/client_procs.dm
  code/modules/client/preferences.dm
  code/modules/events/_event.dm
  code/modules/mob/dead/new_player/new_player.dm
  code/modules/mob/living/carbon/alien/special/alien_embryo.dm
  code/modules/mob/living/carbon/life.dm
  code/modules/mob/living/life.dm
  code/modules/mob/living/say.dm
  code/modules/mob/say.dm
  config/title_screens/images/title1.dmi
  config/title_screens/images/title2.dmi
  config/title_screens/images/title3.dmi
  config/title_screens/images/title4.dmi
  config/title_screens/images/title5.dmi
  config/title_screens/images/wolvesingreyclothing.dmi
  html/templates/header.html
  modular_citadel/code/modules/mob/living/carbon/human/human_movement.dm
  modular_skyrat/code/datums/ai_laws.dm
  modular_skyrat/code/game/gamemodes/objective.dm
  modular_skyrat/code/game/world.dm
  modular_skyrat/code/modules/events/alien_infestation.dm
  modular_skyrat/code/modules/events/anomaly_flux.dm
  modular_skyrat/code/modules/events/anomaly_grav.dm
  modular_skyrat/code/modules/events/anomaly_pyro.dm
  modular_skyrat/code/modules/events/communications_blackout.dm
  modular_skyrat/code/modules/events/electrical_storm.dm
  modular_skyrat/code/modules/events/operative.dm
  modular_skyrat/code/modules/events/radiation_storm.dm
  modular_skyrat/code/modules/events/spontaneous_appendicitis.dm
  modular_skyrat/code/modules/mob/say.dm
  modular_skyrat/code/modules/mob/typing_indicator.dm
  tgstation.dme
Labels: Config Update

#108 Added instructor cloaks
  modular_skyrat/code/modules/clothing/suits/cloaks.dm
  modular_skyrat/icons/mob/neck.dmi
  modular_skyrat/icons/obj/clothing/neck.dmi
  tgstation.dme
Labels: Feature

#169 epic snouts
  modular_skyrat/code/modules/mob/dead/new_player/sprite_accessories/snouts.dm
  modular_skyrat/icons/mob/mam_snouts.dmi
Labels: Feature

#200 Poisonous meatwheat made no longer poisonous.
  modular_skyrat/code/modules/food_and_drinks/food/snacks/meat.dm
  tgstation.dme
Labels: Tweak

#233 Changed vote timer from 20 to 2 minutes.
  code/controllers/subsystem/ticker.dm
Labels: Tweak

#280 Comments out the Valentine's holiday
  code/modules/holiday/holidays.dm
Labels: Removal

#278 Adds diethylamine and saltpetre bottles to the biogenerator's designs
  code/modules/hydroponics/hydroponics.dm
  modular_skyrat/code/modules/reagents/reagent_containers/bottle.dm
  modular_skyrat/code/modules/research/designs/biogenerator_designs.dm
  tgstation.dme
Labels: Feature

#269 Adds a 10mm makeshift pistol to the game.
  modular_skyrat/code/datums/components/crafting/recipes/recipes_weapon_and_ammo.dm
  modular_skyrat/code/modules/projectiles/boxes_magazines/external/pistol.dm
  modular_skyrat/code/modules/projectiles/guns/ballistic/pistol.dm
  modular_skyrat/icons/obj/ammo.dmi
  modular_skyrat/icons/obj/guns/projectile.dmi
  tgstation.dme
Labels: Feature

#287 Hissing
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  modular_skyrat/code/modules/surgery/organs/tongue.dm
  tgstation.dme
Labels: Feature, Removal

#294 Pick up text/sounds
  modular_skyrat/code/game/objects/items.dm
  modular_skyrat/code/modules/projectiles/gun.dm
  tgstation.dme
Labels: Feature

#296 OOC Notes
  code/modules/client/preferences.dm
  code/modules/mob/living/carbon/human/examine.dm
  modular_citadel/code/modules/client/preferences_savefile.dm
  modular_skyrat/code/modules/mob/living/carbon/human/human.dm
  tgstation.dme
Labels: Feature

#299 FIXES OOC NOTES
  modular_citadel/code/modules/client/preferences_savefile.dm
Labels: Fix

#254 Adds a full civil protection (HL2) outfit
  modular_skyrat/code/modules/clothing/head/helmet.dm
  modular_skyrat/code/modules/clothing/masks/hailer.dm
  modular_skyrat/code/modules/clothing/suits/armor.dm
  modular_skyrat/code/modules/clothing/under/jobs/security.dm
  modular_skyrat/code/modules/vending/autodrobe.dm
  modular_skyrat/code/modules/vending/wardrobes.dm
  modular_skyrat/icons/mob/head.dmi
  modular_skyrat/icons/mob/head_muzzled.dmi
  modular_skyrat/icons/mob/mask.dmi
  modular_skyrat/icons/mob/mask_muzzled.dmi
  modular_skyrat/icons/mob/suit.dmi
  modular_skyrat/icons/mob/suit_digi.dmi
  modular_skyrat/icons/mob/uniform.dmi
  modular_skyrat/icons/mob/uniform_digi.dmi
  modular_skyrat/icons/obj/clothing/hats.dmi
  modular_skyrat/icons/obj/clothing/masks.dmi
  modular_skyrat/icons/obj/clothing/suits.dmi
  modular_skyrat/icons/obj/clothing/uniforms.dmi
  modular_skyrat/sound/voice/complionator/die1.ogg
  modular_skyrat/sound/voice/complionator/die2.ogg
  modular_skyrat/sound/voice/complionator/die3.ogg
  modular_skyrat/sound/voice/complionator/die4.ogg
  modular_skyrat/sound/voice/complionator/dontmove2.ogg
  modular_skyrat/sound/voice/complionator/holditrightthere.ogg
  modular_skyrat/sound/voice/complionator/investigate.ogg
  modular_skyrat/sound/voice/complionator/movealong.ogg
  modular_skyrat/sound/voice/complionator/moveit.ogg
  modular_skyrat/sound/voice/complionator/off1.ogg
  modular_skyrat/sound/voice/complionator/off2.ogg
  modular_skyrat/sound/voice/complionator/off3.ogg
  modular_skyrat/sound/voice/complionator/off4.ogg
  modular_skyrat/sound/voice/complionator/officerneedsassistance.ogg
  modular_skyrat/sound/voice/complionator/on1.ogg
  modular_skyrat/sound/voice/complionator/on2.ogg
  modular_skyrat/sound/voice/complionator/pickupthecan1.ogg
  modular_skyrat/sound/voice/complionator/watchit.ogg
  tgstation.dme
Labels: Feature, Sound, Sprites

#302 Bugfixing on the CP mask, as well as a new feature.
  modular_skyrat/code/modules/clothing/masks/hailer.dm
  modular_skyrat/sound/voice/complionator/pain1.ogg
  modular_skyrat/sound/voice/complionator/pain2.ogg
  modular_skyrat/sound/voice/complionator/pain3.ogg
  modular_skyrat/sound/voice/complionator/pain4.ogg
Labels: Feature, Fix, Sound

#303 Adds new loot to both the Legion and Blood Drunk
  modular_skyrat/code/modules/mining/equipment/kinetic_crusher.dm
  modular_skyrat/code/modules/mob/living/simple_animal/hostile/megafauna/blood_drunk_miner.dm
  modular_skyrat/code/modules/mob/living/simple_animal/hostile/megafauna/legion.dm
  modular_skyrat/code/modules/projectiles/guns/energy/kinetic_accelerator.dm
  modular_skyrat/icons/obj/guns/energy.dmi
  tgstation.dme
Labels: Feature

#339 Revert of #278 in favour of #332
  code/modules/hydroponics/hydroponics.dm
  modular_skyrat/code/modules/reagents/reagent_containers/bottle.dm
  modular_skyrat/code/modules/research/designs/biogenerator_designs.dm
  tgstation.dme
Labels: Revert

#324 Adds PKA mods for every megafauna.
  modular_skyrat/code/modules/mining/lavaland/necropolis_chests.dm
  modular_skyrat/code/modules/mob/living/simple_animal/hostile/megafauna/blood_drunk_miner.dm
  modular_skyrat/code/modules/mob/living/simple_animal/hostile/megafauna/hierophant.dm
  modular_skyrat/code/modules/mob/living/simple_animal/hostile/megafauna/legion.dm
  modular_skyrat/code/modules/mob/living/simple_animal/hostile/mining_mobs/elites/drakeling.dm
  modular_skyrat/code/modules/mob/living/simple_animal/hostile/mining_mobs/elites/elite.dm
  modular_skyrat/code/modules/projectiles/guns/energy/kinetic_accelerator.dm
  modular_skyrat/icons/mob/actions/actions_elites.dmi
  modular_skyrat/icons/mob/lavaland/lavaland_monsters.dmi
  tgstation.dme
Labels: Feature

#372 Adds cancel buttons to Say and Me
  modular_skyrat/code/modules/mob/say.dm
Labels: Feature

#373 Adds a new elite mob to the tumors: Candy
  modular_skyrat/_DEFINES/status_effects.dm
  modular_skyrat/code/datums/status_effects/debuffs.dm
  modular_skyrat/code/modules/mining/equipment/kinetic_crusher.dm
  modular_skyrat/code/modules/mining/lavaland/necropolis_chests.dm
  modular_skyrat/code/modules/mob/living/simple_animal/hostile/mining_mobs/elites/candy.dm
  modular_skyrat/code/modules/mob/living/simple_animal/hostile/mining_mobs/elites/drakeling.dm
  modular_skyrat/code/modules/mob/living/simple_animal/hostile/mining_mobs/elites/elite.dm
  modular_skyrat/code/modules/projectiles/guns/energy/kinetic_accelerator.dm
  modular_skyrat/code/modules/uplink/uplink_roles.dm
  modular_skyrat/icons/mob/actions/actions_elites.dmi
  modular_skyrat/icons/mob/lavaland/lavaland_elites.dmi
  modular_skyrat/icons/mob/lavaland/lavaland_monsters.dmi
  modular_skyrat/sound/misc/gorenest.ogg
  tgstation.dme
Labels: Feature, Tweak

#368 Adds the USP Match and the Metrocop hardsuit
  modular_skyrat/code/modules/clothing/spacesuits/hardsuit.dm
  modular_skyrat/code/modules/projectiles/ammunition/ballistic/pistol.dm
  modular_skyrat/code/modules/projectiles/boxes_magazines/ammo_boxes.dm
  modular_skyrat/code/modules/projectiles/boxes_magazines/external/pistol.dm
  modular_skyrat/code/modules/projectiles/guns/ballistic/pistol.dm
  modular_skyrat/code/modules/projectiles/projectile/pistol.dm
  modular_skyrat/code/modules/research/designs/autolathe_designs/autolathe_designs_sec_and_hacked.dm
  modular_skyrat/code/modules/vending/security.dm
  modular_skyrat/icons/mob/head.dmi
  modular_skyrat/icons/mob/head_muzzled.dmi
  modular_skyrat/icons/mob/inhands/weapons/guns_lefthand.dmi
  modular_skyrat/icons/mob/inhands/weapons/guns_righthand.dmi
  modular_skyrat/icons/mob/suit.dmi
  modular_skyrat/icons/mob/suit_digi.dmi
  modular_skyrat/icons/obj/ammo.dmi
  modular_skyrat/icons/obj/clothing/hats.dmi
  modular_skyrat/icons/obj/clothing/suits.dmi
  modular_skyrat/icons/obj/guns/projectile.dmi
  modular_skyrat/sound/weapons/uspshot.ogg
  tgstation.dme
Labels: Feature, Sound, Sprites

#382 Changes to time on job exp requirements
  code/modules/jobs/job_types/atmospheric_technician.dm
  code/modules/jobs/job_types/chemist.dm
  code/modules/jobs/job_types/clown.dm
  code/modules/jobs/job_types/detective.dm
  code/modules/jobs/job_types/geneticist.dm
  code/modules/jobs/job_types/mime.dm
  code/modules/jobs/job_types/roboticist.dm
  code/modules/jobs/job_types/scientist.dm
  code/modules/jobs/job_types/security_officer.dm
  code/modules/jobs/job_types/station_engineer.dm
  code/modules/jobs/job_types/virologist.dm
  code/modules/jobs/job_types/warden.dm
Labels: Feature, Tweak

#383 Fixes simple mob emote spam
  code/datums/emotes.dm
Labels: Tweak

#395 Temporarily disables command bar typing indicator procs
  code/modules/mob/living/life.dm
Labels: Code Improvement

#390 Updates for Vox
  modular_skyrat/code/modules/clothing/masks/breath.dm
  modular_skyrat/code/modules/clothing/outfits/vox.dm
  modular_skyrat/code/modules/mob/dead/new_player/sprite_accessories/vox_accessories.dm
  modular_skyrat/icons/mob/facial_hair_vox.dmi
  modular_skyrat/icons/mob/hair_vox.dmi
  modular_skyrat/icons/mob/vox_parts_greyscale.dmi
  tgstation.dme
Labels: Feature, Tweak

#391 Fixes Experimental Welding Tool Upgrades
  modular_skyrat/code/modules/research/designs/mechfabricator_designs.dm
Labels: Fix

#404 Nerfs USP
  modular_skyrat/code/modules/projectiles/projectile/pistol.dm
Labels: Balance/Rebalance

#414 Fixes runtime error with auto hiss by placing it into a new speech modification system
  modular_skyrat/code/datums/speech_mod/_speech_mod.dm
  modular_skyrat/code/datums/speech_mod/auto_hiss.dm
  modular_skyrat/code/modules/mob/living/carbon/human/auto_hiss.dm
  modular_skyrat/code/modules/surgery/organs/tongue.dm
  tgstation.dme
Labels: Code Improvement, Fix

#420 Adds a visual SSD indicator to sprite and SSD time to examines
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/mob/living/death.dm
  code/modules/mob/living/login.dm
  code/modules/mob/living/logout.dm
  code/modules/mob/living/silicon/robot/examine.dm
  modular_skyrat/code/modules/mob/living/ssd_indicator.dm
  modular_skyrat/icons/mob/ssd_indicator.dmi
  tgstation.dme
Labels: Feature

#427 [Modular] Allows cyborgs/silicons to unlock expressconsole
  code/modules/cargo/expressconsole.dm
  modular_skyrat/code/modules/cargo/expressconsole.dm
  tgstation.dme
Labels: Tweak

#434 [Modular] Adds Wigs, the item, to clothesmate, and loadout
  modular_skyrat/code/modules/client/loadout/head.dm
  modular_skyrat/code/modules/clothing/head/misc_special.dm
  modular_skyrat/code/modules/vending/clothesmate.dm
  tgstation.dme
Labels: Feature, Tweak

#436 [Modular] Adds the polychromic cloak to loadout
  modular_skyrat/code/modules/client/loadout/neck.dm
  tgstation.dme
Labels: Feature

#450 Hotspots and fires but no conflicts this time, I hope
  modular_skyrat/code/modules/atmospherics/environmental/LINDA_fire.dm
  tgstation.dme
Labels: Balance/Rebalance, Code Improvement, Tweak

#435 [Modular] Service Borgs and Their Shakers!
  code/modules/reagents/reagent_containers/borghydro.dm
  modular_skyrat/code/modules/reagents/reagents_containers/borghydro.dm
  tgstation.dme
Labels: Tweak

#451 Event changes, travis have mercy
  modular_skyrat/code/controllers/subsystem/events.dm
  modular_skyrat/code/modules/events/meteor_wave.dm
  modular_skyrat/code/modules/events/pirates.dm
  tgstation.dme
Labels: Balance/Rebalance

#452 Adds the shambling miner minion and the necropolis priest elite to lavaland (Remade the PR because merg conflicts)
  modular_skyrat/code/game/objects/structures/lavaland/necropolis_tendril.dm
  modular_skyrat/code/modules/mining/equipment/kinetic_crusher.dm
  modular_skyrat/code/modules/mob/living/simple_animal/hostile/mining_mobs/elites/candy.dm
  modular_skyrat/code/modules/mob/living/simple_animal/hostile/mining_mobs/elites/drakeling.dm
  modular_skyrat/code/modules/mob/living/simple_animal/hostile/mining_mobs/elites/elite.dm
  modular_skyrat/code/modules/mob/living/simple_animal/hostile/mining_mobs/elites/fanaticminer.dm
  modular_skyrat/code/modules/mob/living/simple_animal/hostile/mining_mobs/shamblingminer.dm
  modular_skyrat/code/modules/procedural_mapping/mapGenerators/lavaland.dm
  modular_skyrat/icons/mob/actions/actions_elites.dmi
  modular_skyrat/icons/mob/inhands/axes_lefthand.dmi
  modular_skyrat/icons/mob/inhands/axes_righthand.dmi
  modular_skyrat/icons/mob/lavaland/lavaland_elites.dmi
  modular_skyrat/icons/mob/lavaland/lavaland_monsters.dmi
  modular_skyrat/icons/obj/lavaland/artefacts.dmi
  tgstation.dme
Labels: Feature, Sprites

#447 Legion core nerf
  modular_skyrat/code/modules/mining/equipment/regenerative_core.dm
Labels: Balance/Rebalance

#464 Shambling Miner hotfix
  modular_skyrat/code/game/turfs/simulated/floor/asteroid.dm
Labels: Fix

#465 Higher fake blue/greenshift chance
  code/game/gamemodes/game_mode.dm
Labels: Tweak

#459 Changed the default client fps to world.fps*2 for smoover movement.
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
Labels: Tweak
