Repository Skyrat-SS13/Skyrat13, pull requests merged in 2020-06, with the labels that each got.

#2297 the mothening - uplink one line fix edition
  code/datums/components/uplink.dm
Labels: Config Update

#2293 Revert "Clothing self equip delay"
  code/_onclick/hud/screen_objects.dm
  code/game/objects/items.dm
  code/game/objects/items/storage/_storage.dm
  code/modules/clothing/clothing.dm
  code/modules/clothing/spacesuits/_spacesuits.dm
  code/modules/mob/inventory.dm
Labels: Revert

#2315 Removes specism, ugly and beatiful quirks due to performance
  code/__DEFINES/traits.dm
  code/controllers/subsystem/processing/quirks.dm
  code/modules/mob/living/carbon/examine.dm
  modular_skyrat/code/datums/mood_events/generic_negative_events.dm
  modular_skyrat/code/datums/mood_events/generic_positive_events.dm
  modular_skyrat/code/datums/traits/good.dm
  modular_skyrat/code/datums/traits/negative.dm
  tgstation.dme
Labels: Removal

#2336 [READY] Fixes Dupe APC, Disposal Pipe Issue
  _maps/map_files/BoxStation/BoxStation_Skyrat.dmm
Labels: Fix, Map Edit, Needs Review

#2312 [Ready] Succubus tail
  code/modules/mob/dead/new_player/sprite_accessories/tails.dm
  modular_skyrat/icons/mob/mam_tails.dmi
Labels: Feature, Needs Review

#2311 [READY] Metastation: The Floofening - Let's make our Metastation be the prettiest out there!
  _maps/map_files/MetaStation/MetaStation_Skyrat.dmm
Labels: Balance/Rebalance, Feature, Fix, Map Edit, Needs Review, Removal, Tweak

#2344 [Map Edit] Minor Pubby Fix
  _maps/map_files/PubbyStation/PubbyStation_Skyrat.dmm
Labels: Fix, Map Edit

#2314 [Map Edit] Probable Syndicate Lava Fix
  modular_skyrat/_maps/RandomRuins/LavaRuins/lavaland_surface_syndicate_base1.dmm
Labels: Feature

#2346 Fixes extra sif spawn
  _maps/RandomRuins/LavaRuins/lavaland_surface_sif_spawn.dmm
  modular_skyrat/code/modules/mob/living/simple_animal/hostile/megafauna/sif.dm
Labels: Fix, Map Edit

#2121 morphcube improvements
  modular_skyrat/code/game/objects/items/devices/traitordevices.dm
Labels: Code Improvement

#2203 Revert "curb flip spam (#2138)"
  modular_skyrat/code/modules/mob/emote.dm
Labels: Revert

#2272 Round End Tatos
  code/__HELPERS/roundend.dm
Labels: Removal

#2300 Bold and brash
  code/modules/client/preferences.dm
  modular_skyrat/code/modules/reagents/chemistry/reagents/drink_reagents.dm
Labels: Grammar and Formatting

#2304 fixes energy butterfly not having an icon
  modular_skyrat/icons/obj/items_and_weapons.dmi
Labels: Fix

#2345 Fixes the executioner sword ranged delimb
  modular_skyrat/code/datums/components/crafting/crafting_results/swords.dm
Labels: Fix

#2343 Removes mention of Citadel Station from antag objectives.
  strings/flavor_objectives/ninja_syndie.txt
  strings/flavor_objectives/traitor.txt
Labels: Grammar and Formatting, Removal

#2317 Removes blood contract/Bottle of mayhem from bubblegum drops (replacement at a later point).
  modular_skyrat/code/modules/mining/lavaland/necropolis_chests.dm
Labels: Removal

#2210 Skyrat contributing standard
  .github/CONTRIBUTING.md
Labels: GitHub

#2360 [Fix/Balance] Cryptominers Deconstruct + More
  modular_skyrat/code/game/machinery/cryptominer/cryptominers.dm
Labels: Fix, Tweak

#2367 funny shovels go DEFCON2
  modular_skyrat/code/modules/mining/equipment/mining_tools.dm
  modular_skyrat/code/modules/research/designs/mining_designs.dm
  modular_skyrat/code/modules/research/techweb/nodes/tools_nodes.dm
  modular_skyrat/icons/obj/shovel.dmi
  tgstation.dme
Labels: Removal

#2382 Give engi & syndies extended tanks again
  code/game/objects/items/storage/boxes.dm
Labels: Fix

#2374 Eternal Mech Fixes
  code/game/mecha/working/ripley.dm
  modular_skyrat/code/game/mecha/mecha_construction_paths.dm
  modular_skyrat/code/modules/research/designs/mechfabricator_designs.dm
Labels: Fix

#2373 [Modular] ATMs
  _maps/RandomRuins/StationRuins/Lavaland/Mining_Station/Mining_Station_Public_01_Skyrat.dmm
  _maps/map_files/BoxStation/BoxStation_Skyrat.dmm
  _maps/map_files/Deltastation/DeltaStation2_Skyrat.dmm
  _maps/map_files/KiloStation/KiloStation_Skyrat.dmm
  _maps/map_files/MetaStation/MetaStation_Skyrat.dmm
  _maps/map_files/Mining/Lavaland_Skyrat.dmm
  _maps/map_files/PubbyStation/PubbyStation_Skyrat.dmm
  code/game/objects/items/cards_ids.dm
  code/game/objects/structures/crates_lockers/closets/secure/cargo.dm
  code/game/objects/structures/crates_lockers/closets/secure/engineering.dm
  code/game/objects/structures/crates_lockers/closets/secure/medical.dm
  code/game/objects/structures/crates_lockers/closets/secure/scientist.dm
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  code/modules/economy/account.dm
  modular_skyrat/code/game/machinery/atm.dm
  modular_skyrat/icons/obj/machines/terminals.dmi
  tgstation.dme
Labels: Feature, Map Edit

#2376 [Fix] Economy: Paycheck to Skyrat Jobs
  modular_skyrat/code/modules/jobs/job_types/blueshield.dm
  modular_skyrat/code/modules/jobs/job_types/brig_physician.dm
  modular_skyrat/code/modules/jobs/job_types/prisoner.dm
  modular_skyrat/code/modules/jobs/job_types/psychologist.dm
Labels: Feature

#2419 [Modular] Emag ATM, Less Enterable Money
  code/game/objects/items/cards_ids.dm
  modular_skyrat/code/game/machinery/atm.dm
  modular_skyrat/icons/obj/machines/terminals.dmi
Labels: Feature, Removal

#2420 [Fix] Cyborg RSF
  code/modules/mob/living/silicon/robot/robot_modules.dm
Labels: Fix

#2429 [Fix] ATM Duplication Bug
  modular_skyrat/code/game/machinery/atm.dm
Labels: Fix

#2450 [Salt-PR?] Prisoners are people too
  modular_skyrat/code/modules/jobs/job_types/prisoner.dm
Labels: Tweak

#2303 Removes lightdrawn component
  modular_skyrat/code/datums/components/crafting/lightdrawn.dm
  modular_skyrat/code/modules/mob/living/carbon/human/species_types/mothpeople.dm
  tgstation.dme
Labels: Removal

#2484 Loooc
  .vs/slnx.sqlite
  code/modules/goonchat/browserassets/css/browserOutput.css
  code/modules/goonchat/browserassets/css/browserOutput_dark.css
  modular_skyrat/code/modules/client/verbs/looc.dm
Labels: Administration

#2476 Flavor text can no longer inject html
  code/__HELPERS/text.dm
  code/datums/elements/flavor_text.dm
  code/modules/client/preferences.dm
Labels: Tweak

#2507 [Fix] Another ATM Exploit
  modular_skyrat/code/game/machinery/atm.dm
Labels: Fix

#2509 [Remove] Removing Codermonkey Tinfoil hat
  code/modules/mob/living/carbon/monkey/monkey.dm
Labels: Removal

#2470 [Fix] Cryptominers Researchable
  modular_skyrat/code/modules/research/techweb/nodes/bluespace_nodes.dm
Labels: Fix

#2453 uplink balance
  modular_skyrat/code/modules/uplink/uplink_bundles.dm
  tgstation.dme
Labels: Balance/Rebalance

#2478 DeltaStation & MetaStation QoL stuff
  _maps/map_files/Deltastation/DeltaStation2_Skyrat.dmm
  _maps/map_files/MetaStation/MetaStation_Skyrat.dmm
Labels: Feature, Fix, Grammar and Formatting, Map Edit, Tweak

#2408 Spiders that are of horror may count as a spider
  code/game/objects/items/weaponry.dm
Labels: Feature

#2439 Slightly better *peep emote 🐦
  modular_citadel/code/modules/mob/cit_emotes.dm
  modular_skyrat/code/modules/mob/emote.dm
  modular_skyrat/sound/voice/peep_once.ogg
Labels: Feature, Sound, Tweak

#2211 Meme name removal because we're MRP-HRP.
  strings/names/death_commando.txt
Labels: Removal, Tweak

#2393 hardsyncs some outdated dmi's
  icons/obj/ammo.dmi
  icons/obj/guns/projectile.dmi
Labels: Sprites

#2217 Lifts caps from synthetic limbs
  modular_skyrat/code/game/objects/items/tools/weldingtool.dm
  modular_skyrat/code/modules/power/cable.dm
  tgstation.dme
Labels: Balance/Rebalance, Stale

#2527 Fixbarrels
  modular_skyrat/code/modules/hydroponics/fermenting_barrel.dm
Labels: Fix

#2266 Ambitions and Objectives
  code/__DEFINES/admin.dm
  code/__DEFINES/antagonists.dm
  code/__DEFINES/cooldowns.dm
  code/__DEFINES/say.dm
  code/__HELPERS/_lists.dm
  code/__HELPERS/roundend.dm
  code/controllers/configuration/entries/general.dm
  code/datums/datum.dm
  code/datums/mind.dm
  code/modules/admin/admin.dm
  code/modules/admin/antag_panel.dm
  code/modules/admin/topic.dm
  code/modules/antagonists/_common/antag_datum.dm
  code/modules/antagonists/changeling/powers/absorb.dm
  code/modules/antagonists/cult/cult.dm
  code/modules/mob/living/login.dm
  code/modules/mob/mob.dm
  modular_skyrat/code/game/gamemodes/objective.dm
  tgstation.dme
Labels: Config Update, Feature

#2388 Fixes Squish head issues on anthromorphs
  modular_citadel/icons/mob/mutant_bodyparts.dmi
Labels: Fix

#2530 missed dmi from the pea PR
  icons/obj/food/food.dmi
Labels: Sprites

#2475 fix laser rifle
  modular_skyrat/code/datums/components/crafting/crafting_results/swords.dm
  modular_skyrat/code/modules/projectiles/guns/energy/laser.dm
Labels: Fix

#2505 Added new skins for borgs
  code/modules/mob/living/silicon/robot/robot_modules.dm
  modular_skyrat/code/modules/mob/living/silicon/robot/robot_modules.dm
  modular_skyrat/icons/mob/clownborgs.dmi
  modular_skyrat/icons/mob/moreborgsmodels.dmi
Labels: Feature, Removal

#2490 Normalizes Cheems
  modular_skyrat/code/modules/mob/living/simple_animal/friendly/doges.dm
Labels: Fix, Tweak

#2529 Makes the blunderbuss able to be stored in armor vests
  code/__DEFINES/inventory.dm
Labels: Balance/Rebalance

#2532 Removes fusion
  code/modules/atmospherics/gasmixtures/reactions.dm
Labels: Removal

#2506 Fashion! Cloaks Edition
  code/modules/clothing/suits/cloaks.dm
  modular_skyrat/code/modules/mob/dead/new_player/sprite_accessories/hair_head.dm
  modular_skyrat/icons/mob/clothing/neck.dmi
  modular_skyrat/icons/mob/human_face.dmi
Labels: Feature, Fix, Sprites

#2508 [Fix] VSCode now can debug
  .vscode/extensions.json
  .vscode/launch.json
  .vscode/settings.json
  code/game/world.dm
Labels: Feature, Fix

#2534 Revert "Removes fusion"
  code/modules/atmospherics/gasmixtures/reactions.dm
Labels: Removal, Revert

#2535 fixes engi shit
  code/game/objects/items/storage/belt.dm
  code/modules/clothing/spacesuits/hardsuit.dm
  code/modules/clothing/suits/miscellaneous.dm
Labels: Tweak

#2547 Github decided that changing an icon name isn't considered a change.
  modular_skyrat/icons/mob/human_face.dmi
Labels: Fix

#2363 Makes maint energy more sane
  code/game/turfs/simulated/walls.dm
  modular_skyrat/code/_DEFINES/status_effects.dm
  modular_skyrat/code/datums/status_effects/buffs.dm
  modular_skyrat/code/modules/food_and_drinks/drinks/drinks.dm
  modular_skyrat/code/modules/reagents/chemistry/reagents/drink_reagents.dm
Labels: Tweak

#2548 Fixes modular modifications of loadout
  modular_skyrat/code/modules/client/loadout/backpack.dm
  modular_skyrat/code/modules/client/loadout/uniform.dm
Labels: Fix, Removal

#2549 Fixes DeltaStation mail sorting
  _maps/map_files/Deltastation/DeltaStation2_Skyrat.dmm
Labels: Fix, Map Edit

#2538 Admun verb organization
  code/modules/admin/admin_verbs.dm
  code/modules/admin/secrets.dm
  code/modules/admin/topic.dm
  code/modules/admin/verbs/randomverbs.dm
  modular_skyrat/code/modules/admin/admin_verbs.dm
Labels: Administration

#2564 Buffs Bluespace Tech's hardsuits
  modular_citadel/code/modules/clothing/outfits/standard.dm
Labels: Balance/Rebalance

#2566 Removes random brain damage sporadic messages
  code/modules/mob/living/carbon/human/life.dm
Labels: Removal

#2565 Mutation and clone damage fix for IPCs
  code/datums/dna.dm
  modular_skyrat/code/_DEFINES/traits.dm
  modular_skyrat/code/datums/dna.dm
  modular_skyrat/code/modules/mob/living/carbon/damage_procs.dm
  modular_skyrat/code/modules/mob/living/carbon/human/species_types/ipc.dm
  modular_skyrat/code/modules/mob/living/carbon/human/species_types/synthliz.dm
  modular_skyrat/code/modules/mob/living/carbon/human/species_types/synths.dm
  tgstation.dme
Labels: Fix

#2571 Updates the vox_head. Missing vox head sprites by gone!
  modular_skyrat/icons/mob/clothing/head_vox.dmi
Labels: Feature

#2577 Removes MouseMove as its very performance draining.
  code/__DEFINES/dcs/signals.dm
  code/_onclick/drag_drop.dm
  code/datums/components/combat_mode.dm
Labels: Removal, Tweak

#2389 Cryptominer Temperature Adjustment
  modular_skyrat/code/game/machinery/cryptominer/cryptominers.dm
Labels: Balance/Rebalance

#2553 [Remove] Remove Collared Trait
  modular_skyrat/code/datums/traits/negative.dm
Labels: Removal

#2607 Fixes amulet of kings going invisible
  code/modules/mining/lavaland/necropolis_chests.dm
  modular_skyrat/icons/obj/clothing/neck.dmi
Labels: Fix

#2603 Fix: Incorrect sink dirs
  _maps/map_files/BoxStation/BoxStation_Skyrat.dmm
  _maps/map_files/Deltastation/DeltaStation2_Skyrat.dmm
  _maps/map_files/MetaStation/MetaStation_Skyrat.dmm
Labels: Fix, Map Edit

#2602 TETRIS TIME
  modular_skyrat/code/modules/research/techweb/nodes/computer_hud_nodes.dm
Labels: Fix

#2523 [Ready] Long-range Analyzer
  code/game/objects/items/devices/scanners.dm
  code/game/objects/items/flamethrower.dm
  code/game/objects/items/storage/belt.dm
  code/game/objects/items/tanks/tanks.dm
  code/game/objects/items/tools/crowbar.dm
  code/game/objects/items/tools/wirecutters.dm
  code/modules/assembly/bomb.dm
  code/modules/atmospherics/machinery/components/components_base.dm
  code/modules/atmospherics/machinery/pipes/pipes.dm
  code/modules/atmospherics/machinery/portable/portable_atmospherics.dm
  code/modules/power/singularity/collector.dm
  code/modules/research/designs/tool_designs.dm
  code/modules/research/techweb/all_nodes.dm
  code/modules/research/techweb/nodes/tools_nodes.dm
  modular_skyrat/icons/obj/device.dmi
Labels: Feature, Fix, Needs Review

#2467 clarke orebox fix
  modular_skyrat/code/game/mecha/working/clarke.dm
Labels: Fix

#2302 Clothing self-equip delay 1.16 - nether update
  code/_onclick/hud/screen_objects.dm
  code/game/objects/items.dm
  code/modules/arousal/genitals.dm
  code/modules/clothing/clothing.dm
  code/modules/clothing/spacesuits/_spacesuits.dm
  code/modules/mob/inventory.dm
  code/modules/mob/living/carbon/human/inventory.dm
Labels: Balance/Rebalance, Fix, Stale

#2277 Impedes people from having extreme harm set to "Yes" while extreme content is set to "No"
  code/modules/client/preferences.dm
  modular_citadel/code/modules/client/preferences_savefile.dm
Labels: Stale

#2273 Lavaland balance stuff
  code/modules/mining/lavaland/necropolis_chests.dm
  modular_skyrat/code/modules/clothing/refactor.dm
  modular_skyrat/code/modules/mining/lavaland/necropolis_chests.dm
  modular_skyrat/code/modules/mob/living/simple_animal/hostile/megafauna/gladiator.dm
  modular_skyrat/code/modules/mob/living/simple_animal/hostile/megafauna/legion.dm
  modular_skyrat/code/modules/mob/living/simple_animal/hostile/megafauna/legionhard.dm
  modular_skyrat/code/modules/mob/living/simple_animal/hostile/megafauna/sif.dm
Labels: Balance/Rebalance, Feature

#2440 Rebalances two Abductor Glands
  code/modules/antagonists/abductor/equipment/glands/transform.dm
  code/modules/antagonists/abductor/equipment/glands/trauma.dm
Labels: Balance/Rebalance, Feature, Removal

#2562 [READY] Adds a combat knife to the motherbase shipment.
  modular_skyrat/code/modules/uplink/uplink_bundles.dm
Labels: Feature, Needs Review

#2550 [Ready] Bluespace Rapid Pipe Dispenser - Now works at range!
  code/game/objects/items/RPD.dm
  code/game/objects/items/storage/belt.dm
  code/game/objects/structures/crates_lockers/closets/secure/engineering.dm
  code/modules/clothing/spacesuits/hardsuit.dm
  code/modules/clothing/suits/miscellaneous.dm
  modular_skyrat/code/game/objects/items/BSRPD.dm
  modular_skyrat/code/game/objects/items/robot/robot_upgrades.dm
  modular_skyrat/code/modules/research/designs/tool_designs.dm
Labels: Feature, Needs Review

#2580 [Modular] Positronic Alert Console
  _maps/map_files/BoxStation/BoxStation_Skyrat.dmm
  _maps/map_files/Deltastation/DeltaStation2_Skyrat.dmm
  _maps/map_files/KiloStation/KiloStation_Skyrat.dmm
  _maps/map_files/MetaStation/MetaStation_Skyrat.dmm
  _maps/map_files/PubbyStation/PubbyStation_Skyrat.dmm
  modular_skyrat/code/game/machinery/posialert.dm
  modular_skyrat/icons/obj/machines/terminals.dmi
  tgstation.dme
Labels: Feature, Map Edit

#2624 Fix: Missing wiring in Delta security
  _maps/map_files/Deltastation/DeltaStation2_Skyrat.dmm
Labels: Feature, Fix, Map Edit

#2636 Fix: Deltastation map correction buggered a tile up + Cloning window toggle ID
  _maps/map_files/Deltastation/DeltaStation2_Skyrat.dmm
Labels: Fix, Map Edit

#2342 Adds high heels
  modular_skyrat/code/modules/clothing/shoes/miscellaneous.dm
  modular_skyrat/code/modules/vending/clothesmate.dm
  modular_skyrat/icons/mob/clothing/feet.dmi
  modular_skyrat/icons/mob/clothing/feet_digi.dmi
  modular_skyrat/icons/obj/clothing/shoes.dmi
  tgstation.dme
Labels: Feature, Sprites, Stale

#2375 Makes Coldstorm's donator item mask thing from citadel better
  modular_skyrat/code/modules/clothing/masks/gasmask.dm
  modular_skyrat/icons/mob/clothing/mask.dmi
  modular_skyrat/icons/obj/clothing/masks.dmi
Labels: Stale

#2477 fixes maint energy crate supply pack
  modular_skyrat/code/modules/cargo/packs/special.dm
  modular_skyrat/code/modules/reagents/chemistry/reagents/drink_reagents.dm
Labels: Fix

#2650 Restricts Cults
  code/modules/uplink/uplink_items/uplink_roles.dm
Labels: Tweak

#2625 [Maps] Remove Public Shuttle, Quantum Instead
  _maps/map_files/BoxStation/BoxStation_Skyrat.dmm
  _maps/map_files/Deltastation/DeltaStation2_Skyrat.dmm
  _maps/map_files/KiloStation/KiloStation_Skyrat.dmm
  _maps/map_files/MetaStation/MetaStation_Skyrat.dmm
  _maps/map_files/Mining/Lavaland_Skyrat.dmm
  _maps/map_files/PubbyStation/PubbyStation_Skyrat.dmm
  code/game/machinery/quantum_pad.dm
Labels: Feature, Map Edit, Removal

#2638 Syndicate Cyborg module (TRAITOR)
  code/modules/mob/living/silicon/robot/robot_modules.dm
  modular_skyrat/code/game/objects/items/borg_shapeshifter.dm
  modular_skyrat/code/game/objects/items/robot/robot_upgrades.dm
  modular_skyrat/code/modules/mob/living/silicon/robot/robot_modules.dm
  modular_skyrat/code/modules/uplink/uplink_roles.dm
  modular_skyrat/icons/mob/moreborgsmodels.dmi
  tgstation.dme
Labels: Feature

#2629 [Modular] [Sprite Edit] Bootyborg Sprite Overhaul + Other Small Cyborg Sprite Changes.
  modular_skyrat/icons/mob/clownborgs.dmi
  modular_skyrat/icons/mob/customrobot.dmi
  modular_skyrat/icons/mob/moreborgsmodels.dmi
Labels: Tweak

#2676 Modular Emoji Addon №2
  modular_skyrat/icons/emoji.dmi
Labels: Grammar and Formatting, Removal, Sprites

#2306 A literal shitposter PR
  code/game/objects/effects/contraband.dm
  code/modules/paperwork/photocopier.dm
  modular_skyrat/code/game/objects/effects/contraband.dm
  modular_skyrat/code/modules/paperwork/photocopier.dm
  modular_skyrat/icons/obj/contraband.dmi
  tgstation.dme
Labels: Feature

#2349 Buffs alcohol healing
  modular_skyrat/code/datums/diseases/advance/symptoms/heal.dm
Labels: Balance/Rebalance

#2667 Lightly buffs telesci
  modular_skyrat/code/modules/telescience/telepad.dm
  modular_skyrat/code/modules/telescience/telesci.dm
  modular_skyrat/code/modules/telescience/telesci_computer.dm
Labels: Balance/Rebalance

#2410 Spider consistency maybe
  modular_skyrat/code/modules/mob/living/simple_animal/terror_spiders/terror_spiders.dm
Labels: Balance/Rebalance

#2371 Fixes more asinine USP code
  modular_skyrat/code/modules/projectiles/boxes_magazines/external/pistol.dm
  modular_skyrat/code/modules/projectiles/guns/ballistic/pistol.dm
  modular_skyrat/code/modules/projectiles/projectile/pistol.dm
Labels: Fix

#2361 [Modular] Wireless Charging
  modular_skyrat/code/game/machinery/wirelesscharger/wirelesscharger.dm
  modular_skyrat/code/game/machinery/wirelesscharger/wirelesscharger.dmi
  modular_skyrat/code/game/objects/items/circuitboards/machine_circuitboards.dm
  modular_skyrat/code/modules/research/designs/machine_designs.dm
  modular_skyrat/code/modules/research/techweb/all_nodes.dm
  modular_skyrat/code/modules/research/techweb/nodes/engineering_nodes.dm
  tgstation.dme
Labels: Feature, Stale

#2568 [Icons] Better Computer Math Icons
  modular_skyrat/icons/obj/computermath.dmi
Labels: Tweak

#2569 Removes the recipe for Strange Reagent
  code/modules/reagents/chemistry/recipes/medicine.dm
Labels: Removal

#2637 Fixes glory kill stacking, fixes gladiator greetings while he's dead.
  modular_skyrat/code/modules/mob/living/simple_animal/hostile/megafauna/gladiator.dm
  modular_skyrat/code/modules/mob/living/simple_animal/hostile/megafauna/megafauna.dm
  modular_skyrat/code/modules/mob/living/simple_animal/hostile/mining_mobs/miningmobs.dm
Labels: Fix

#2657 Removes "my ass is heavy" line from HECU masks
  modular_skyrat/code/modules/clothing/masks/hailer.dm
Labels: Removal

#2671 Let's make transfer votes go off real time, rather than byond time.
  code/controllers/subsystem/autotransfer.dm
Labels: Tweak

#2468 Ports tg singing
  code/__DEFINES/say.dm
  code/game/atoms_movable.dm
  code/modules/goonchat/browserassets/css/browserOutput.css
  code/modules/language/aphasia.dm
  code/modules/language/beachbum.dm
  code/modules/language/common.dm
  code/modules/language/draconic.dm
  code/modules/language/drone.dm
  code/modules/language/language.dm
  code/modules/language/machine.dm
  code/modules/language/monkey.dm
  code/modules/language/mushroom.dm
  code/modules/language/narsian.dm
  code/modules/language/ratvarian.dm
  code/modules/language/slime.dm
  code/modules/language/swarmer.dm
  code/modules/language/sylvan.dm
  code/modules/language/vampiric.dm
  code/modules/language/xenocommon.dm
  code/modules/mob/living/say.dm
  code/modules/mob/say.dm
  modular_skyrat/code/modules/language/buggy.dm
  modular_skyrat/code/modules/language/calcic.dm
  modular_skyrat/code/modules/language/dunmeri.dm
  modular_skyrat/code/modules/language/moffic.dm
  modular_skyrat/code/modules/language/neokanji.dm
  modular_skyrat/code/modules/language/shadowtongue.dm
  modular_skyrat/code/modules/language/solcommon.dm
  modular_skyrat/code/modules/language/sylvan.dm
  modular_skyrat/code/modules/language/technorussian.dm
  modular_skyrat/code/modules/language/terrorspider.dm
  modular_skyrat/code/modules/language/vox.dm
  strings/names/verbs.txt
Labels: Feature

#2653 Removes harm crusher, no penalty PKA and 10mm PKA from uplink
  modular_skyrat/code/modules/uplink/uplink_roles.dm
Labels: Removal

#2666 Fixes heels, unfucks some vending machine items
  modular_skyrat/code/modules/vending/autodrobe.dm
  modular_skyrat/code/modules/vending/clothesmate.dm
  modular_skyrat/code/modules/vending/engivend.dm
  modular_skyrat/code/modules/vending/security.dm
  modular_skyrat/code/modules/vending/wardrobes.dm
  modular_skyrat/icons/mob/clothing/feet.dmi
  modular_skyrat/icons/mob/clothing/feet_digi.dmi
  modular_skyrat/icons/obj/clothing/shoes.dmi
Labels: Fix

#2427 [SemiModular] PDA Vendor
  _maps/map_files/BoxStation/BoxStation_Skyrat.dmm
  _maps/map_files/Deltastation/DeltaStation2_Skyrat.dmm
  _maps/map_files/KiloStation/KiloStation_Skyrat.dmm
  _maps/map_files/MetaStation/MetaStation_Skyrat.dmm
  _maps/map_files/PubbyStation/PubbyStation_Skyrat.dmm
  code/game/objects/items/circuitboards/machine_circuitboards.dm
  modular_skyrat/code/game/machinery/pdavendor.dm
  modular_skyrat/code/modules/cargo/packs.dm
  modular_skyrat/icons/obj/machines/computer.dmi
  tgstation.dme
Labels: Feature, Map Edit

#2644 Adds Rabbit Lop-Eared to ears list
  modular_skyrat/code/modules/mob/dead/new_player/sprite_accessories/ears.dm
  modular_skyrat/icons/mob/mam_ears.dmi
Labels: Feature

#2694 makes the praetor suit lavaproof
  modular_skyrat/code/modules/mining/lavaland/necropolis_chests.dm
Labels: Fix

#2699 Revert "Removes the recipe for Strange Reagent"
  code/modules/reagents/chemistry/recipes/medicine.dm
Labels: Removal, Revert

#2313 [READY] Holding people at gunpoint (Bay-style AIMING)
  code/__DEFINES/dcs/signals.dm
  code/_onclick/hud/radial.dm
  code/_onclick/item_attack.dm
  code/game/objects/items/devices/radio/radio.dm
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/living_mobility.dm
  modular_skyrat/code/modules/mob/living/carbon/carbon.dm
  modular_skyrat/code/modules/mob/living/carbon/gunpoint/gunpoint.dm
  modular_skyrat/code/modules/mob/living/carbon/gunpoint/gunpoint_datum.dm
  modular_skyrat/code/modules/mob/living/carbon/gunpoint/gunpoint_radial.dm
  modular_skyrat/code/modules/mob/living/living.dm
  modular_skyrat/icons/mob/radial_gunpoint.dmi
  modular_skyrat/icons/mob/targeted.dmi
  modular_skyrat/sound/effects/targetoff.ogg
  modular_skyrat/sound/effects/targeton.ogg
  tgstation.dme
Labels: Feature, Needs Review

#2719 Re-synchronises projectiles.dmi and ammo.dmi with upstream
  icons/obj/ammo.dmi
  icons/obj/guns/projectile.dmi
Labels: Fix, Sprites

#2725 Exempt upstream PRs from actions/stale.
  .github/workflows/stale.yml
Labels: GitHub

#2481 Buffs virology because i overshot the nerfs
  modular_skyrat/code/datums/diseases/advance/symptoms/genetics.dm
  modular_skyrat/code/datums/diseases/advance/symptoms/heal.dm
  modular_skyrat/code/datums/diseases/advance/symptoms/sensory.dm
Labels: Balance/Rebalance

#2368 fix shield and zwiehander
  modular_skyrat/code/modules/mining/equipment/kinetic_crusher.dm
  modular_skyrat/code/modules/mining/lavaland/necropolis_chests.dm
Labels: Fix

#2693 [Semi-Modular] The Long Awaited ZOMBIES REWORK!
  code/modules/mob/living/carbon/human/species_types/zombies.dm
  code/modules/surgery/organs/eyes.dm
  code/modules/zombie/items.dm
  modular_skyrat/code/modules/mob/living/carbon/human/species_types/designatedspeciesscreamfile.dm
  modular_skyrat/code/modules/mob/living/carbon/human/species_types/zombies.dm
  modular_skyrat/code/modules/zombie/items.dm
  modular_skyrat/code/modules/zombie/organs.dm
  modular_skyrat/icons/obj/items/nanitetumor.dmi
  modular_skyrat/icons/obj/nanitetumor.dmi
  modular_skyrat/sound/zombie/zombie_scream.ogg
Labels: Balance/Rebalance, Feature

#2755 Fix: I forgot I'm tired
  code/modules/vending/kinkmate.dm
Labels: Fix

#2762 [DNM] [Revert] 2724 Slim blood colour is body colour
  code/game/atoms.dm
  code/game/objects/effects/decals/cleanable/humans.dm
  code/modules/clothing/shoes/_shoes.dm
  code/modules/mob/living/blood.dm
  code/modules/mob/living/carbon/human/human_movement.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/human/species_types/bugmen.dm
  code/modules/mob/living/carbon/human/species_types/flypeople.dm
  code/modules/mob/living/carbon/human/species_types/ipc.dm
  code/modules/mob/living/carbon/human/species_types/jellypeople.dm
  code/modules/mob/living/carbon/human/species_types/lizardpeople.dm
  code/modules/mob/living/carbon/human/species_types/synthliz.dm
  code/modules/mob/living/carbon/update_icons.dm
  code/modules/projectiles/projectile.dm
  code/modules/reagents/chemistry/reagents/other_reagents.dm
Labels: DO NOT MERGE, Removal, Revert
