Repository Skyrat-SS13/Skyrat13, pull requests merged in 2020-05, with the labels that each got.

#1641 Show generic hair on beanies
  code/modules/clothing/head/beanie.dm
Labels: Fix

#1509 [READY] Valeborg Sprite improvements, reworks & fixes
  code/modules/antagonists/nukeop/equipment/borgchameleon.dm
  code/modules/mob/living/silicon/pai/pai.dm
  code/modules/mob/living/silicon/robot/robot_modules.dm
  modular_skyrat/icons/mob/widerobot.dmi
Labels: Fix, Needs Review, Tweak

#1627 Re-enables mobility flags for headset use
  code/game/objects/items/devices/radio/radio.dm
Labels: Balance/Rebalance

#1642 Removes the constant alien noises from xenohybrids
  modular_skyrat/code/modules/mob/living/carbon/human/species_types/furrypeople.dm
  modular_skyrat/code/modules/surgery/organs/tongue.dm
Labels: Removal

#1685 Dynamic added threat in config
  code/controllers/configuration/entries/dynamic.dm
  code/game/gamemodes/dynamic/dynamic.dm
  config/dynamic_config.txt
Labels: Config Update

#1684 False wall checks take time
  code/game/objects/structures/false_walls.dm
  code/game/turfs/simulated/walls.dm
  modular_skyrat/code/game/objects/structures/false_walls.dm
  tgstation.dme
Labels: Tweak

#1683 spiky ponytail works with +generic styles
  icons/mob/hair_extensions.dmi
Labels: Fix, Sprites

#1610 [Map Edit: Lavaland] MultiZ Lavaland
  _maps/map_files/Mining/Lavaland_Skyrat.dmm
  _maps/shuttles/lavaland_mining.dmm
  code/__DEFINES/layers_planes.dm
  code/__DEFINES/maps.dm
  code/controllers/subsystem/mapping.dm
  modular_skyrat/code/game/area/Space_Station_13_areas.dm
  modular_skyrat/code/game/area/lavalandelevator.dm
  modular_skyrat/icons/turf/areas.dmi
  tgstation.dme
Labels: Feature, Map Edit

#1587 [Map Edit: CC] Pacifying Tile
  _maps/map_files/generic/CentCom_Skyrat.dmm
  modular_skyrat/code/game/turfs/open/pacifytile.dm
  modular_skyrat/icons/turf/floors/pacifytile.dmi
  tgstation.dme
Labels: Feature, Map Edit

#1714 Synth bugfixing
  modular_skyrat/code/modules/mob/living/carbon/human/species_types/synths.dm
Labels: Fix

#1677 Revert "[MIRROR] Meta station atmos opening up"
  _maps/map_files/MetaStation/MetaStation_Skyrat.dmm
Labels: Map Edit, Revert

#1727 Makes IPC and synthlizards actually robots
  code/__HELPERS/mobs.dm
  code/_globalvars/lists/flavor_misc.dm
  code/modules/client/preferences.dm
  code/modules/food_and_drinks/drinks/drinks/drinkingglass.dm
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/surgery/bodyparts/bodyparts.dm
  modular_citadel/code/modules/client/preferences_savefile.dm
  modular_skyrat/code/_DEFINES/DNA.dm
  modular_skyrat/code/_HELPERS/mobs.dm
  modular_skyrat/code/game/objects/items/tools/welding_tool.dm
  modular_skyrat/code/modules/food_and_drinks/recipes/drinks_recipes.dm
  modular_skyrat/code/modules/mob/dead/new_player/sprite_accessories/ipc_chassis.dm
  modular_skyrat/code/modules/mob/living/brain/brain_item.dm
  modular_skyrat/code/modules/mob/living/carbon/human/human.dm
  modular_skyrat/code/modules/mob/living/carbon/human/human_defense.dm
  modular_skyrat/code/modules/mob/living/carbon/human/species.dm
  modular_skyrat/code/modules/mob/living/carbon/human/species_types/ipc.dm
  modular_skyrat/code/modules/mob/living/carbon/human/species_types/synthliz.dm
  modular_skyrat/code/modules/power/cable.dm
  modular_skyrat/code/modules/reagents/chemistry/holder.dm
  modular_skyrat/code/modules/reagents/chemistry/reagents.dm
  modular_skyrat/code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
  modular_skyrat/code/modules/reagents/chemistry/reagents/medicine_reagents.dm
  modular_skyrat/code/modules/reagents/chemistry/reagents/other_reagents.dm
  modular_skyrat/code/modules/reagents/chemistry/reagents/pyrotechnic_reagents.dm
  modular_skyrat/code/modules/reagents/chemistry/reagents/toxin_reagents.dm
  modular_skyrat/code/modules/reagents/chemistry/recipes/medicine.dm
  modular_skyrat/code/modules/surgery/bodyparts/bodyparts.dm
  modular_skyrat/code/modules/surgery/bodyparts/dismemberment.dm
  modular_skyrat/code/modules/surgery/mechanic_steps.dm
  modular_skyrat/code/modules/surgery/organs/augments_arm.dm
  modular_skyrat/code/modules/surgery/organs/ears.dm
  modular_skyrat/code/modules/surgery/organs/eyes.dm
  modular_skyrat/code/modules/surgery/organs/lungs.dm
  modular_skyrat/code/modules/surgery/organs/stomach.dm
  modular_skyrat/code/modules/surgery/organs/tongue.dm
  modular_skyrat/code/modules/surgery/robot_brain_surgery.dm
  modular_skyrat/code/modules/surgery/robot_chassis_restoration.dm
  modular_skyrat/code/modules/surgery/robot_healing.dm
  modular_skyrat/code/modules/surgery/robot_restore_looks.dm
  modular_skyrat/icons/mob/ipc/ipc_parts.dmi
  modular_skyrat/icons/obj/drinks.dmi
  modular_skyrat/icons/obj/surgery.dmi
  tgstation.dme
Labels: Feature

#1729 Will it autobuild now? Who knows.
  .github/workflows/autobuild_tgui.yml
Labels: GitHub

#1730 [HOTFIX] unfucked tgui files
  tgui-next/packages/tgui/public/tgui.bundle.js
Labels: FUCK, UI

#1733 The update that finally fixes reskinning
  modular_skyrat/code/game/objects/obj.dm
  modular_skyrat/code/modules/clothing/refactor.dm
  modular_skyrat/icons/mob/clothing/head_muzzled.dmi
  modular_skyrat/icons/mob/clothing/suit_digi.dmi
  modular_skyrat/icons/obj/clothing/suits.dmi
Labels: Fix

#1724 better lyssa plush + katra plush
  modular_skyrat/code/game/objects/items/plushies.dm
  modular_skyrat/icons/obj/plushies.dmi
Labels: Feature, Tweak

#1735 [READY] Fixes some Space Tiles under Resin Walls on OldStation & Indestructible Walls + Tweaks
  modular_skyrat/_maps/RandomRuins/SpaceRuins/oldstation.dmm
Labels: Fix, Needs Review, Tweak

#1629 Allows hiding items and yourself in the trash piles
  modular_skyrat/code/game/objects/structures/trash_pile.dm
Labels: Feature

#1747 [READY] Fixes a lot of Cargo Crate descriptions to remove errors + Tweaks to them and a price change
  code/modules/cargo/packs/costumes_toys.dm
  code/modules/cargo/packs/emergency.dm
  code/modules/cargo/packs/engine.dm
  code/modules/cargo/packs/engineering.dm
  code/modules/cargo/packs/livestock.dm
  code/modules/cargo/packs/materials.dm
  code/modules/cargo/packs/medical.dm
  code/modules/cargo/packs/misc.dm
  code/modules/cargo/packs/organic.dm
  code/modules/cargo/packs/science.dm
  code/modules/cargo/packs/security.dm
  code/modules/cargo/packs/service.dm
  code/modules/cargo/packs/vending.dm
  modular_skyrat/code/modules/cargo/packs/bloat.dm
  modular_skyrat/code/modules/cargo/packs/special.dm
Labels: Balance/Rebalance, Fix, Needs Review, Tweak

#1740 Fixes legion cores and fits them to citadel standards
  modular_skyrat/code/modules/mining/equipment/regenerative_core.dm
Labels: Fix

#1749 [MODULAR] Fed uniform is now Orvi-like by default, also rewrites them (a bit too much, perhaps)
  modular_skyrat/code/modules/client/loadout/uniform.dm
  modular_skyrat/code/modules/clothing/refactor.dm
  modular_skyrat/icons/mob/clothing/uniform.dmi
  modular_skyrat/icons/mob/clothing/uniform_digi.dmi
  modular_skyrat/icons/obj/clothing/uniform.dmi
Labels: Feature, Tweak

#1728 [Modular] Computer Math
  modular_skyrat/code/game/objects/items/computermath.dm
  modular_skyrat/code/modules/research/designs/tool_designs.dm
  modular_skyrat/code/modules/research/techweb/all_nodes.dm
  modular_skyrat/icons/obj/computermath.dmi
  tgstation.dme
Labels: Feature

#1709 Adds pAI device into loadout
  modular_skyrat/code/modules/client/loadout/hands.dm
Labels: Feature

#1606 Makes brig physicians unable to become bloodsuckers.
  code/game/gamemodes/bloodsucker/bloodsucker.dm
  code/game/gamemodes/dynamic/dynamic_rulesets_latejoin.dm
  code/game/gamemodes/dynamic/dynamic_rulesets_roundstart.dm
Labels: Tweak

#1752 More Posters.
  code/game/objects/effects/contraband.dm
  modular_skyrat/icons/obj/contraband.dmi
Labels: Feature

#1705 Power gloves: New old traitor item. Stealth suit fixes too.
  code/game/machinery/recharger.dm
  modular_skyrat/code/datums/status_effects/buffs.dm
  modular_skyrat/code/modules/clothing/gloves/gloves.dm
  modular_skyrat/code/modules/clothing/under/stealth.dm
  modular_skyrat/code/modules/uplink/uplink_roles.dm
  modular_skyrat/icons/mob/clothing/hands.dmi
  modular_skyrat/icons/obj/clothing/gloves.dmi
Labels: Feature

#1611 [MODULAR] Adds violence/security risk color-coded grade prisoner jumpsuits, with strong implication...
  modular_skyrat/code/modules/clothing/refactor.dm
  modular_skyrat/icons/mob/clothing/uniform.dmi
  modular_skyrat/icons/mob/clothing/uniform_digi.dmi
  modular_skyrat/icons/obj/clothing/uniform.dmi
Labels: Sprites

#1707 Nerfs the virology symptoms i added
  modular_skyrat/code/datums/diseases/advance/symptoms/heal.dm
  modular_skyrat/code/datums/diseases/advance/symptoms/sensory.dm
  modular_skyrat/code/datums/diseases/advance/symptoms/viral.dm
Labels: Balance/Rebalance

#1775 Coins don't have material effects
  code/modules/mining/ores_coins.dm
Labels: Tweak

#1737 Show playtime on notes
  SQL/database_changelog.txt
  SQL/tgstation_schema.sql
  code/modules/admin/sql_message_system.dm
Labels: Administration, SQL

#1531 Kinetic Destroyer
  code/modules/mining/equipment/kinetic_crusher.dm
  code/modules/mining/machine_vending.dm
  icons/mob/inhands/weapons/hammerspc_lefthand.dmi
  icons/mob/inhands/weapons/hammerspc_righthand.dmi
  icons/obj/mining.dmi
  modular_skyrat/code/modules/mining/machine_vending.dm
Labels: Feature, Sprites

#1771 You know the legion core nerf Citadel did? Yeah i fucking hate it.
  modular_skyrat/code/modules/mining/equipment/regenerative_core.dm
Labels: Balance/Rebalance

#1784 Fixes stealth suit runtimes
  modular_skyrat/code/datums/status_effects/buffs.dm
Labels: Fix

#1777 Comments out power sink objective and uplink item
  code/game/gamemodes/objective_sabotage.dm
  code/modules/uplink/uplink_items/uplink_devices.dm
Labels: Removal

#1778 Applies #1720 improvements to Cybernetic Naga
  modular_skyrat/icons/mob/mam_taur.dmi
Labels: Tweak

#1786 Fixes space ninja icons
  modular_skyrat/code/modules/ninja/suit/head.dm
  modular_skyrat/icons/mob/clothing/suit.dmi
Labels: Fix

#1802 Possibly fixes the legion cores giving slowdown issue by commenting out the citadel procs
  code/modules/mining/equipment/regenerative_core.dm
  modular_skyrat/code/modules/mining/equipment/regenerative_core.dm
  tgstation.dme
Labels: Fix

#1688 Clockwork/Bronze Multitool and Switchblade and Experimental Welder
  icons/obj/clothing/belt_overlays.dmi
  modular_skyrat/code/datums/components/crafting/recipes/recipes_misc.dm
  modular_skyrat/code/game/objects/items/devices/multitool.dm
  modular_skyrat/code/game/objects/items/tools/weldingtool.dm
  modular_skyrat/code/game/objects/items/weaponry.dm
  modular_skyrat/icons/mob/inhands/equipment/tools_lefthand.dmi
  modular_skyrat/icons/mob/inhands/equipment/tools_righthand.dmi
  modular_skyrat/icons/mob/inhands/weapons/swords_lefthand.dmi
  modular_skyrat/icons/mob/inhands/weapons/swords_righthand.dmi
  modular_skyrat/icons/obj/brass.dmi
  modular_skyrat/icons/obj/items_and_weapons.dmi
  tgstation.dme
Labels: Feature, Sprites

#1817 False wall timer fix
  modular_skyrat/code/game/objects/structures/false_walls.dm
Labels: Fix

#1819 Fixes and modularizes tiger carp stuff
  code/game/gamemodes/dynamic/dynamic_rulesets_events.dm
  code/modules/mob/living/simple_animal/hostile/carp.dm
  modular_skyrat/code/game/gamemodes/dynamic/dynamic_rulesets_events.dm
  modular_skyrat/code/modules/events/tiger_carp_frenzy.dm
  modular_skyrat/code/modules/mob/living/simple_animal/hostile/carp.dm
  modular_skyrat/icons/mob/animal.dmi
  tgstation.dme
Labels: Fastmerge Request, Fix

#1818 Removes the dumb gin joke, due to performance and economical issues.
  modular_skyrat/code/modules/research/designs/autobottler_designs.dm
  tgstation.dme
Labels: Balance/Rebalance, Fastmerge Request, Removal

#1824 Fixes the bug in which you swallow revolvers when using a conversion kit
  modular_skyrat/code/game/objects/items/kits.dm
Labels: Fix

#1862 Comments out atrocious chatspam and wire pulse/cut delays
  code/datums/wires/_wires.dm
Labels: Removal

#1713 Metastation Maint Overhaul
  _maps/map_files/MetaStation/MetaStation_Skyrat.dmm
Labels: Feature, Map Edit

#1832 Metastation Feature Requests & Bugfixing
  _maps/map_files/MetaStation/MetaStation_Skyrat.dmm
  code/game/objects/effects/spawners/misc_lootdrop.dm
Labels: Balance/Rebalance, Code Improvement, Feature, Fix, Map Edit, Tweak

#1871 Adds Lightweight trait
  code/__DEFINES/traits.dm
  code/_globalvars/traits.dm
  code/datums/traits/neutral.dm
  code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
Labels: Feature

#1867 [map edits] meta, box, syndie, and delta fixes
  _maps/map_files/BoxStation/BoxStation_Skyrat.dmm
  _maps/map_files/Deltastation/DeltaStation2_Skyrat.dmm
  _maps/map_files/MetaStation/MetaStation_Skyrat.dmm
  modular_skyrat/_maps/RandomRuins/LavaRuins/lavaland_surface_syndicate_base1.dmm
Labels: Fix, Map Edit

#1895 [READY] Adds kinkmate to Delta Dorms
  _maps/map_files/Deltastation/DeltaStation2_Skyrat.dmm
Labels: Feature, Map Edit, Needs Review, Removal

#1891 [map edit] fire alarm in chemistry, lavaland syndie base fix
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/BoxStation/BoxStation_Skyrat.dmm
  modular_skyrat/_maps/RandomRuins/LavaRuins/lavaland_surface_syndicate_base1.dmm
Labels: Feature, Map Edit

#1913 [Plushie] Kato
  modular_skyrat/code/game/objects/items/plushies.dm
  modular_skyrat/icons/obj/plushies.dmi
Labels: Feature

#1912 Computermath 2.0, now with more algebra!
  modular_skyrat/code/game/objects/items/computermath.dm
Labels: Tweak

#1910 [Modular] Fixes missing HoS cloak reskin, adds descs to some of reskins
  modular_skyrat/code/modules/clothing/refactor.dm
  modular_skyrat/icons/obj/clothing/suits.dmi
Labels: Feature, Fix

#1902 [Fix] Looping Circuitboards Vending
  code/game/objects/items/circuitboards/machine_circuitboards.dm
  modular_skyrat/code/game/objects/items/circuitboards/machine_circuitboards.dm
Labels: Fix

#1903 [Fix] No Teleporting in Bluespace Locker
  modular_skyrat/code/game/area/Space_Station_13_areas.dm
Labels: Fix

#1355 Blob Buff/Nerf
  code/game/area/Space_Station_13_areas.dm
  code/modules/antagonists/blob/blob/blobs/core.dm
  code/modules/antagonists/blob/blob/blobs/factory.dm
  code/modules/antagonists/blob/blob/blobs/node.dm
  code/modules/antagonists/blob/blob/blobs/resource.dm
  code/modules/antagonists/blob/blob/blobs/shield.dm
  code/modules/antagonists/blob/blob/overmind.dm
  code/modules/antagonists/blob/blob/theblob.dm
Labels: Balance/Rebalance, Currently Testmerged

#1696 [Modular] Xenoarchaeology
  _maps/RandomRuins/StationRuins/Lavaland/Mining_Station/Mining_Station_Public_01_Skyrat.dmm
  _maps/map_files/BoxStation/BoxStation_Skyrat.dmm
  _maps/map_files/Deltastation/DeltaStation2_Skyrat.dmm
  _maps/map_files/KiloStation/KiloStation_Skyrat.dmm
  _maps/map_files/MetaStation/MetaStation_Skyrat.dmm
  _maps/map_files/Mining/Lavaland_Skyrat.dmm
  _maps/map_files/PubbyStation/PubbyStation_Skyrat.dmm
  code/__DEFINES/maps.dm
  code/controllers/subsystem/mapping.dm
  code/modules/hydroponics/plant_genes.dm
  code/modules/hydroponics/seeds.dm
  code/modules/jobs/job_types/scientist.dm
  code/modules/mining/equipment/mineral_scanner.dm
  code/modules/research/techweb/all_nodes.dm
  code/modules/research/techweb/nodes/alien_nodes.dm
  config/jobs.txt
  modular_skyrat/code/_HELPERS/reagents.dm
  modular_skyrat/code/game/area/Space_Station_13_areas.dm
  modular_skyrat/code/game/objects/effects/effect_system/effect_smoke.dm
  modular_skyrat/code/game/objects/structures/flora.dm
  modular_skyrat/code/game/turfs/open/floor/plating/lavaland_jungle.dm
  modular_skyrat/code/modules/hydroponics/botany_flora.dm
  modular_skyrat/code/modules/hydroponics/grown.dm
  modular_skyrat/code/modules/hydroponics/plant_genes.dm
  modular_skyrat/code/modules/hydroponics/seeds.dm
  modular_skyrat/code/modules/mapping/lavaland_jungle_gen.dm
  modular_skyrat/code/modules/research/designs/tool_designs.dm
  modular_skyrat/code/modules/research/xenoarch/artifact.dm
  modular_skyrat/code/modules/research/xenoarch/artifact_list.dm
  modular_skyrat/code/modules/research/xenoarch/fossil_and_artifact.dmi
  modular_skyrat/code/modules/research/xenoarch/strange_rock.dm
  modular_skyrat/code/modules/research/xenoarch/tools.dm
  modular_skyrat/code/modules/research/xenoarch/tools.dmi
  modular_skyrat/code/modules/research/xenoarch/xenobotany/grown/amauri.dm
  modular_skyrat/code/modules/research/xenoarch/xenobotany/grown/gelthi.dm
  modular_skyrat/code/modules/research/xenoarch/xenobotany/grown/jurlmah.dm
  modular_skyrat/code/modules/research/xenoarch/xenobotany/grown/nofruit.dm
  modular_skyrat/code/modules/research/xenoarch/xenobotany/grown/shand.dm
  modular_skyrat/code/modules/research/xenoarch/xenobotany/grown/surik.dm
  modular_skyrat/code/modules/research/xenoarch/xenobotany/grown/telriis.dm
  modular_skyrat/code/modules/research/xenoarch/xenobotany/grown/thaadra.dm
  modular_skyrat/code/modules/research/xenoarch/xenobotany/grown/vale.dm
  modular_skyrat/code/modules/research/xenoarch/xenobotany/grown/vaporsac.dm
  modular_skyrat/code/modules/research/xenoarch/xenobotany/icons/growing.dmi
  modular_skyrat/code/modules/research/xenoarch/xenobotany/icons/harvests.dmi
  modular_skyrat/code/modules/research/xenoarch/xenobotany/icons/seeds.dmi
  modular_skyrat/icons/effects/96x96.dmi
  modular_skyrat/icons/effects/ore_visuals.dmi
  modular_skyrat/icons/obj/flora/jungleflora.dmi
  modular_skyrat/icons/turf/areas.dmi
  modular_skyrat/icons/turf/floors/water.dmi
  modular_skyrat/icons/turf/smooth/_smooth.dmi
  modular_skyrat/icons/turf/smooth/dirt.dmi
  modular_skyrat/icons/turf/smooth/grass.dmi
  modular_skyrat/icons/turf/water.dmi
  tgstation.dme
Labels: Config Update, Currently Testmerged, Feature, Map Edit

#1337 Lets antag banned people be converted into some antags
  code/modules/antagonists/_common/antag_datum.dm
  modular_skyrat/code/modules/antagonists/bloodsucker/datum_vassal.dm
  modular_skyrat/code/modules/antagonists/devil/sintouched/sintouched.dm
  modular_skyrat/code/modules/antagonists/survivalist/survivalist.dm
  tgstation.dme
Labels: Tweak

#1597 I was promised $20 for this PR: Removes Contamination from Uranium
  code/datums/materials/basemats.dm
Labels: Removal

#1712 BLOB buFf
  code/__DEFINES/antagonists.dm
  code/modules/antagonists/blob/blob/overmind.dm
Labels: Balance/Rebalance

#1901 fixes unintended //skyrat change being shown in sec records console
  code/game/machinery/computer/security.dm
Labels: Fix

#1799 buffs the unused penlight feature
  code/game/objects/items/devices/flashlight.dm
Labels: Feature

#1836 Upgrades the synthetic quirk to the standards set by Azarak's rework
  modular_skyrat/code/modules/mob/living/carbon/human/species_types/synths.dm
  modular_skyrat/code/modules/reagents/chemistry/reagents/medicine_reagents.dm
  modular_skyrat/icons/mob/synth_parts.dmi
Labels: Tweak

#1849 Just lowers the cost of miner salve patches on the mining vendor
  modular_skyrat/code/modules/mining/machine_vending.dm
  modular_skyrat/code/modules/reagents/reagent_containers/borghydro.dm
  modular_skyrat/code/modules/reagents/reagent_containers/patch.dm
  modular_skyrat/code/modules/reagents/reagent_containers/pill.dm
  modular_skyrat/code/modules/reagents/reagents_containers/patch.dm
  modular_skyrat/code/modules/reagents/reagents_containers/reagent_containers/bottle.dm
  tgstation.dme
Labels: Balance/Rebalance

#1875 Objectively improves Runtime
  modular_skyrat/code/modules/mob/living/simple_animal/friendly/cat.dm
  tgstation.dme
Labels: Tweak

#1887 Alternative titles for jobs
  code/__HELPERS/game.dm
  code/controllers/subsystem/job.dm
  code/datums/datacore.dm
  code/modules/client/preferences.dm
  code/modules/jobs/job_types/_job.dm
  code/modules/mob/dead/new_player/new_player.dm
  modular_citadel/code/modules/client/preferences_savefile.dm
  modular_skyrat/code/modules/jobs/job_types/_job.dm
  modular_skyrat/code/modules/jobs/job_types/_job_alt_titles.dm
  tgstation.dme
Labels: Feature

#1888 Nerfs growth serum
  code/modules/reagents/chemistry/reagents/other_reagents.dm
  modular_skyrat/code/modules/reagents/chemistry/reagents/other_reagents.dm
Labels: Tweak

#1896 Makes robotic limbs spark when getting damage
  modular_skyrat/code/modules/surgery/bodyparts/bodyparts.dm
Labels: Feature

#1899 Surgery robo fixses
  code/modules/surgery/brain_surgery.dm
  code/modules/surgery/coronary_bypass.dm
  code/modules/surgery/dental_implant.dm
  code/modules/surgery/embalming.dm
  code/modules/surgery/emergency_cardioversion_recovery.dm
  code/modules/surgery/eye_surgery.dm
  code/modules/surgery/graft_synthtissue.dm
  code/modules/surgery/healing.dm
  code/modules/surgery/lipoplasty.dm
  code/modules/surgery/lobectomy.dm
  code/modules/surgery/organ_manipulation.dm
  code/modules/surgery/plastic_surgery.dm
  modular_skyrat/code/modules/surgery/robot_healing.dm
  modular_skyrat/code/modules/surgery/robot_restore_looks.dm
Labels: Fix, Tweak

#1866 Shovels
  modular_skyrat/code/modules/mining/equipment/mining_tools.dm
  modular_skyrat/code/modules/research/designs/mining_designs.dm
  modular_skyrat/code/modules/research/techweb/all_nodes.dm
  modular_skyrat/code/modules/research/techweb/nodes/tools_nodes.dm
  modular_skyrat/icons/obj/shovel.dmi
  tgstation.dme
Labels: Feature

#1922 [READY] Modifies the IC Issue response players see. (REQUESTED BY XYEL)
  code/modules/admin/verbs/adminhelp.dm
Labels: Needs Review, Tweak

#1927 synced neck.dmi with cit
  icons/mob/clothing/neck.dmi
Labels: Sprites

#1938 computermath fix and balance
  modular_skyrat/code/game/objects/items/computermath.dm
Labels: Fix

#1782 [Modular] Adds defines to the loadout system, tweaks restrictions and adds clear gasmask into the list
  modular_skyrat/code/modules/client/loadout/_defines.dm
  modular_skyrat/code/modules/client/loadout/_medical.dm
  modular_skyrat/code/modules/client/loadout/backpack.dm
  modular_skyrat/code/modules/client/loadout/head.dm
  modular_skyrat/code/modules/client/loadout/mask.dm
  modular_skyrat/code/modules/client/loadout/suit.dm
  modular_skyrat/code/modules/client/loadout/uniform.dm
  modular_skyrat/code/modules/client/loadout/~defines.dm
  tgstation.dme
Labels: Feature, Tweak

#1944 Modular Emoji Addon №1
  modular_skyrat/icons/emoji.dmi
Labels: Sprites

#1971 Combat mode and Surrender emote now flash an image above you.
  code/datums/emotes.dm
  code/modules/mob/living/emote.dm
  code/modules/mob/living/living_combat.dm
  modular_skyrat/code/modules/mob/emote.dm
  modular_skyrat/code/modules/mob/living/combat_indicator.dm
  modular_skyrat/code/modules/mob/living/emote.dm
  modular_skyrat/icons/mob/combat_indicator.dmi
  modular_skyrat/icons/mob/popup_flicks.dmi
  tgstation.dme
Labels: Feature

#1975 Surrender Verb
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/living.dm
Labels: Feature

#1961 [computermath] Balancing, bugfix and extra questiontype
  modular_skyrat/code/game/objects/items/computermath.dm
Labels: Tweak

#1892 Adds Caps to Dynamic Events
  code/game/gamemodes/dynamic/dynamic_rulesets_events.dm
Labels: Balance/Rebalance

#1535 [Ready] Part 1/X: Better arcades
  _maps/map_files/BoxStation/BoxStation_Skyrat.dmm
  _maps/map_files/Deltastation/DeltaStation2_Skyrat.dmm
  _maps/map_files/MetaStation/MetaStation_Skyrat.dmm
  code/game/machinery/computer/arcade.dm
  code/game/machinery/computer/arcade/battle.dm
  code/game/machinery/computer/arcade/minesweeper.dm
  code/game/machinery/computer/arcade/misc_arcade.dm
  code/game/machinery/computer/arcade/orion_trail.dm
  code/game/objects/items/circuitboards/machine_circuitboards.dm
  code/game/objects/items/toys.dm
  code/modules/research/designs/machine_desings/machine_designs_all_misc.dm
  modular_skyrat/code/game/machinery/computer/arcade/arcade.dm
  modular_skyrat/code/game/machinery/computer/arcade/arcade_counter.dm
  modular_skyrat/code/game/machinery/computer/arcade/arcade_prize.dm
  modular_skyrat/code/game/machinery/computer/arcade/prize_datums.dm
  modular_skyrat/icons/obj/arcade.dmi
  tgstation.dme
Labels: Currently Testmerged, Feature, Map Edit, Needs Review, Tweak

#2000 Dynamic roundstart scaling rule config
  code/controllers/configuration/entries/dynamic.dm
  config/dynamic_config.txt
  modular_skyrat/code/game/gamemodes/dynamic/dynamic_rulesets_roundstart.dm
Labels: Config Update

#1999 Better IC spawning loadout, and minor tweaks for spawning others
  modular_citadel/code/modules/clothing/outfits/standard.dm
  modular_skyrat/code/modules/mob/dead/observer/observer.dm
Labels: Administration

#1976 [Ready] Player ticket manager
  code/__DEFINES/admin.dm
  code/__HELPERS/_logging.dm
  code/modules/admin/chat_commands.dm
  code/modules/admin/topic.dm
  code/modules/admin/verbs/adminhelp.dm
  code/modules/admin/verbs/adminpm.dm
  code/modules/client/client_procs.dm
  modular_skyrat/code/modules/admin/verbs/adminhelp.dm
  tgstation.dme
Labels: Feature, Needs Review

#2002 [Map Edits] De-decalification, Prize machine, Lootpiles
  _maps/map_files/Deltastation/DeltaStation2_Skyrat.dmm
  _maps/map_files/KiloStation/KiloStation_Skyrat.dmm
  _maps/map_files/MetaStation/MetaStation_Skyrat.dmm
  _maps/map_files/PubbyStation/PubbyStation_Skyrat.dmm
Labels: Feature, Map Edit, Removal

#1995 [Map Fix: Box] Evidence Storage and Cargo Access
  _maps/map_files/BoxStation/BoxStation_Skyrat.dmm
Labels: Fix, Map Edit

#1962 Adds some new alt titles
  modular_skyrat/code/modules/jobs/job_types/_job_alt_titles.dm
Labels: Feature

#1605 Reworks Bag of Holding explosions.
  _maps/map_files/generic/CentCom_Skyrat.dmm
  code/datums/components/storage/concrete/bag_of_holding.dm
  code/modules/mob/living/carbon/monkey/monkey.dm
Labels: Balance/Rebalance, Map Edit

#2032 Reduces tiger carp events
  modular_skyrat/code/game/gamemodes/dynamic/dynamic_rulesets_events.dm
Labels: Tweak

#1921 Craftin Glassin
  code/datums/components/crafting/recipes/recipes_misc.dm
Labels: Feature

#1662 [Modular] New chem recipes and /tg/ misc chems
  modular_skyrat/code/game/objects/items/stacks/sheets/sheet_types.dm
  modular_skyrat/code/modules/food_and_drinks/food/snacks/meat.dm
  modular_skyrat/code/modules/food_and_drinks/recipes/drink_recipes.dm
  modular_skyrat/code/modules/reagents/chemistry/reagents/food_reagents.dm
  modular_skyrat/code/modules/reagents/chemistry/reagents/other_reagents.dm
  modular_skyrat/code/modules/reagents/chemistry/recipes/others.dm
Labels: Feature, Fix

#1702 Medibots don't like apples.
  modular_skyrat/code/modules/mob/living/simple_animal/bot/bot.dm
  modular_skyrat/code/modules/mob/living/simple_animal/bot/medbot.dm
  tgstation.dme
Labels: Tweak

#1835 [Not Modular] Fluff Addition: Factions/Employers. Also rewords contract and yet again renames fed uniforms
  code/_globalvars/lists/flavor_misc.dm
  code/datums/datacore.dm
  code/game/machinery/computer/security.dm
  code/modules/client/preferences.dm
  code/modules/paperwork/contract.dm
  modular_citadel/code/modules/client/preferences_savefile.dm
  modular_skyrat/code/modules/clothing/refactor.dm
  modular_skyrat/code/modules/mob/living/carbon/human/human.dm
  modular_skyrat/code/modules/paperwork/contract.dm
  tgstation.dme
Labels: Feature, Tweak

#1972 Makeshift halberd
  modular_skyrat/code/datums/components/crafting/recipes/recipes_weapon_and_ammo.dm
  modular_skyrat/code/game/objects/items/weaponry.dm
  modular_skyrat/icons/mob/inhands/weapons/axes_lefthand.dmi
  modular_skyrat/icons/mob/inhands/weapons/axes_righthand.dmi
  modular_skyrat/icons/obj/items_and_weapons.dmi
Labels: Feature

#1970 Added modular bland worn/baggy shirt, its reskins and polychromic variant
  modular_skyrat/code/modules/client/loadout/suit.dm
  modular_skyrat/code/modules/clothing/suits/miscellaneous.dm
  modular_skyrat/icons/mob/clothing/suit.dmi
  modular_skyrat/icons/obj/clothing/suits.dmi
Labels: Feature

#2036 Surrender Fix
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/emote.dm
Labels: Tweak

#2053 Psicodine
  code/_globalvars/traits.dm
  code/datums/traits/negative.dm
Labels: Tweak

#2051 Minor dynamic blob changes
  modular_skyrat/code/game/gamemodes/dynamic/dynamic_rulesets_midround.dm
Labels: Tweak

#2025 Adds *tilt
  code/modules/mob/living/emote.dm
  modular_skyrat/code/modules/mob/living/emote.dm
Labels: Feature

#1920 Rewords Vampire Conversion
  code/modules/antagonists/bloodsucker/objects/bloodsucker_crypt.dm
Labels: Tweak

#2050 [Fix] Weird Airlock on Map, Shovel issues
  _maps/shuttles/whiteship_meta.dmm
  modular_skyrat/code/modules/mining/equipment/mining_tools.dm
Labels: Fix, Map Edit

#1996 [Fix(?)] Message Server can be researched, built, etc.
  code/game/machinery/telecomms/machines/message_server.dm
  modular_skyrat/code/game/objects/items/circuitboards/machine_circuitboards.dm
  modular_skyrat/code/modules/research/designs/telecomms_designs.dm
  modular_skyrat/code/modules/research/techweb/nodes/computer_hud_nodes.dm
  tgstation.dme
Labels: Feature

#2056 [Not-Modular] Revert(?) Volumetric Storage
  code/game/objects/items/storage/backpack.dm
Labels: Code Improvement, Revert

#2057 Sprite Improvement: Shark Light made into a cute little snubby snout
  modular_skyrat/icons/mob/mam_snouts.dmi
Labels: Tweak

#2061 Dynamic Overthrow roundstart
  modular_skyrat/code/game/gamemodes/dynamic/dynamic_rulesets_latejoin.dm
  modular_skyrat/code/game/gamemodes/dynamic/dynamic_rulesets_roundstart.dm
Labels: Feature

#2035 Fixes gamemode failure, I think
  code/modules/client/preferences_savefile.dm
Labels: Fix

#1969 Minor fixes
  code/modules/projectiles/guns/energy/kinetic_accelerator.dm
  modular_skyrat/code/datums/components/crafting/crafting_results/blunderbuss.dm
  modular_skyrat/code/datums/components/crafting/crafting_results/cannon.dm
  modular_skyrat/code/datums/components/crafting/crafting_results/swords.dm
  modular_skyrat/code/datums/components/crafting/recipes/recipes_weapon_and_ammo.dm
  modular_skyrat/code/game/objects/items/misc.dm
  modular_skyrat/code/modules/clothing/suits/armor.dm
  modular_skyrat/code/modules/projectiles/guns/ballistic/shotgun.dm
  modular_skyrat/code/modules/projectiles/guns/energy/kinetic_accelerator.dm
  modular_skyrat/code/modules/research/designs/weapon_designs.dm
  modular_skyrat/icons/mob/clothing/shitarmor.dmi
  modular_skyrat/icons/mob/clothing/shitarmor_digi.dmi
  modular_skyrat/icons/mob/clothing/suit.dmi
  modular_skyrat/icons/mob/clothing/suit_digi.dmi
  modular_skyrat/icons/obj/clothing/shitarmor.dmi
  modular_skyrat/icons/obj/clothing/suits.dmi
  modular_skyrat/icons/obj/projectiles.dmi
Labels: Fix, Sprites

#2067 [MIRROR FIX] "Removes the absolute istype fest from footsteps"
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/simple_animal/hostile/giant_spider.dm
  code/modules/mob/living/simple_animal/hostile/retaliate/spaceman.dm
  modular_skyrat/code/modules/mob/living/simple_animal/hostile/megafauna/bubblegum.dm
  modular_skyrat/code/modules/mob/living/simple_animal/hostile/megafauna/glaurung.dm
  modular_skyrat/code/modules/mob/living/simple_animal/hostile/mining_mobs/shamblingminer.dm
Labels: Removal

#2059 [Modular] Renames OrviTrek uniforms YET YET AGAIN to be EntCorp's
  modular_skyrat/code/modules/client/loadout/head.dm
  modular_skyrat/code/modules/client/loadout/suit.dm
  modular_skyrat/code/modules/client/loadout/uniform.dm
  modular_skyrat/code/modules/clothing/refactor.dm
Labels: Tweak

#1942 Fixes nanite slurry
  modular_skyrat/code/modules/reagents/chemistry/reagents/medicine_reagents.dm
Labels: Fix

#1948 [Code Bounty] [Ready] Terror Spiders ported
  code/__DEFINES/DNA.dm
  code/__DEFINES/is_helpers.dm
  code/__DEFINES/role_preferences.dm
  code/__DEFINES/say.dm
  code/modules/goonchat/browserassets/css/browserOutput.css
  code/modules/goonchat/browserassets/css/browserOutput_dark.css
  code/modules/mob/living/say.dm
  modular_skyrat/code/datums/saymode.dm
  modular_skyrat/code/game/gamemodes/dynamic/dynamic_rulesets_midround.dm
  modular_skyrat/code/modules/antagonists/terror_spiders/terror_spiders.dm
  modular_skyrat/code/modules/events/terror_spider_infestation.dm
  modular_skyrat/code/modules/language/terrorspider.dm
  modular_skyrat/code/modules/mob/living/simple_animal/terror_spiders/__defines.dm
  modular_skyrat/code/modules/mob/living/simple_animal/terror_spiders/actions.dm
  modular_skyrat/code/modules/mob/living/simple_animal/terror_spiders/chem.dm
  modular_skyrat/code/modules/mob/living/simple_animal/terror_spiders/ghost.dm
  modular_skyrat/code/modules/mob/living/simple_animal/terror_spiders/hive.dm
  modular_skyrat/code/modules/mob/living/simple_animal/terror_spiders/reproduction.dm
  modular_skyrat/code/modules/mob/living/simple_animal/terror_spiders/spider_types/black.dm
  modular_skyrat/code/modules/mob/living/simple_animal/terror_spiders/spider_types/brown.dm
  modular_skyrat/code/modules/mob/living/simple_animal/terror_spiders/spider_types/empress.dm
  modular_skyrat/code/modules/mob/living/simple_animal/terror_spiders/spider_types/gray.dm
  modular_skyrat/code/modules/mob/living/simple_animal/terror_spiders/spider_types/green.dm
  modular_skyrat/code/modules/mob/living/simple_animal/terror_spiders/spider_types/mother.dm
  modular_skyrat/code/modules/mob/living/simple_animal/terror_spiders/spider_types/prince.dm
  modular_skyrat/code/modules/mob/living/simple_animal/terror_spiders/spider_types/princess.dm
  modular_skyrat/code/modules/mob/living/simple_animal/terror_spiders/spider_types/purple.dm
  modular_skyrat/code/modules/mob/living/simple_animal/terror_spiders/spider_types/queen.dm
  modular_skyrat/code/modules/mob/living/simple_animal/terror_spiders/spider_types/red.dm
  modular_skyrat/code/modules/mob/living/simple_animal/terror_spiders/spider_types/white.dm
  modular_skyrat/code/modules/mob/living/simple_animal/terror_spiders/terror_ai.dm
  modular_skyrat/code/modules/mob/living/simple_animal/terror_spiders/terror_spiders.dm
  modular_skyrat/code/modules/mob/say.dm
  modular_skyrat/code/modules/surgery/organs/parasites.dm
  modular_skyrat/icons/mob/actions/actions_terrorspiders.dmi
  modular_skyrat/icons/mob/terrorspider.dmi
  modular_skyrat/icons/mob/terrorspider64.dmi
  tgstation.dme
Labels: Config Update, Feature, Needs Review, Sprites

#2024 ERP menu rework thing: The Coom Menu (TM)
  code/__HELPERS/_cit_helpers.dm
  code/modules/client/preferences.dm
  modular_citadel/code/modules/client/preferences_savefile.dm
  modular_skyrat/code/interactions/_interaction.dm
  modular_skyrat/code/interactions/interaction_interface.dm
  modular_skyrat/code/interactions/interaction_mob.dm
  modular_skyrat/code/interactions/lewd/_lewd.dm
  modular_skyrat/code/interactions/lewd/lewd_datums.dm
  modular_skyrat/code/interactions/lewd/lewd_interactions.dm
  modular_skyrat/code/interactions/lewd/objects.dm
  modular_skyrat/code/modules/mob/living/carbon/human/human.dm
Labels: Refactor, Removal

#2043 [READY] Port of tetris as an arcade.
  code/game/machinery/computer/arcade.dm
  modular_skyrat/code/game/machinery/computer/arcade/tetris.dm
  modular_skyrat/code/game/objects/items/circuitboards/computer_circuitboards.dm
  modular_skyrat/code/modules/client/asset_cache.dm
  modular_skyrat/code/modules/research/designs/machine_desings/machine_designs_all_misc.dm
  modular_skyrat/code/modules/research/techweb/all_nodes.dm
  modular_skyrat/icons/tetris/tetris_0.gif
  modular_skyrat/icons/tetris/tetris_1.gif
  modular_skyrat/icons/tetris/tetris_2.gif
  modular_skyrat/icons/tetris/tetris_3.gif
  modular_skyrat/icons/tetris/tetris_4.gif
  modular_skyrat/icons/tetris/tetris_5.gif
  modular_skyrat/icons/tetris/tetris_6.gif
  modular_skyrat/icons/tetris/tetris_7.gif
  modular_skyrat/icons/tetris/tetrisp0.gif
  modular_skyrat/icons/tetris/tetrisp1.gif
  modular_skyrat/icons/tetris/tetrisp2.gif
  modular_skyrat/icons/tetris/tetrisp3.gif
  modular_skyrat/icons/tetris/tetrisp4.gif
  modular_skyrat/icons/tetris/tetrisp5.gif
  modular_skyrat/icons/tetris/tetrisp6.gif
  modular_skyrat/icons/tetris/tetrisp7.gif
  tgstation.dme
  tgui/assets/tgui.js
  tgui/src/interfaces/tetris/tetris.js
  tgui/src/interfaces/tetris/tetris2.js
Labels: Feature, Needs Review, UI

#1979 Adds a bunch of emojis...
  modular_skyrat/icons/emoji.dmi
Labels: Sprites

#1958 [READY] More breast sizes to pick from. Airhead quirk. Speech impediment quirks.
  code/controllers/configuration/entries/game_options.dm
  code/controllers/subsystem/processing/quirks.dm
  code/game/machinery/doors/airlock.dm
  code/modules/mob/living/carbon/human/examine.dm
  config/game_options.txt
  modular_citadel/code/datums/status_effects/chems.dm
  modular_skyrat/code/datums/speech_mod/_speech_mod.dm
  modular_skyrat/code/datums/speech_mod/impediments.dm
  modular_skyrat/code/datums/status_effects/chems.dm
  modular_skyrat/code/datums/traits/negative.dm
  modular_skyrat/code/datums/traits/neutral.dm
  modular_skyrat/code/game/machinery/doors/airlock.dm
  tgstation.dme
Labels: Config Update, Feature, Needs Review, Tweak

#2011 Credits
  code/__HELPERS/roundend.dm
  code/_onclick/hud/credits.dm
  code/game/gamemodes/changeling/changeling.dm
  code/game/gamemodes/clock_cult/clock_cult.dm
  code/game/gamemodes/cult/cult.dm
  code/game/gamemodes/devil/devil_game_mode.dm
  code/game/gamemodes/extended/extended.dm
  code/game/gamemodes/game_mode.dm
  code/game/gamemodes/gangs/gangs.dm
  code/game/gamemodes/meteor/meteor.dm
  code/game/gamemodes/nuclear/nuclear.dm
  code/game/gamemodes/revolution/revolution.dm
  code/game/gamemodes/traitor/traitor.dm
  code/game/gamemodes/wizard/wizard.dm
  code/modules/client/client_defines.dm
  code/modules/client/client_procs.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/client/preferences_toggles.dm
  icons/credits.dmi
  icons/title_cards.dmi
  modular_skyrat/icons/credits/1zas.png
  modular_skyrat/icons/credits/2cluck.png
  modular_skyrat/icons/credits/3MPAOSA.png
  modular_skyrat/icons/credits/4_themed_NT.png
  modular_skyrat/icons/credits/4_themed_clown.png
  modular_skyrat/icons/credits/4_themed_cooks.png
  modular_skyrat/icons/credits/4_themed_syndie.png
  modular_skyrat/icons/credits/5BYOND.png
Labels: Feature, Sprites

#2010 Borg comms
  code/game/objects/items/devices/radio/radio.dm
  code/modules/mob/living/silicon/robot/robot.dm
  code/modules/mob/living/silicon/robot/robot_modules.dm
Labels: Feature, Fix, Tweak

#2004 Robotics Backpacks!
  code/modules/jobs/job_types/roboticist.dm
  modular_skyrat/code/game/objects/items/storage/backpacks/roboticist.dm
  modular_skyrat/code/modules/vending/wardrobes.dm
  modular_skyrat/icons/mob/clothing/back.dmi
  modular_skyrat/icons/obj/storage/roboticistpacks.dmi
  tgstation.dme
Labels: Feature

#2045 Add OOC Pref viewing to Cyborgs
  code/modules/mob/living/silicon/robot/examine.dm
  modular_skyrat/code/modules/mob/living/silicon/silicon.dm
  tgstation.dme
Labels: Feature

#1994 Food preferences in the character setup
  code/controllers/subsystem/processing/quirks.dm
  code/modules/client/preferences.dm
  modular_citadel/code/modules/client/preferences_savefile.dm
Labels: Feature

#2039 fixes and buffs shanks
  modular_skyrat/code/game/objects/items/weaponry.dm
Labels: Balance/Rebalance

#2070 [MIRROR-REPLACEMENT] Ports "Removes the absolute istype fest from footsteps"
  code/__DEFINES/footsteps.dm
  code/__DEFINES/is_helpers.dm
  code/datums/components/footstep.dm
  code/datums/dna.dm
  code/modules/mob/living/carbon/alien/humanoid/humanoid.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/physiology.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/monkey/monkey.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/simple_animal/bot/ed209bot.dm
  code/modules/mob/living/simple_animal/friendly/cat.dm
  code/modules/mob/living/simple_animal/friendly/dog.dm
  code/modules/mob/living/simple_animal/friendly/farm_animals.dm
  code/modules/mob/living/simple_animal/friendly/fox.dm
  code/modules/mob/living/simple_animal/friendly/panda.dm
  code/modules/mob/living/simple_animal/friendly/penguin.dm
  code/modules/mob/living/simple_animal/friendly/sloth.dm
  code/modules/mob/living/simple_animal/hostile/alien.dm
  code/modules/mob/living/simple_animal/hostile/bear.dm
  code/modules/mob/living/simple_animal/hostile/bosses/paperwizard.dm
  code/modules/mob/living/simple_animal/hostile/dark_wizard.dm
  code/modules/mob/living/simple_animal/hostile/faithless.dm
  code/modules/mob/living/simple_animal/hostile/giant_spider.dm
  code/modules/mob/living/simple_animal/hostile/gorilla/gorilla.dm
  code/modules/mob/living/simple_animal/hostile/hivebot.dm
  code/modules/mob/living/simple_animal/hostile/jungle/leaper.dm
  code/modules/mob/living/simple_animal/hostile/jungle/mega_arachnid.dm
  code/modules/mob/living/simple_animal/hostile/jungle/mook.dm
  code/modules/mob/living/simple_animal/hostile/megafauna/blood_drunk_miner.dm
  code/modules/mob/living/simple_animal/hostile/megafauna/bubblegum.dm
  code/modules/mob/living/simple_animal/hostile/megafauna/drake.dm
  code/modules/mob/living/simple_animal/hostile/mining_mobs/goliath.dm
  code/modules/mob/living/simple_animal/hostile/nanotrasen.dm
  code/modules/mob/living/simple_animal/hostile/pirate.dm
  code/modules/mob/living/simple_animal/hostile/retaliate/clown.dm
  code/modules/mob/living/simple_animal/hostile/retaliate/spaceman.dm
  code/modules/mob/living/simple_animal/hostile/russian.dm
  code/modules/mob/living/simple_animal/hostile/skeleton.dm
  code/modules/mob/living/simple_animal/hostile/syndicate.dm
  code/modules/mob/living/simple_animal/hostile/wizard.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
  code/modules/mob/living/simple_animal/slime/slime.dm
  modular_skyrat/code/modules/mob/living/simple_animal/hostile/megafauna/bubblegum.dm
  modular_skyrat/code/modules/mob/living/simple_animal/hostile/megafauna/glaurung.dm
  modular_skyrat/code/modules/mob/living/simple_animal/hostile/megafauna/rogueprocess.dm
  modular_skyrat/code/modules/mob/living/simple_animal/hostile/mining_mobs/shamblingminer.dm
Labels: Fix, Removal

#1945 Psychology
  _maps/map_files/BoxStation/BoxStation_Skyrat.dmm
  _maps/map_files/Deltastation/DeltaStation2_Skyrat.dmm
  _maps/map_files/KiloStation/KiloStation_Skyrat.dmm
  _maps/map_files/MetaStation/MetaStation_Skyrat.dmm
  _maps/map_files/PubbyStation/PubbyStation_Skyrat.dmm
  code/__DEFINES/access.dm
  code/__DEFINES/jobs.dm
  code/game/gamemodes/objective.dm
  code/game/gamemodes/objective_items.dm
  code/game/objects/items/devices/PDA/PDA_types.dm
  code/game/objects/items/religion.dm
  code/modules/clothing/under/jobs/medical.dm
  code/modules/events/wizard/departmentrevolt.dm
  code/modules/jobs/access.dm
  code/modules/jobs/job_types/chief_medical_officer.dm
  code/modules/jobs/jobs.dm
  config/jobs.txt
  modular_skyrat/code/_DEFINES/jobs.dm
  modular_skyrat/code/game/area/Space_Station_13_areas.dm
  modular_skyrat/code/game/machinery/computer/crew.dm
  modular_skyrat/code/game/objects/effects/landmarks.dm
  modular_skyrat/code/game/objects/items/religion.dm
  modular_skyrat/code/game/objects/structures/crates_lockers/closets/secure/medical.dm
  modular_skyrat/code/modules/jobs/access.dm
  modular_skyrat/code/modules/jobs/job_types/psychologist.dm
  modular_skyrat/icons/turf/areas.dmi
  tgstation.dme
  tools/mapmerge2/map_scripts/clothingunderrepath.txt
Labels: Config Update, Feature, Map Edit, Tools

#2098 Dynamic events fix
  code/game/gamemodes/dynamic/dynamic_rulesets_events.dm
Labels: Fix

#2083 Let's rebuild tgui in all branches that touch tgui files to make conflicts less likely to happen.
  .github/workflows/autobuild_tgui.yml
Labels: GitHub

#2101 Hypnotic stupor quirk
  modular_skyrat/code/datums/traits/neutral.dm
Labels: Feature

#2089 Lowers down carp event weights on non-dynamic
  code/modules/events/carp_migration.dm
  modular_skyrat/code/modules/events/tiger_carp_frenzy.dm
Labels: Tweak

#2108 this was not the intended effect :)
  .github/workflows/autobuild_tgui.yml
Labels: GitHub

#2104 Adds in a non-combat mode combat indicator hotkey
  code/modules/mob/living/living_combat.dm
  modular_skyrat/code/modules/keybindings/keybind/living.dm
  modular_skyrat/code/modules/mob/living/combat_indicator.dm
  tgstation.dme
Labels: Feature

#2112 [Map Edit] Fax Machines
  _maps/map_files/BoxStation/BoxStation_Skyrat.dmm
  _maps/map_files/Deltastation/DeltaStation2_Skyrat.dmm
  _maps/map_files/KiloStation/KiloStation_Skyrat.dmm
  _maps/map_files/MetaStation/MetaStation_Skyrat.dmm
  _maps/map_files/PubbyStation/PubbyStation_Skyrat.dmm
Labels: Feature, Map Edit

#2113 Removes gigantism and small traits, because we have sprite size % pref now
  modular_skyrat/code/_DEFINES/traits.dm
  modular_skyrat/code/datums/traits/neutral.dm
Labels: Removal

#2115 Fixes food preferences not respecting like/dislikes limits
  code/modules/client/preferences.dm
  modular_citadel/code/modules/client/preferences_savefile.dm
Labels: Fix

#2116 makes synthetic trait users not die from famine
  modular_skyrat/code/modules/mob/living/carbon/human/species_types/synths.dm
Labels: Fix

#2117 Fixes PKA manufacturing defects
  modular_skyrat/code/modules/projectiles/guns/energy/kinetic_accelerator.dm
Labels: Fix

#2165 Fixes missing shutters on Deltastation
  _maps/map_files/Deltastation/DeltaStation2_Skyrat.dmm
Labels: Fix, Map Edit

#2164 Modularises a keg so its removal upstream doesn't break maps in rotation.
  modular_skyrat/code/modules/reagents/reagent_containers/reagent_dispenser.dm
  tgstation.dme
Labels: Code Improvement

#2163 Fix double internals on spawn
  code/game/objects/items/storage/boxes.dm
Labels: Fix

#1850 Partially removes lavaland RNG megafauna spawns
  code/datums/ruins/lavaland.dm
  code/game/turfs/simulated/floor/plating/asteroid.dm
  code/modules/mob/living/simple_animal/hostile/megafauna/bubblegum.dm
  modular_skyrat/code/game/turfs/simulated/floor/asteroid.dm
Labels: Balance/Rebalance, Removal

#2139 [Modular] Alt cloak and boatcloaks
  modular_skyrat/code/modules/client/loadout/neck.dm
  modular_skyrat/code/modules/clothing/suits/cloaks.dm
  modular_skyrat/icons/mob/clothing/neck.dmi
  modular_skyrat/icons/obj/clothing/neck.dmi
Labels: Feature

#1869 #1720 improved snek taur but what about their suits?
  code/modules/mob/living/carbon/human/update_icons.dm
  modular_skyrat/icons/mob/clothing/taur_naga.dmi
  modular_skyrat/icons/mob/suits_taur.dmi
Labels: Refactor, Tweak

#1918 Staffwho, Adminverbs - Hide Most is useful
  code/modules/admin/admin_verbs.dm
  modular_citadel/code/modules/client/verbs/who.dm
  modular_citadel/code/modules/mentor/dementor.dm
  modular_skyrat/code/modules/admin/admin_verbs.dm
  modular_skyrat/code/modules/client/verbs/who.dm
Labels: Administration, Fix

#2130 [Ready] Event Panel
  code/__DEFINES/dcs/signals.dm
  code/_onclick/hud/_defines.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  icons/mob/screen_ghost.dmi
  modular_citadel/code/modules/client/preferences_savefile.dm
  modular_skyrat/code/_onclick/hud/ghost.dm
  modular_skyrat/code/datums/event_menu.dm
  modular_skyrat/code/modules/mob/dead/observer/observer.dm
  tgstation.dme
  tgui/assets/tgui.js
  tgui/src/interfaces/event_menu.ract
  tgui/src/interfaces/spawners_menu.ract
Labels: Feature, Needs Review, Sprites, UI

#2128 fixes locker mech icon bugs
  modular_skyrat/code/game/mecha/mecha_construction_paths.dm
  modular_skyrat/icons/mecha/mech_construct.dmi
  modular_skyrat/icons/mecha/mech_construction.dmi
Labels: Fix

#2138 Curb flip spam
  modular_skyrat/code/modules/mob/emote.dm
Labels: Balance/Rebalance

#2107 [Ready] Increased smaller Terror Spiders speed.
  modular_skyrat/code/modules/mob/living/simple_animal/terror_spiders/spider_types/black.dm
  modular_skyrat/code/modules/mob/living/simple_animal/terror_spiders/spider_types/gray.dm
  modular_skyrat/code/modules/mob/living/simple_animal/terror_spiders/spider_types/green.dm
  modular_skyrat/code/modules/mob/living/simple_animal/terror_spiders/spider_types/red.dm
  modular_skyrat/code/modules/mob/living/simple_animal/terror_spiders/spider_types/white.dm
  modular_skyrat/code/modules/mob/living/simple_animal/terror_spiders/terror_spiders.dm
Labels: Balance/Rebalance, Needs Review

#2105 Adds polychromic gear to loadout
  modular_skyrat/code/modules/client/loadout/uniform.dm
Labels: Feature

#2120 Double check before starting game early
  code/modules/admin/admin.dm
Labels: Administration

#2001 Encryption key changes
  code/modules/client/verbs/looc.dm
  modular_skyrat/code/modules/cargo/packs/misc.dm
  modular_skyrat/code/modules/research/designs/telecomms_designs.dm
  modular_skyrat/code/modules/research/techweb/all_nodes.dm
  modular_skyrat/code/modules/research/techweb/nodes/engineering_nodes.dm
  modular_skyrat/code/modules/research/techweb/nodes/misc_nodes.dm
  tgstation.dme
Labels: Feature, Tweak

#2038 [Code Bounty] Department IDs
  code/game/objects/items/cards_ids.dm
  code/modules/jobs/job_types/atmospheric_technician.dm
  code/modules/jobs/job_types/bartender.dm
  code/modules/jobs/job_types/botanist.dm
  code/modules/jobs/job_types/cargo_technician.dm
  code/modules/jobs/job_types/chemist.dm
  code/modules/jobs/job_types/cook.dm
  code/modules/jobs/job_types/detective.dm
  code/modules/jobs/job_types/geneticist.dm
  code/modules/jobs/job_types/janitor.dm
  code/modules/jobs/job_types/medical_doctor.dm
  code/modules/jobs/job_types/paramedic.dm
  code/modules/jobs/job_types/quartermaster.dm
  code/modules/jobs/job_types/roboticist.dm
  code/modules/jobs/job_types/scientist.dm
  code/modules/jobs/job_types/security_officer.dm
  code/modules/jobs/job_types/shaft_miner.dm
  code/modules/jobs/job_types/station_engineer.dm
  code/modules/jobs/job_types/virologist.dm
  code/modules/jobs/job_types/warden.dm
  modular_skyrat/code/game/objects/items/cards_ids.dm
  modular_skyrat/code/modules/jobs/job_types/psychologist.dm
  modular_skyrat/icons/mob/inhands/equipment/idcards_lefthand.dmi
  modular_skyrat/icons/mob/inhands/equipment/idcards_righthand.dmi
  modular_skyrat/icons/obj/card.dmi
Labels: Feature, Sprites

#2168 [READY] Removes the Combat Shotgun from the Warden's Locker
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
Labels: Needs Review, Removal

#2162 Buff Sentient Disease
  code/modules/antagonists/disease/disease_abilities.dm
Labels: Balance/Rebalance

#2177 Event panel runtime fixes
  modular_skyrat/code/_onclick/hud/ghost.dm
  modular_skyrat/code/datums/event_menu.dm
  tgui/assets/tgui.js
  tgui/src/interfaces/event_menu.ract
Labels: UI
