Repository Skyrat-SS13/Skyrat13, pull requests merged in 2020-08, with the labels that each got.

#3179 Actually fixes bee balm.
  icons/obj/hydroponics/harvest.dmi
Labels: Fix, Sprites

#3176 Birbs chirp now
  modular_skyrat/code/modules/mob/living/carbon/human/species_types/anthro/avian.dm
Labels: Tweak

#3044 Ghost Cafe Cyborgs!
  _maps/map_files/generic/CentCom_Skyrat.dmm
  modular_skyrat/code/datums/ai_laws.dm
  modular_skyrat/code/game/objects/items/borg_shapeshifter.dm
  modular_skyrat/code/game/objects/structures/ghost_role_spawners.dm
  modular_skyrat/code/modules/mob/living/silicon/robot/robot.dm
  modular_skyrat/code/modules/mob/living/silicon/robot/robot_modules.dm
  modular_skyrat/icons/obj/machines/robot_storage.dmi
Labels: Feature, Fix, Map Edit

#2993 Makes the meteor shuttle emag-only
  modular_skyrat/code/datums/shuttles.dm
  tgstation.dme
Labels: Tweak

#3202 Alert admins for unresolved tickets
  code/modules/admin/verbs/adminhelp.dm
  modular_skyrat/code/modules/admin/verbs/adminhelp.dm
Labels: Administration

#3205 Revert "Alert admins for unresolved tickets"
  code/modules/admin/verbs/adminhelp.dm
  modular_skyrat/code/modules/admin/verbs/adminhelp.dm
Labels: Revert

#3059 Hopefully fixes terrospiders :t conflict with traitors :t
  modular_skyrat/code/modules/language/terrorspider.dm
Labels: Tweak

#3206 massive kudzu/spacevines buff
  _maps/map_files/BoxStation/BoxStation_Skyrat.dmm
  _maps/map_files/Deltastation/DeltaStation2_Skyrat.dmm
  _maps/map_files/KiloStation/KiloStation_Skyrat.dmm
  _maps/map_files/MetaStation/MetaStation_Skyrat.dmm
  _maps/map_files/PubbyStation/PubbyStation_Skyrat.dmm
  code/modules/events/spacevine.dm
Labels: Feature, Map Edit, Tweak

#3011 Adds Medical and Prescription Medical/Security HUDS to the Loadout menu
  modular_skyrat/code/modules/client/loadout/_medical.dm
  modular_skyrat/code/modules/client/loadout/_security.dm
  tgstation.dme
Labels: Feature

#3013 [FULLMERGE PLEASE I BEG YOU] Unfucks some emotes
  code/modules/mob/living/carbon/human/emote.dm
  code/modules/mob/living/emote.dm
Labels: Fix

#3233 FIXES THE FUCKING PRESCRIPTION LOADOUT TO WORK FOR BLUESHIELD PLEASE SPEEDMERGE THIS FUCK
  modular_skyrat/code/modules/client/loadout/_security.dm
Labels: Fix

#3242 Let's make the bureaucracy error event not limit the amount of assistants
  code/modules/events/bureaucratic_error.dm
Labels: Fix

#3241 Fixes that one pipe in engineering that was visible for some reason
  _maps/map_files/BoxStation/BoxStation_Skyrat.dmm
Labels: Map Edit, Tweak

#3236 Replaces the Shutter sound with something more fitting.
  code/game/machinery/doors/poddoor.dm
  code/game/machinery/doors/shutters.dm
  modular_skyrat/sound/machinery/shutters_close.ogg
  modular_skyrat/sound/machinery/shutters_open.ogg
  tgstation.dme
Labels: Tweak

#3220 Refurbished Centcom Docking Area - The Squeakquel
  _maps/map_files/generic/CentCom_Skyrat.dmm
  modular_skyrat/code/game/machinery/Sleeper.dm
  modular_skyrat/code/game/machinery/cloning.dm
  tgstation.dme
Labels: Map Edit

#3278 Small Fix - No more invisible Skeleton Key
  modular_skyrat/code/game/objects/items/cards_ids.dm
Labels: Fix

#3227 adds kudzu turf, nerfs venus
  code/modules/events/spacevine.dm
  code/modules/mob/living/simple_animal/hostile/venus_human_trap.dm
Labels: Balance/Rebalance, Feature

#3228 huge blob buff, please be careful
  code/__DEFINES/antagonists.dm
  code/modules/antagonists/blob/blob/blobs/blob_mobs.dm
  code/modules/antagonists/blob/blob/blobs/core.dm
  code/modules/antagonists/blob/blob/blobs/factory.dm
  code/modules/antagonists/blob/blob/blobs/node.dm
  code/modules/antagonists/blob/blob/blobs/resource.dm
  code/modules/antagonists/blob/blob/blobs/shield.dm
  code/modules/antagonists/blob/blob/powers.dm
Labels: Tweak

#3339 Flavour tweaks to the ghost cafe.
  code/game/objects/structures/ghost_role_spawners.dm
  modular_skyrat/code/game/objects/structures/ghost_role_spawners.dm
Labels: Tweak

#3210 Added Drake disguises to the shapeshifting device for cyborgs
  modular_skyrat/code/game/objects/items/borg_shapeshifter.dm
Labels: Feature

#3365 Fix service borg offset in borg shapeshifter
  modular_skyrat/code/game/objects/items/borg_shapeshifter.dm
Labels: Fix

#3238 Otieborgs & Engihounds!
  code/modules/mob/living/silicon/robot/robot_modules.dm
  modular_skyrat/icons/mob/widerobot.dmi
Labels: Feature, Fix, Sprites

#3369 Removes donor hair/hat from monkeyspawn
  code/modules/mob/living/carbon/monkey/monkey.dm
Labels: Fix, Removal

#3370 Various ERP verb fixes
  code/modules/arousal/arousal.dm
  modular_skyrat/code/datums/interactions/_interaction.dm
  modular_skyrat/code/datums/interactions/interaction_definitions.dm
  modular_skyrat/code/datums/interactions/interaction_interface.dm
  modular_skyrat/code/datums/interactions/interaction_mob.dm
  modular_skyrat/code/datums/interactions/lewd/_lewd.dm
  modular_skyrat/code/datums/interactions/lewd/lewd_datums.dm
  modular_skyrat/code/datums/interactions/lewd/lewd_interactions.dm
  modular_skyrat/code/datums/interactions/lewd/lewd_species.dm
  modular_skyrat/code/datums/interactions/lewd/objects.dm
  tgstation.dme
Labels: Feature, Fix

#3349 Removed STYLE_NO_ANTHRO_ICON from exploration suit and children objects
  modular_skyrat/code/modules/mining/equipment/explorer_gear.dm
Labels: Fix

#3293 Oh the horrors! [MODULAR] [READY]
  code/modules/mob/living/carbon/life.dm
  modular_skyrat/master_files/sound/effects/horror_scream.ogg
  modular_skyrat/master_files/sound/effects/horror_scream_reverb.ogg
  modular_skyrat/master_files/sound/misc/tear.ogg
  modular_skyrat/modules/horrorform/code/modules/antagonists/changeling/powers/horror_form.dm
  modular_skyrat/modules/horrorform/code/modules/mob/hostile/true_changeling.dm
  modular_skyrat/modules/horrorform/icons/mob/actions/actions_changeling.dmi
  modular_skyrat/modules/horrorform/icons/mob/animal.dmi
  modular_skyrat/modules/horrorform/readme.md
  tgstation.dme
Labels: Feature, Needs Review

#3383 Changes to the ghost cafe, small CC changes, adds the stack fabricator device.
  _maps/map_files/generic/CentCom_Skyrat.dmm
  code/modules/research/machinery/cafe_imprinter.dm
  modular_skyrat/code/game/objects/items/stackspawner/stackspawner.dmi
  modular_skyrat/code/game/objects/items/stackspawner/stackspawner_item.dm
  modular_skyrat/code/game/objects/items/stackspawner/stackspawner_machine.dm
  tgstation.dme
Labels: Feature, Map Edit, Tweak

#3291 [Ready] The CE can now command Poly to shut it, or perch on their shoulder.
  code/modules/mob/living/simple_animal/parrot.dm
  modular_skyrat/code/modules/mob/living/simple_animal/parrot.dm
  tgstation.dme
Labels: Feature, Needs Review

#3218 Tiger Carp yum yum!
  code/modules/food_and_drinks/food/snacks_meat.dm
  modular_skyrat/code/modules/mob/living/simple_animal/hostile/carp.dm
Labels: Balance/Rebalance, Feature

#3388 Adds a mentorsay hotkey(praise)
  code/modules/keybindings/keybind/client.dm
Labels: Feature

#3342 fixes goldbrand
  modular_skyrat/code/modules/ruins/lavalandruin_code/misc.dm
Labels: Fix

#3298 Royal 79101t Classic Manual Typewriter (mint Green)
  code/modules/client/preferences.dm
Labels: Grammar and Formatting

#3386 supermatter cascade portal
  _maps/map_files/Mining/Lavaland_Skyrat.dmm
  _maps/map_files/generic/CentCom_Skyrat.dmm
  modular_skyrat/code/game/gamemodes/endgame/smblob.dm
  modular_skyrat/code/game/gamemodes/endgame/smblob.dmi
  modular_skyrat/code/game/gamemodes/endgame/smportal.dm
  modular_skyrat/code/game/gamemodes/endgame/smportal.dmi
  tgstation.dme
Labels: Feature, Map Edit

#3219 Removes cook access to the morgue.
  code/modules/jobs/job_types/cook.dm
Labels: Removal, Tweak

#3245 FUCK imperial measurements
  code/__DEFINES/preferences.dm
  code/controllers/subsystem/processing/quirks.dm
  code/modules/arousal/organs/penis.dm
  code/modules/client/preferences.dm
  modular_skyrat/code/modules/client/preferences_toggles.dm
Labels: Feature

#3246 fixes railgun bullet casing bug
  modular_skyrat/code/datums/components/crafting/crafting_results/railgun.dm
Labels: Fix

#3292 Unfucks Rogue Process
  modular_skyrat/code/modules/mining/lavaland/necropolis_chests.dm
  modular_skyrat/code/modules/mob/living/simple_animal/hostile/megafauna/rogueprocess.dm
Labels: Balance/Rebalance

#3303 Removes blood freezers from lavaland
  _maps/RandomRuins/StationRuins/Lavaland/Mining_Station/Mining_Station_Public_01_Skyrat.dmm
  _maps/map_files/Mining/Lavaland_Skyrat.dmm
Labels: Balance/Rebalance, Map Edit, Removal

#3304 Biology
  code/datums/diseases/advance/symptoms/species.dm
Labels: Fix

#3295 [READY] Better explosion echoes
  code/datums/explosion.dm
  code/game/sound.dm
  sound/effects/creak1.ogg
  sound/effects/creak2.ogg
  sound/effects/creak3.ogg
  sound/effects/explosioncreak1.ogg
  sound/effects/explosioncreak2.ogg
Labels: Needs Review, Sound, Testmerge Candidate, Tweak

#3312 Megafauna music preference
  code/__DEFINES/preferences.dm
  code/modules/client/preferences.dm
  modular_skyrat/code/modules/client/preferences_toggles.dm
  modular_skyrat/code/modules/mob/living/simple_animal/hostile/megafauna/blood_drunk_miner.dm
  modular_skyrat/code/modules/mob/living/simple_animal/hostile/megafauna/bubblegum.dm
  modular_skyrat/code/modules/mob/living/simple_animal/hostile/megafauna/colossus.dm
  modular_skyrat/code/modules/mob/living/simple_animal/hostile/megafauna/demonic_frost_miner.dm
  modular_skyrat/code/modules/mob/living/simple_animal/hostile/megafauna/drake.dm
  modular_skyrat/code/modules/mob/living/simple_animal/hostile/megafauna/gladiator.dm
  modular_skyrat/code/modules/mob/living/simple_animal/hostile/megafauna/hierophant.dm
  modular_skyrat/code/modules/mob/living/simple_animal/hostile/megafauna/legion.dm
  modular_skyrat/code/modules/mob/living/simple_animal/hostile/megafauna/megafauna.dm
  modular_skyrat/code/modules/mob/living/simple_animal/hostile/megafauna/rogueprocess.dm
  modular_skyrat/code/modules/mob/living/simple_animal/hostile/megafauna/sif.dm
Labels: Feature

#3382 Fix fake dogborgs not being able to rest
  modular_skyrat/code/game/objects/items/borg_shapeshifter.dm
Labels: Fix

#3367 Power Tools: The Floofening
  code/game/objects/items/tools/saw.dm
  code/game/objects/items/tools/screwdriver.dm
  code/game/objects/items/tools/wrench.dm
  code/modules/research/designs/tool_designs.dm
  code/modules/research/techweb/nodes/tools_nodes.dm
  modular_skyrat/code/game/objects/items/tools/modular_tools.dm
  modular_skyrat/code/modules/research/designs/tool_designs.dm
  modular_skyrat/icons/mob/inhands/equipment/tools_lefthand.dmi
  modular_skyrat/icons/mob/inhands/equipment/tools_righthand.dmi
  modular_skyrat/icons/obj/clothing/belt_overlays.dmi
  modular_skyrat/icons/obj/tools.dmi
  tgstation.dme
Labels: Feature

#3403 Updated the borg shapeshifter
  modular_skyrat/code/game/objects/items/borg_shapeshifter.dm
Labels: Feature

#3411 Cafe fixes
  _maps/map_files/generic/CentCom_Skyrat.dmm
  code/game/objects/structures/ghost_role_spawners.dm
  modular_skyrat/code/game/objects/structures/ghost_role_spawners.dm
Labels: Fix, Map Edit, Tweak

#3417 Fixes the super shotgun
  modular_skyrat/code/modules/mining/lavaland/necropolis_chests.dm
Labels: Fix

#3413 Fixes the MI13 stealth suit
  modular_skyrat/code/modules/clothing/under/stealth.dm
Labels: Fix

#3409 fixes inorganic biology for real
  code/datums/diseases/advance/symptoms/species.dm
Labels: Fix

#3407 fixes the crucible, unfucks some sif necklace code
  modular_skyrat/code/modules/mining/lavaland/necropolis_chests.dm
  modular_skyrat/icons/mob/inhands/weapons/crucible_lefthand.dmi
  modular_skyrat/icons/mob/inhands/weapons/crucible_righthand.dmi
  modular_skyrat/icons/mob/inhands/weapons/swords_lefthand.dmi
  modular_skyrat/icons/mob/inhands/weapons/swords_righthand.dmi
Labels: Fix

#3374 Fixes the allergic quirk
  modular_skyrat/code/datums/traits/negative.dm
Labels: Fix

#3399 [Bugfix] Poly properly resets on unbuckle
  modular_skyrat/code/modules/mob/living/simple_animal/parrot.dm
Labels: Fix

#3412 Fixes sprite accessories not showing proper to the new separated skyrat species
  code/modules/mob/dead/new_player/sprite_accessories/body_markings.dm
  code/modules/mob/dead/new_player/sprite_accessories/legs_and_taurs.dm
  code/modules/mob/dead/new_player/sprite_accessories/snouts.dm
  code/modules/mob/dead/new_player/sprite_accessories/tails.dm
Labels: Fix

#3424 [SPEEDMERGE] Fixes punch miss messages, fixes timestop memes
  code/game/objects/effects/proximity.dm
  code/modules/mob/living/carbon/human/species.dm
Labels: Fix

#3425 Ultimate disrespect.
  modular_skyrat/code/datums/interactions/interaction_definitions.dm
  modular_skyrat/code/datums/interactions/interaction_mob.dm
Labels: Feature

#3426 Fixes terror spiders gibbing randomly
  modular_skyrat/code/modules/mob/living/simple_animal/terror_spiders/terror_spiders.dm
Labels: Fix

#3422 [SPRITE IMPROVEMENT] USP Changes
  modular_skyrat/code/modules/projectiles/guns/ballistic/pistol.dm
  modular_skyrat/icons/obj/guns/projectile.dmi
Labels: Grammar and Formatting, Removal, Tweak

#3396 Items show armor ratings on examine more
  code/__DEFINES/modular_skyrat/misc.dm
  code/game/objects/items.dm
  modular_skyrat/code/game/objects/items.dm
  modular_skyrat/code/game/objects/obj.dm
  tgstation.dme
Labels: Feature

#3436 [Fix] Green hand drills are longer unlocked via basic mining
  code/modules/research/techweb/nodes/tools_nodes.dm
  modular_skyrat/code/modules/research/designs/tool_designs.dm
Labels: Fix

#3431 ghost cafe fixes
  _maps/map_files/generic/CentCom_Skyrat.dmm
  code/game/area/areas/centcom.dm
  code/game/objects/structures/ghost_role_spawners.dm
  modular_skyrat/code/game/objects/structures/ghost_role_spawners.dm
Labels: Feature, Map Edit, Tweak

#3430 Removes reroll limit on contractor kit.
  code/modules/antagonists/traitor/equipment/contractor.dm
Labels: Removal, Tweak

#3457 more box medbay change
  _maps/map_files/BoxStation/BoxStation_Skyrat.dmm
Labels: Feature, Map Edit

#3223 [READY] The Cargo Utilitarian Update (Part One)
  modular_skyrat/code/modules/clothing/refactor.dm
  modular_skyrat/icons/mob/clothing/cargoutil.dmi
  modular_skyrat/icons/mob/clothing/cargoutil_digi.dmi
  modular_skyrat/icons/obj/clothing/cargoutilit.dmi
Labels: Feature, Needs Review

#3461 one more medbay change before I lose my mind
  _maps/map_files/BoxStation/BoxStation_Skyrat.dmm
Labels: Feature, Fix, Map Edit, Removal

#3446 Kills dracula
  code/datums/dna.dm
  code/modules/antagonists/bloodsucker/datum_bloodsucker.dm
  code/modules/antagonists/bloodsucker/powers/feed.dm
  code/modules/mob/living/carbon/monkey/monkey.dm
  code/modules/mob/transform_procs.dm
  code/modules/reagents/chemistry/reagents/other_reagents.dm
  modular_skyrat/code/modules/mining/equipment/regenerative_core.dm
Labels: Balance/Rebalance

#3445 Talking on a headset makes a chk chk sound
  code/game/objects/items/devices/radio/headset.dm
  modular_skyrat/sound/radio/common.ogg
  modular_skyrat/sound/radio/security.ogg
  modular_skyrat/sound/radio/syndie.ogg
Labels: Sound

#3458 Fixes nitryl breathing, improves stimulum somewhat
  code/modules/movespeed/modifiers/reagents.dm
  code/modules/reagents/chemistry/reagents/other_reagents.dm
  code/modules/surgery/organs/lungs.dm
Labels: Fix, Tweak

#3419 (QoL) Highly controversial huge nerf to robust grass.
  code/game/objects/structures/flora.dm
  modular_skyrat/code/game/objects/structures/flora.dm
Labels: Fix

#3465 AOOC toggled on by default
  code/_globalvars/configuration.dm
Labels: Tweak

#3462 Adds a S.W.A.T. node to the BEPIS, buffs blueshield armor
  modular_skyrat/code/game/objects/items/weaponry.dm
  modular_skyrat/code/modules/clothing/head/helmet.dm
  modular_skyrat/code/modules/clothing/suits/armor.dm
  modular_skyrat/code/modules/research/designs/weapon_designs.dm
  modular_skyrat/code/modules/research/techweb/nodes/bepis_nodes.dm
  modular_skyrat/icons/mob/clothing/head.dmi
  modular_skyrat/icons/mob/clothing/suit.dmi
  modular_skyrat/icons/mob/inhands/weapons/melee_lefthand.dmi
  modular_skyrat/icons/mob/inhands/weapons/melee_righthand.dmi
  modular_skyrat/icons/obj/clothing/hats.dmi
  modular_skyrat/icons/obj/clothing/suits.dmi
  modular_skyrat/icons/obj/items_and_weapons.dmi
Labels: Feature

#3440 [Bagatji drink recipe] There's a Snake in my Bar
  code/modules/flufftext/Hallucination.dm
  code/modules/mob/living/carbon/carbon_defines.dm
  modular_skyrat/code/modules/food_and_drinks/recipes/drinks_recipes.dm
  modular_skyrat/code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
  modular_skyrat/icons/obj/drinks.dmi
Labels: Feature

#3453 Fixes the science budget gaining hundreds of thousands of credits
  code/modules/research/techweb/_techweb.dm
Labels: Fix

#3467 AOOC anonymized
  code/modules/client/client_defines.dm
  code/modules/client/verbs/aooc.dm
Labels: Tweak

#3442 Mirrors #3126 correctly with modular changes (Paramedic heirloom is now a health analyzer)
  modular_skyrat/code/datums/traits/negative.dm
Labels: Fix

#3404 Fixes stinky genital appearance code, properly respects measurement preferences of the viewer
  code/game/objects/items/devices/scanners.dm
  code/modules/arousal/genitals.dm
  code/modules/arousal/organs/breasts.dm
  code/modules/arousal/organs/penis.dm
  code/modules/arousal/organs/testicles.dm
  code/modules/arousal/organs/vagina.dm
  code/modules/client/preferences.dm
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/mob/living/carbon/human/species_types/jellypeople.dm
Labels: Fix, Tweak

#3421 Adds A new emergency shuttle, the "Turtle" to buy
  _maps/shuttles/emergency_turtle.dmm
  code/datums/shuttles.dm
Labels: Feature, Map Edit, Tweak

#3481 removed angry goats from loadout & added Jake's fix and a plushie
  code/game/objects/items/miscellaneous.dm
  code/modules/food_and_drinks/kitchen_machinery/grill.dm
  code/modules/mob/living/simple_animal/bot/medbot.dm
  modular_skyrat/code/game/objects/items/plushies.dm
  modular_skyrat/icons/obj/plushies.dmi
Labels: Feature, Fix, Tweak

#3410 Nerfs Candy Bloodcrawl
  modular_skyrat/code/modules/mob/living/simple_animal/hostile/mining_mobs/elites/candy.dm
Labels: Balance/Rebalance

#3460 Small JungleRat sprite-dump update
  modular_skyrat/code/modules/mining/lavaland/necropolis_chests.dm
  modular_skyrat/icons/mob/clothing/head.dmi
  modular_skyrat/icons/mob/clothing/head_muzzled.dmi
  modular_skyrat/icons/mob/clothing/suit.dmi
  modular_skyrat/icons/mob/clothing/suit_digi.dmi
  modular_skyrat/icons/obj/clothing/hats.dmi
  modular_skyrat/icons/obj/clothing/suits.dmi
  modular_skyrat/icons/obj/guns/energy.dmi
Labels: Sprites

#3459 Ghost Cafe 2 & Opting out of EORG
  _maps/map_files/generic/CentCom_Skyrat.dmm
  code/game/objects/structures/ghost_role_spawners.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  modular_skyrat/code/_HELPERS/roundend.dm
  modular_skyrat/code/game/objects/effects/landmarks.dm
  modular_skyrat/code/game/turfs/open/floor/planetfloor.dm
  modular_skyrat/code/game/turfs/open/floor/plating/lavaland_jungle.dm
  modular_skyrat/icons/turf/floors/planetfloor.dmi
  tgstation.dme
Labels: Feature, Fix, Map Edit, Tweak

#3420 Kinetic Accelerators of the Rainbow
  modular_skyrat/code/modules/mining/lavaland/necropolis_chests.dm
  modular_skyrat/code/modules/mining/machine_vending.dm
  modular_skyrat/code/modules/projectiles/guns/energy/kinetic_accelerator.dm
  modular_skyrat/icons/obj/guns/energy.dmi
Labels: Feature

#2893 [Testmerge] Dynamic client-side processed lighting on a component
  code/__DEFINES/layers_planes.dm
  code/game/machinery/dance_machine.dm
  code/game/objects/effects/effect_system/effects_sparks.dm
  code/game/objects/items/cigs_lighters.dm
  code/game/objects/items/devices/PDA/PDA.dm
  code/game/objects/items/devices/flashlight.dm
  code/game/objects/items/melee/energy.dm
  code/game/objects/items/tools/weldingtool.dm
  code/modules/atmospherics/environmental/LINDA_fire.dm
  code/modules/clothing/head/hardhat.dm
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/spacesuits/hardsuit.dm
  code/modules/hydroponics/plant_genes.dm
  code/modules/lighting/lighting_turf.dm
  code/modules/mining/equipment/kinetic_crusher.dm
  code/modules/mob/living/silicon/robot/robot.dm
  code/modules/mob/living/simple_animal/bot/bot.dm
  code/modules/projectiles/gun.dm
  code/modules/projectiles/projectile/beams.dm
  code/modules/surgery/organs/eyes.dm
  modular_skyrat/code/_onclick/hud/plane_master.dm
  modular_skyrat/code/datums/components/overlay_lighting.dm
  modular_skyrat/icons/misc/light_128.dmi
  modular_skyrat/icons/misc/light_160.dmi
  modular_skyrat/icons/misc/light_192.dmi
  modular_skyrat/icons/misc/light_224.dmi
  modular_skyrat/icons/misc/light_256.dmi
  modular_skyrat/icons/misc/light_288.dmi
  modular_skyrat/icons/misc/light_32.dmi
  modular_skyrat/icons/misc/light_320.dmi
  modular_skyrat/icons/misc/light_352.dmi
  modular_skyrat/icons/misc/light_64.dmi
  modular_skyrat/icons/misc/light_96.dmi
  tgstation.dme
Labels: Feature

#3437 Gives the warden a choice beacon so he can select between the particle defender or compact combat shotgun
  code/modules/projectiles/boxes_magazines/internal/shotgun.dm
  modular_skyrat/code/modules/jobs/job_types/warden.dm
  modular_skyrat/code/modules/projectiles/boxes_magazines/internal/shotgun.dm
  modular_skyrat/code/modules/projectiles/guns/ballistic/shotgun.dm
  tgstation.dme
Labels: Balance/Rebalance

#3456 Uniform Sprites: Foreman, Mining Tech. Portable Turret adjustment. Fixed missing sprite for durathread jumpsuit.
  code/game/machinery/porta_turret/portable_turret_construct.dm
  icons/mob/clothing/uniform_digi.dmi
  modular_skyrat/code/modules/clothing/under/jobs/miningexpanded.dm
  modular_skyrat/code/modules/jobs/job_types/mining_foreman.dm
  modular_skyrat/icons/mob/clothing/uniform.dmi
  modular_skyrat/icons/mob/clothing/uniform_digi.dmi
  modular_skyrat/icons/obj/clothing/uniform.dmi
  tgstation.dme
Labels: Balance/Rebalance, Feature, Sprites

#3472 Some small changes to make the particle defender more in line with other shotguns.
  modular_citadel/code/modules/projectiles/guns/pumpenergy.dm
Labels: Balance/Rebalance

#3490 [Fix] Ghost Cafe 2 (EORG zone) fixes
  _maps/map_files/generic/CentCom_Skyrat.dmm
Labels: Fix, Map Edit

#3489 fixes IPC burn wounds not cabling proper
  modular_skyrat/code/datums/wounds/mechanical/burn.dm
Labels: Fix
