Repository Skyrat-SS13/Skyrat13, pull requests merged in 2020-07, with the labels that each got.

#2779 Revert "A literal shitposter PR"
  code/game/objects/effects/contraband.dm
  code/modules/paperwork/photocopier.dm
  modular_skyrat/code/game/objects/effects/contraband.dm
  modular_skyrat/code/modules/paperwork/photocopier.dm
  modular_skyrat/icons/obj/contraband.dmi
  tgstation.dme
Labels: Revert

#2708 tgui: ByondUi, Cam Console, Spyglass Kit, Map Popups
  code/__HELPERS/game.dm
  code/_onclick/hud/map_popups.dm
  code/datums/movement_detector.dm
  code/game/machinery/computer/camera.dm
  code/game/objects/items/devices/spyglasses.dm
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  code/modules/tgui/external.dm
  code/modules/tgui/tgui.dm
  icons/mob/map_backgrounds.dmi
  interface/skin.dmf
  node_modules/.yarn-integrity
  tgstation.dme
  tgui-next/README.md
  tgui-next/packages/common/collections.js
  tgui-next/packages/common/timer.js
  tgui-next/packages/tgui/byond.js
  tgui-next/packages/tgui/components/Box.js
  tgui-next/packages/tgui/components/Button.js
  tgui-next/packages/tgui/components/ByondUi.js
  tgui-next/packages/tgui/components/Toast.js
  tgui-next/packages/tgui/components/index.js
  tgui-next/packages/tgui/interfaces/Bepis.js
  tgui-next/packages/tgui/interfaces/CameraConsole.js
  tgui-next/packages/tgui/interfaces/Canvas.js
  tgui-next/packages/tgui/interfaces/GravityGenerator.js
  tgui-next/packages/tgui/interfaces/HypnoChair.js
  tgui-next/packages/tgui/interfaces/KitchenSink.js
  tgui-next/packages/tgui/interfaces/LanguageMenu.js
  tgui-next/packages/tgui/interfaces/Launchpad.js
  tgui-next/packages/tgui/interfaces/NaniteRemote.js
  tgui-next/packages/tgui/interfaces/NtosConfiguration.js
  tgui-next/packages/tgui/interfaces/OperatingComputer.js
  tgui-next/packages/tgui/layout.js
  tgui-next/packages/tgui/public/tgui.bundle.css
  tgui-next/packages/tgui/routes.js
  tgui-next/packages/tgui/store.js
  tgui-next/packages/tgui/styles/components/Button.scss
  tgui-next/packages/tgui/styles/components/CameraConsole.scss
  tgui-next/packages/tgui/styles/components/Layout.scss
  tgui-next/packages/tgui/styles/components/NtosWrapper.scss
  tgui-next/packages/tgui/styles/components/ProgressBar.scss
  tgui-next/packages/tgui/styles/main.scss
  tgui-next/packages/tgui/styles/themes/ntos.scss
  tgui-next/packages/tgui/webpack.config.js
  tgui-next/yarn.lock
Labels: Feature, Sprites, UI

#2775 [READY] [Modular] TG Station Gateway Fix and Port V2
  _maps/RandomZLevels/away_mission/Academy.dmm
  _maps/RandomZLevels/away_mission/SnowCabin.dmm
  _maps/RandomZLevels/away_mission/TheBeach.dmm
  _maps/RandomZLevels/away_mission/caves.dmm
  _maps/RandomZLevels/away_mission/challenge.dmm
  _maps/RandomZLevels/away_mission/moonoutpost19.dmm
  _maps/RandomZLevels/away_mission/research.dmm
  _maps/RandomZLevels/away_mission/snowdin.dmm
  _maps/RandomZLevels/away_mission/spacebattle.dmm
  _maps/RandomZLevels/away_mission/undergroundoutpost45.dmm
  _maps/RandomZLevels/away_mission/wildwest.dmm
  _maps/map_files/BoxStation/BoxStation_Skyrat.dmm
  _maps/map_files/CogStation/CogStation_Skyrat.dmm
  _maps/map_files/Deltastation/DeltaStation2_Skyrat.dmm
  _maps/map_files/IceBoxStation/IceBoxStation.dmm
  _maps/map_files/KiloStation/KiloStation_Skyrat.dmm
  _maps/map_files/LambdaStation/lambda_Skyrat.dmm
  _maps/map_files/MetaStation/MetaStation_Skyrat.dmm
  _maps/map_files/PubbyStation/PubbyStation_Skyrat.dmm
  code/modules/awaymissions/mission_code/spacebattle.dm
  config/awaymissionconfig.txt
  config/game_options.txt
  config/vr_config.txt
  modular_skyrat/code/_onclick/observer.dm
  modular_skyrat/code/controllers/subsystem/mapping.dm
  modular_skyrat/code/modules/awaymissions/gateway.dm
  modular_skyrat/code/modules/awaymissions/zlevel.dm
  modular_skyrat/icons/obj/machines/gateway.dmi
  tgstation.dme
  tgui-next/packages/tgui/interfaces/Gateway.js
  tgui-next/packages/tgui/routes.js
Labels: Config Update, Feature, Fix, Map Edit, Needs Review, UI

#2832 [Fix] RSD now uses the correct icon-state when designating a shuttle's area
  code/modules/shuttle/shuttle_creation/shuttle_creator.dm
Labels: Fix

#2831 [Modular] FIXES THE FUCKING SECURITY JUMPSUITS
  modular_skyrat/icons/mob/clothing/uniform.dmi
  modular_skyrat/icons/mob/clothing/uniform_digi.dmi
Labels: Fix

#2805 Metastation Bugfixing
  _maps/map_files/MetaStation/MetaStation_Skyrat.dmm
Labels: Fix, Map Edit

#2709 [Semi-Modular] Femboy Robotics, Femboy Robotics (Male Bootyborgs)
  code/modules/mob/living/silicon/robot/robot_modules.dm
  modular_skyrat/code/game/objects/items/borg_shapeshifter.dm
  modular_skyrat/code/modules/mob/living/silicon/robot/robot_modules.dm
  modular_skyrat/icons/mob/clownborgs.dmi
  modular_skyrat/icons/mob/moreborgsmodels.dmi
Labels: Feature, Sprites

#2647 Nerfs executioner sword, lightly buffs the shortsword
  modular_skyrat/code/datums/components/crafting/crafting_results/swords.dm
  modular_skyrat/code/modules/mining/lavaland/necropolis_chests.dm
Labels: Balance/Rebalance

#2454 Synth bugfixing
  code/modules/client/preferences.dm
  code/modules/mob/living/carbon/update_icons.dm
  modular_skyrat/code/datums/traits/neutral.dm
  modular_skyrat/code/modules/mob/living/carbon/human/species_types/synths.dm
  modular_skyrat/code/modules/surgery/bodyparts/bodyparts.dm
Labels: Fix

#2267 Antags can see exploitable info through examine
  code/__DEFINES/antagonists.dm
  code/modules/antagonists/_common/antag_datum.dm
  code/modules/antagonists/brainwashing/brainwashing.dm
  code/modules/mob/living/carbon/human/examine.dm
  modular_skyrat/code/modules/mob/living/carbon/human/human.dm
Labels: Feature

#2704 Removes weapon circuitry from research
  code/modules/integrated_electronics/subtypes/weaponized.dm
Labels: Removal

#2690 Bushfighter beret and security uniform reskins
  modular_skyrat/code/modules/clothing/refactor.dm
  modular_skyrat/icons/mob/clothing/head.dmi
  modular_skyrat/icons/mob/clothing/head_muzzled.dmi
  modular_skyrat/icons/mob/clothing/uniform.dmi
  modular_skyrat/icons/mob/clothing/uniform_digi.dmi
  modular_skyrat/icons/obj/clothing/hats.dmi
  modular_skyrat/icons/obj/clothing/uniform.dmi
Labels: Sprites

#2685 Unofficial Skyrat Edit - Patch/Addon for #2684 (#12570) PR
  code/modules/clothing/head/misc.dm
  icons/mob/clothing/head.dmi
  icons/obj/clothing/hats.dmi
  modular_skyrat/code/modules/client/loadout/head.dm
  modular_skyrat/code/modules/clothing/refactor.dm
Labels: Sprites

#2905 Temporarily adjusts bombs on syndicate uplinks
  modular_skyrat/code/modules/uplink/uplink_explosives.dm
Labels: Balance/Rebalance, Removal

#2897 Revamp and fix of the TED agent! [Modular] [Ready]
  code/modules/clothing/outfits/standard.dm
  modular_skyrat/code/game/objects/items/chrono_eraser.dm
  modular_skyrat/code/modules/clothing/outfits/standard.dm
  modular_skyrat/code/modules/clothing/spacesuits/chronosuit.dm
  modular_skyrat/icons/mob/clothing/head.dmi
  modular_skyrat/icons/mob/clothing/head_muzzled.dmi
  modular_skyrat/icons/mob/clothing/suit.dmi
  modular_skyrat/icons/mob/clothing/suit_digi.dmi
  tgstation.dme
Labels: Fix, Needs Review, Tweak

#2892 Alternative Captains Suit! [Modular] [Ready]
  modular_skyrat/code/modules/client/loadout/uniform.dm
  modular_skyrat/code/modules/clothing/under/suits.dm
  modular_skyrat/icons/mob/clothing/uniform.dmi
  modular_skyrat/icons/mob/clothing/uniform_digi.dmi
  modular_skyrat/icons/obj/clothing/uniform.dmi
  tgstation.dme
Labels: Feature, Needs Review

#2887 FIXES CYBORG SIZE MODULES AND REDUCES THEIR EFFECT
  code/game/objects/items/robot/robot_upgrades.dm
  code/modules/mob/living/silicon/robot/robot.dm
  modular_skyrat/code/game/objects/items/robot/robot_upgrades.dm
Labels: Fix

#2916 Fixes floor lights disappearing in emergencies
  icons/obj/lighting.dmi
Labels: Fix, Sprites

#2940 Corporate regulations PR but more modular and maintainable
  code/controllers/configuration/entries/general.dm
  code/game/objects/items/manuals.dm
  config/config.txt
  config/skyrat/skyrat_config.txt
  modular_skyrat/code/controllers/configuration/entries/skyrat_config.dm
  modular_skyrat/code/game/objects/items/manuals.dm
  tgstation.dme
Labels: Config Update, Feature

#2928 Comments out the Detomatix
  code/modules/uplink/uplink_items/uplink_explosives.dm
Labels: Removal

#2936 [MIRROR] Fix Paramedic Jumpsuit
  code/modules/clothing/under/jobs/medical.dm
  icons/mob/clothing/uniform.dmi
Labels: Sprites

#2944 Let's finally disable overthrow.
  modular_skyrat/code/game/gamemodes/dynamic/dynamic_rulesets_roundstart.dm
Labels: Testmerge Candidate

#2961 fixes character setup
  code/modules/client/preferences.dm
Labels: Fix

#2902 Obfuscates the contractor tablet
  code/modules/modular_computers/computers/item/tablet.dm
Labels: Tweak

#2471 You now can play the circle game.
  code/game/objects/items/weaponry.dm
Labels: Fix

#2515 Makes automatic guns actually automatic
  code/modules/projectiles/gun.dm
  code/modules/projectiles/guns/ballistic/automatic.dm
Labels: Feature

#2639 Surgery code improvement.
  code/__DEFINES/modular_skyrat/medical_defines.dm
  code/__DEFINES/traits.dm
  code/modules/reagents/chemistry/reagents/medicine_reagents.dm
  modular_skyrat/code/_DEFINES/medical_defines.dm
  modular_skyrat/code/modules/reagents/chemistry/reagents/medicine_reagents.dm
  modular_skyrat/code/modules/surgery/surgery_step.dm
  tgstation.dme
Labels: Code Improvement

#2903 Spaceproofs BMP Asteroid Skeletons
  _maps/RandomZLevels/away_mission/caves.dmm
  modular_skyrat/code/game/objects/structures/spawner.dm
  modular_skyrat/code/modules/awaymissions/corpse.dm
  modular_skyrat/code/modules/mob/living/simple_animal/hostile/skeleton.dm
  tgstation.dme
Labels: Fix, Map Edit

#2784 [Modular] Adds the Sensible Suitskirt to the loadout
  modular_skyrat/code/modules/client/loadout/uniform.dm
Labels: Feature, Stale

#2736 [Not ready][Removal] Comments out teleporter species fuckery
  code/game/machinery/teleporter.dm
Labels: Removal

#2869 Small Engineering QoL changes
  code/game/machinery/doors/airlock.dm
  code/game/machinery/spaceheater.dm
  code/game/objects/items/RCD.dm
  code/game/objects/items/circuitboards/machine_circuitboards.dm
  code/game/objects/items/holosign_creator.dm
  code/modules/power/singularity/collector.dm
Labels: Feature, Fix, Tweak

#2868 Comments out split personality
  code/datums/brain_damage/split_personality.dm
Labels: Removal

#2861 (BOUNTY) Silicon Interactions Menu 2: Electric Boogaloo (Or why I don't use git bash)
  modular_skyrat/code/interactions/_interaction.dm
  modular_skyrat/code/interactions/interaction_interface.dm
  modular_skyrat/code/interactions/lewd/_lewd.dm
  modular_skyrat/code/interactions/lewd/lewd_interactions.dm
Labels: Feature, Tweak

#2852 Tweaks to the stale PR marking action
  .github/workflows/stale.yml
Labels: GitHub

#2933 Fixes pugilist gloves and variations fucking with the fists of steel quirk
  code/modules/clothing/gloves/miscellaneous.dm
Labels: Fix

#2938 Fixes an oversight with medipen dispensing
  code/modules/reagents/chemistry/machinery/chem_master.dm
  code/modules/reagents/reagent_containers/hypospray.dm
Labels: Tweak

#2896 unfucks ebony blade a bit
  modular_skyrat/code/game/objects/items/weaponry.dm
Labels: Fix

#2866 Better ERG
  _maps/map_files/generic/CentCom_Skyrat.dmm
  code/__HELPERS/roundend.dm
  code/datums/mind.dm
  code/game/objects/effects/landmarks.dm
  code/modules/client/preferences.dm
  modular_skyrat/code/_onclick/hud/ghost.dm
  modular_skyrat/code/datums/actions/erg.dm
  modular_skyrat/icons/mob/screen_gen.dmi
  modular_skyrat/icons/mob/screen_ghost.dmi
  tgstation.dme
Labels: Feature, Map Edit

#2618 Multi-character language keys, fixes some language bugs i guess
  code/modules/mob/living/say.dm
  modular_skyrat/code/modules/language/buggy.dm
  modular_skyrat/code/modules/language/calcic.dm
  modular_skyrat/code/modules/language/dunmeri.dm
  modular_skyrat/code/modules/language/moffic.dm
  modular_skyrat/code/modules/language/neokanji.dm
  modular_skyrat/code/modules/language/shadowtongue.dm
  modular_skyrat/code/modules/language/solcommon.dm
  modular_skyrat/code/modules/language/sylvan.dm
  modular_skyrat/code/modules/language/technorussian.dm
  modular_skyrat/code/modules/language/vox.dm
Labels: Feature, Fix, Tweak

#2985 I HAVE A MOUTH AND YET I MUST SPEAK IN TECHNORUSSIAN
  code/modules/mob/living/say.dm
Labels: Fix

#2696 Drunkenness changes
  code/modules/mob/living/carbon/life.dm
  code/modules/mob/mob_helpers.dm
  modular_skyrat/code/_onclick/hud/alert.dm
  tgstation.dme
Labels: Balance/Rebalance, Feature

#2717 [Modular] [Bugfix] Fixes the Medical Gygax to be printable; Makes the Medical Gygax no longer just a more expensive Ody reskin.
  modular_skyrat/code/game/mecha/mech_fabricator.dm
  modular_skyrat/code/game/mecha/medical/medigax.dm
  tgstation.dme
Labels: Balance/Rebalance, Fix

#2806 Greyscale moth sprites, preferences don't species squash moths
  code/modules/client/preferences_savefile.dm
  modular_skyrat/icons/mob/moth_parts.dmi
Labels: Fix, Sprites

#2819 fixes ranged glory kills and unfucks legion loot
  modular_skyrat/code/modules/mob/living/simple_animal/hostile/megafauna/legion.dm
  modular_skyrat/code/modules/mob/living/simple_animal/hostile/megafauna/legionhard.dm
  modular_skyrat/code/modules/mob/living/simple_animal/hostile/mining_mobs/miningmobs.dm
Labels: Fix

#2820 [READY] General shotgun overhaul
  code/modules/projectiles/guns/ballistic/revolver.dm
  code/modules/projectiles/guns/ballistic/shotgun.dm
  icons/mob/inhands/weapons/64x_guns_left.dmi
  icons/mob/inhands/weapons/64x_guns_right.dmi
  icons/obj/guns/projectile.dmi
Labels: Needs Review, Sprites

#2828 [Tweak] Radial Vendors
  code/game/objects/items/circuitboards/machine_circuitboards.dm
  code/modules/cargo/packs/vending.dm
  code/modules/vending/kinkmate.dm
  modular_skyrat/code/_globalvars/lists/vending.dm
  tgstation.dme
Labels: Code Improvement

#2844 adds icon for eyepatch mesons
  modular_skyrat/code/modules/clothing/glasses/_glasses.dm
  modular_skyrat/icons/obj/clothing/glasses.dmi
Labels: Sprites

#2846 Fixes blood code insanity, blood options in da character setup :flushed:
  code/__DEFINES/misc.dm
  code/__HELPERS/icons.dm
  code/controllers/subsystem/processing/quirks.dm
  code/datums/dna.dm
  code/game/atoms.dm
  code/game/objects/effects/decals/cleanable/humans.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/clothing/shoes/_shoes.dm
  code/modules/mob/living/blood.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/human/species_types/abductors.dm
  code/modules/mob/living/carbon/human/species_types/android.dm
  code/modules/mob/living/carbon/human/species_types/angel.dm
  code/modules/mob/living/carbon/human/species_types/bugmen.dm
  code/modules/mob/living/carbon/human/species_types/dwarves.dm
  code/modules/mob/living/carbon/human/species_types/flypeople.dm
  code/modules/mob/living/carbon/human/species_types/ipc.dm
  code/modules/mob/living/carbon/human/species_types/jellypeople.dm
  code/modules/mob/living/carbon/human/species_types/mushpeople.dm
  code/modules/mob/living/carbon/human/species_types/podpeople.dm
  code/modules/mob/living/carbon/human/species_types/shadowpeople.dm
  code/modules/mob/living/carbon/human/species_types/synthliz.dm
  code/modules/mob/living/carbon/human/species_types/synths.dm
  code/modules/mob/living/carbon/human/species_types/zombies.dm
  code/modules/mob/living/carbon/update_icons.dm
  code/modules/mob/mob_helpers.dm
  code/modules/projectiles/projectile.dm
  code/modules/reagents/chemistry/reagents/other_reagents.dm
  config/game_options.txt
  modular_skyrat/code/modules/mob/living/carbon/human/species_types/vox.dm
Labels: Code Improvement, Config Update, Feature, Fix, Needs Review

#2914 Ventclog Chem Remix
  code/modules/events/vent_clog.dm
Labels: Tweak

#2929 Shamelessly steals nanite updates from a downstream
  code/modules/research/designs/nanite_designs.dm
  code/modules/research/nanites/extra_settings/number.dm
  code/modules/research/nanites/nanite_programs/sensor.dm
  code/modules/research/nanites/program_disks.dm
  modular_skyrat/code/modules/research/nanites/utility.dm
  modular_skyrat/code/modules/research/techweb/nodes/misc_nodes.dm
  tgstation.dme
Labels: Feature, Fix

#2930 Synths unbruhification
  code/datums/components/nanites.dm
  code/datums/diseases/_disease.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/research/nanites/nanite_programs.dm
  code/modules/research/nanites/nanite_programs/buffing.dm
  code/modules/research/nanites/nanite_programs/healing.dm
  code/modules/research/nanites/nanite_programs/protocols.dm
  code/modules/research/nanites/nanite_programs/rogue.dm
  code/modules/research/nanites/nanite_programs/suppression.dm
  code/modules/research/nanites/nanite_programs/utility.dm
  code/modules/research/nanites/nanite_programs/weapon.dm
  modular_skyrat/code/_HELPERS/mobs.dm
  modular_skyrat/code/modules/mob/living/carbon/human/species_types/synths.dm
Labels: Feature, Fix

#2918 Ports descriptors from Baystation, squashes species squash
  code/__DEFINES/is_helpers.dm
  code/__HELPERS/pronouns.dm
  code/controllers/subsystem/processing/quirks.dm
  code/game/objects/items/weaponry.dm
  code/game/turfs/open.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/food_and_drinks/food/snacks/meat.dm
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/human/species_types/furrypeople.dm
  code/modules/reagents/chemistry/reagents/other_reagents.dm
  code/modules/reagents/chemistry/recipes/slime_extracts.dm
  config/game_options.txt
  modular_skyrat/code/datums/descriptors/_descriptor.dm
  modular_skyrat/code/datums/descriptors/descriptor_types/generic.dm
  modular_skyrat/code/datums/descriptors/descriptor_types/species_based/nabber.dm
  modular_skyrat/code/datums/descriptors/descriptor_types/species_based/skrell.dm
  modular_skyrat/code/datums/descriptors/descriptor_types/species_based/vox.dm
  modular_skyrat/code/modules/mob/living/carbon/human/species.dm
  modular_skyrat/code/modules/mob/living/carbon/human/species_types/anthro/_anthro.dm
  modular_skyrat/code/modules/mob/living/carbon/human/species_types/anthro/aquatic.dm
  modular_skyrat/code/modules/mob/living/carbon/human/species_types/anthro/avian.dm
  modular_skyrat/code/modules/mob/living/carbon/human/species_types/anthro/lizardpeople.dm
  modular_skyrat/code/modules/mob/living/carbon/human/species_types/anthro/mammal.dm
  modular_skyrat/code/modules/mob/living/carbon/human/species_types/anthro/mothpeople.dm
  modular_skyrat/code/modules/mob/living/carbon/human/species_types/anthro/xenohybrid.dm
  modular_skyrat/code/modules/mob/living/carbon/human/species_types/exotic/plasmamen.dm
  modular_skyrat/code/modules/mob/living/carbon/human/species_types/exotic/shadowpeople.dm
  modular_skyrat/code/modules/mob/living/carbon/human/species_types/exotic/vox.dm
  modular_skyrat/code/modules/mob/living/carbon/human/species_types/exotic/zombies.dm
  modular_skyrat/code/modules/mob/living/carbon/human/species_types/general/screams.dm
  modular_skyrat/code/modules/mob/living/carbon/human/species_types/human/_humanoid.dm
  modular_skyrat/code/modules/mob/living/carbon/human/species_types/human/dunmer.dm
  modular_skyrat/code/modules/mob/living/carbon/human/species_types/synthetic/ipc.dm
  modular_skyrat/code/modules/mob/living/carbon/human/species_types/synthetic/synthliz.dm
  modular_skyrat/code/modules/mob/living/carbon/human/species_types/synthetic/synths.dm
  modular_skyrat/code/modules/mob/living/combat_indicator.dm
  modular_skyrat/code/modules/vending/kinkmate.dm
  tgstation.dme
Labels: Config Update, Feature

#2986 It's walter season, get you one
  modular_skyrat/icons/emoji.dmi
  modular_skyrat/icons/mob/popup_flicks.dmi
  tgstation.dme
Labels: Feature

#2987 <BR>
  code/modules/mob/living/carbon/human/examine.dm
Labels: Grammar and Formatting

#2998 Fixes screamer mask runtimes and game breaking issues
  modular_skyrat/code/_HELPERS/mobs.dm
  modular_skyrat/code/modules/clothing/traitor/ghostface.dm
Labels: Fix

#3015 adds the primitive processor
  code/game/objects/items/stacks/sheets/sheet_types.dm
  modular_skyrat/code/game/machinery/primitiveprocessor.dm
  modular_skyrat/icons/obj/kitchen.dmi
  tgstation.dme
Labels: Feature

#2997 Being droonk takes effort
  code/modules/mob/living/carbon/life.dm
Labels: Feature

#3061 REVERT'S EORG CHANGES
  _maps/map_files/generic/CentCom_Skyrat.dmm
  code/__HELPERS/roundend.dm
  code/datums/mind.dm
  code/game/objects/effects/landmarks.dm
  code/modules/client/preferences.dm
  modular_skyrat/code/_onclick/hud/ghost.dm
  modular_skyrat/code/datums/actions/erg.dm
  tgstation.dme
Labels: Map Edit, Removal, Revert

#3030 Preservahyde is now a medicine
  code/modules/mob/living/carbon/life.dm
  code/modules/reagents/chemistry/reagents/other_reagents.dm
  code/modules/reagents/chemistry/recipes/others.dm
  code/modules/reagents/reagent_containers/hypospray.dm
  modular_skyrat/code/modules/mob/living/carbon/life.dm
  modular_skyrat/code/modules/reagents/chemistry/reagents/medicine_reagents.dm
  modular_skyrat/code/modules/reagents/chemistry/recipes/medicine.dm
Labels: Tweak

#2829 [READY] Rebalances almost all ballistic projectiles
  code/modules/projectiles/projectile/bullets/lmg.dm
  code/modules/projectiles/projectile/bullets/pistol.dm
  code/modules/projectiles/projectile/bullets/revolver.dm
  code/modules/projectiles/projectile/bullets/rifle.dm
  code/modules/projectiles/projectile/bullets/smg.dm
  code/modules/projectiles/projectile/bullets/sniper.dm
Labels: Needs Review

#3018 Old pulse sound!
  code/modules/projectiles/ammunition/energy/laser.dm
  modular_skyrat/sound/weapons/pulse.ogg
Labels: Sound

#3025 Particle Accelerator Update [QOL]
  code/datums/wires/particle_accelerator.dm
  code/modules/power/singularity/particle_accelerator/particle.dm
  code/modules/power/singularity/particle_accelerator/particle_accelerator.dm
  code/modules/power/singularity/particle_accelerator/particle_control.dm
  code/modules/power/singularity/particle_accelerator/particle_emitter.dm
  modular_skyrat/icons/obj/machines/particle_accelerator.dmi
Labels: Feature, Fix, Tweak

#2956 removing golems and lifebringers from xenoarch
  _maps/map_files/Mining/Lavaland_Skyrat.dmm
Labels: Map Edit, Removal

#2959 removes syndie miner, makes crypto harder
  modular_skyrat/code/game/machinery/cryptominer/cryptominers.dm
  modular_skyrat/code/game/objects/items/circuitboards/machine_circuitboards.dm
  modular_skyrat/code/modules/research/designs/machine_designs.dm
  modular_skyrat/code/modules/research/techweb/all_nodes.dm
  modular_skyrat/code/modules/research/techweb/nodes/bluespace_nodes.dm
Labels: Balance/Rebalance, Removal

#2838 Tile Floofing: Allows you to change what type of titanium and what type of plasteel types you place.
  code/game/objects/items/stacks/tiles/tile_mineral.dm
  code/game/turfs/simulated/floor/mineral_floor.dm
  modular_skyrat/code/game/objects/items/stacks/tiles/tile_reskinning.dm
  modular_skyrat/code/game/objects/items/stacks/tiles/tyle_types.dm
  modular_skyrat/code/game/turfs/open/mineral_floor.dm
  modular_skyrat/code/game/turfs/simulated/floor/misc_floor.dm
  modular_skyrat/icons/obj/tiles.dmi
  modular_skyrat/icons/turf/floors.dmi
  tgstation.dme
Labels: Feature, Testmerge Candidate

#3093 Medical and Goodie Cargo Additions
  modular_skyrat/code/modules/cargo/packs/bloat.dm
  modular_skyrat/code/modules/cargo/packs/goodies.dm
  modular_skyrat/code/modules/cargo/packs/medical.dm
  modular_skyrat/code/modules/cargo/packs/special.dm
  tgstation.dme
Labels: Feature

#3009 [FULLMERGE PLEASE I BEG YOU] Lavaland bugfixing
  modular_skyrat/code/modules/clothing/head/misc.dm
  modular_skyrat/code/modules/mining/equipment/kinetic_crusher.dm
  modular_skyrat/code/modules/mining/lavaland/necropolis_chests.dm
  modular_skyrat/code/modules/mob/living/simple_animal/hostile/megafauna/rogueprocess.dm
  modular_skyrat/code/modules/mob/living/simple_animal/hostile/megafauna/sif.dm
Labels: Fix

#3010 [FULLMERGE PLEASE I BEG YOU] Come to <BR>azil
  code/modules/mob/living/carbon/human/examine.dm
  modular_skyrat/code/datums/descriptors/_descriptor.dm
Labels: Grammar and Formatting

#2965 [FULLMERGE PLEASE I BEG YOU] Character setup beautification
  code/_globalvars/lists/names.dm
  code/modules/client/preferences.dm
  code/modules/mob/living/carbon/human/species.dm
  modular_skyrat/code/modules/mob/living/carbon/human/species_types/general/screams.dm
  modular_skyrat/code/modules/mob/living/carbon/human/species_types/general/snowflake.dm
  tgstation.dme
Labels: Tweak

#3109 [FIX - SPEEDMERGE I BEG] Fixes mediborg grippers just not having a sprite, bricking them.
  code/game/objects/items/robot/robot_items.dm
Labels: Fix

#3106 [fullmerge please fuck] unfucks glory kills
  modular_skyrat/code/modules/mob/living/simple_animal/hostile/megafauna/megafauna.dm
  modular_skyrat/code/modules/mob/living/simple_animal/hostile/mining_mobs/miningmobs.dm
Labels: Fix

#3107 [fullmerge please] Certified 1907 Antique Underwood No. 4 Typewriter moment
  code/modules/client/preferences.dm
  modular_skyrat/code/modules/mob/living/carbon/human/species_types/general/snowflake.dm
Labels: Grammar and Formatting

#3108 [fullmerge please] Adds language icon OOC emojis
  modular_skyrat/icons/emoji.dmi
Labels: Feature

#3110 Overthrow commentout
  modular_skyrat/code/game/gamemodes/dynamic/dynamic_rulesets_roundstart.dm
Labels: Removal

#2851 [Fix] Plasma thrusters now look for the correct tile for an engine heater to link to when facing North or South. [TESTMERGE ONLY]
  code/game/machinery/shuttle/shuttle_engine.dm
Labels: Fix

#3134 [READY] Fixes Double Barrel shotgun reskins & Inhands
  code/modules/projectiles/guns/ballistic/revolver.dm
Labels: Needs Review

#2943 Brings the shrink module to how it was before
  modular_skyrat/code/game/objects/items/robot/robot_upgrades.dm
Labels: Feature

#3178 [Ready] Three oneline changes
  code/game/objects/items/stacks/sheets/sheet_types.dm
  code/modules/events/spacevine.dm
  code/modules/mob/living/simple_animal/bot/medbot.dm
  code/modules/mob/living/simple_animal/hostile/venus_human_trap.dm
Labels: Feature, Fix, Needs Review, Tweak

#3017 Togglable Emergency Shuttle
  code/__DEFINES/shuttles.dm
  code/controllers/subsystem/shuttle.dm
  code/game/gamemodes/game_mode.dm
  code/modules/admin/verbs/randomverbs.dm
  code/modules/shuttle/emergency.dm
  code/modules/shuttle/shuttle.dm
  modular_skyrat/code/modules/admin/admin_verbs.dm
Labels: Administration, Feature
