Repository Skyrat-SS13/Skyrat13, pull requests merged in 2020-03, with the labels that each got.

#466 Ports King Goat from /tg/station
  modular_skyrat/_maps/RandomRuins/LavaRuins/kinggoatboss.dmm
  modular_skyrat/_maps/RandomRuins/SpaceRuins/kinggoatarena.dmm
  modular_skyrat/code/datums/ruins/lavaland.dm
  modular_skyrat/code/datums/ruins/space.dm
  modular_skyrat/code/game/area/areas/ruins/lavaland.dm
  modular_skyrat/code/game/machinery/computer/arcade.dm
  modular_skyrat/code/game/objects/items/plushes/plushes.dm
  modular_skyrat/code/game/objects/structures/ladders.dm
  modular_skyrat/code/modules/clothing/head/misc.dm
  modular_skyrat/code/modules/mining/equipment/kinetic_crusher.dm
  modular_skyrat/code/modules/mining/lavaland/necropolis_chests.dm
  modular_skyrat/code/modules/mining/shelters.dm
  modular_skyrat/code/modules/mob/living/simple_animal/friendly/farm_animals.dm
  modular_skyrat/code/modules/mob/living/simple_animal/hostile/megafauna/king_of_goats.dm
  modular_skyrat/code/modules/mob/living/simple_animal/hostile/megafauna/megafauna.dm
  modular_skyrat/code/modules/projectiles/guns/energy/kinetic_accelerator.dm
  modular_skyrat/code/modules/ruins/lavalandruin_code/kinggoat.dm
  modular_skyrat/icons/mob/head.dmi
  modular_skyrat/icons/mob/head_muzzled.dmi
  modular_skyrat/icons/mob/king_of_goats.dmi
  modular_skyrat/icons/mob/large-worn-icons/64x64/head.dmi
  modular_skyrat/icons/obj/clothing/hats.dmi
  modular_skyrat/icons/obj/lavaland/artefacts.dmi
  modular_skyrat/icons/obj/plushes.dmi
  modular_skyrat/sound/ambience/Visager-Battle.ogg
  modular_skyrat/sound/ambience/Visager-Miniboss_Fight.ogg
  modular_skyrat/sound/items/goatsound.ogg
  tgstation.dme
Labels: Feature

#479 Fixes the 9mm rubber box in autolathe to be printable
  modular_skyrat/code/modules/research/designs/autolathe_designs/autolathe_designs_sec_and_hacked.dm
Labels: Tweak

#456 [Modular] Engieborgs and Plasma
  code/modules/mob/living/silicon/robot/robot_modules.dm
  modular_skyrat/code/game/objects/items/robot/robot_upgrades.dm
  modular_skyrat/code/game/objects/items/stacks/sheets/glass.dm
  modular_skyrat/code/game/objects/items/stacks/sheets/mineral.dm
  modular_skyrat/code/game/objects/items/stacks/sheets/sheet_types.dm
  modular_skyrat/code/modules/mob/living/silicon/robot/robot_modules.dm
  modular_skyrat/code/modules/research/designs/mechfabricator_designs.dm
  modular_skyrat/code/modules/research/techweb/all_nodes.dm
  tgstation.dme
Labels: Feature

#458 Adds a praetor suit (DOOM 2016) as a legion drop
  modular_skyrat/code/modules/mob/living/simple_animal/hostile/megafauna/legion.dm
  modular_skyrat/icons/mob/head.dmi
  modular_skyrat/icons/mob/head_muzzled.dmi
  modular_skyrat/icons/mob/suit.dmi
  modular_skyrat/icons/mob/suit_digi.dmi
  modular_skyrat/icons/obj/clothing/hats.dmi
  modular_skyrat/icons/obj/clothing/suits.dmi
Labels: Feature, Sprites, Tweak

#487 Makes welding masks not hide face when up
  modular_skyrat/code/modules/clothing/masks/gasmask.dm
  tgstation.dme
Labels: Tweak

#488 Adds in a new race, Synths.
  code/modules/surgery/bodyparts/bodyparts.dm
  config/game_options.txt
  modular_citadel/icons/mob/mutant_bodyparts.dmi
  modular_skyrat/code/modules/mob/dead/new_player/sprite_accessories/synthliz_accessories.dm
  modular_skyrat/code/modules/mob/living/carbon/human/species_types/ipc.dm
  modular_skyrat/code/modules/mob/living/carbon/human/species_types/synthliz.dm
  modular_skyrat/icons/mob/synthliz/synthliz_antennas.dmi
  modular_skyrat/icons/mob/synthliz/synthliz_body_markings.dmi
  modular_skyrat/icons/mob/synthliz/synthliz_parts_greyscale.dmi
  modular_skyrat/icons/mob/synthliz/synthliz_snouts.dmi
  modular_skyrat/icons/mob/synthliz/synthliz_tails.dmi
  tgstation.dme
Labels: Config Update, Feature

#424 Removes slaughterlings, replaces them with blood smacks
  modular_skyrat/code/modules/mob/living/simple_animal/hostile/megafauna/bubblegum.dm
  tgstation.dme
Labels: Balance/Rebalance, Removal

#482 Surgery now requires anesthetics to go smoothly
  modular_skyrat/code/modules/surgery/surgery_step.dm
  tgstation.dme
Labels: Balance/Rebalance

#486 Revenant changes
  modular_skyrat/code/modules/antagonists/revenant/revenant.dm
  modular_skyrat/code/modules/antagonists/revenant/revenant_abilities.dm
  modular_skyrat/icons/mob/actions/actions_revenant.dmi
  modular_skyrat/icons/mob/mob.dmi
  tgstation.dme
Labels: Balance/Rebalance, Feature, Tweak

#501 Fixes north facing synth waggy tail
  modular_skyrat/icons/mob/synthliz/synthliz_tails.dmi
Labels: Fix

#504 [Modular] Service Shaker x4 and Fix
  modular_skyrat/code/modules/mob/living/silicon/robot/robot_modules.dm
  modular_skyrat/code/modules/reagents/reagents_containers/borghydro.dm
  modular_skyrat/icons/obj/drinks.dmi
Labels: Feature, Fix

#506 Fixes some oversights with surgery
  modular_skyrat/code/modules/surgery/surgery_step.dm
Labels: Fix

#507 Removes minefield component from the emagged minesweeper
  modular_skyrat/code/game/machinery/computer/arcade/minesweeper.dm
  tgstation.dme
Labels: Removal

#508 Fixes nightmare names
  modular_skyrat/code/modules/mob/living/carbon/human/species_types/shadowpeople.dm
  tgstation.dme
Labels: Fix

#493 [Modular] a Bluespace Locker
  _maps/map_files/generic/CentCom.dmm
  code/__DEFINES/maps.dm
  modular_skyrat/code/_HELPERS/unsorted.dm
  modular_skyrat/code/controllers/subsystem/bluespace_locker.dm
  modular_skyrat/code/game/area/Space_Station_13_areas.dm
  modular_skyrat/code/game/objects/structures/crates_lockers/closets/bluespace_locker.dm
  modular_skyrat/icons/obj/closet.dmi
  tgstation.dme
Labels: Feature, Map Edit

#519 [Fix] Service Shakers weren't children before, now they are.
  modular_skyrat/code/modules/mob/living/silicon/robot/robot_modules.dm
  modular_skyrat/code/modules/reagents/reagents_containers/borghydro.dm
Labels: Fix

#520 Fixes Vore pref on examine taking the wrong value
  modular_skyrat/code/modules/mob/living/carbon/human/human.dm
Labels: Fix

#541 Fixes borgs being too slow
  modular_skyrat/code/modules/mob/living/silicon/robot/robot.dm
  tgstation.dme
Labels: Tweak

#537 New admin verb and improved admin who
  modular_skyrat/code/modules/admin/admin_verbs.dm
  modular_skyrat/code/modules/client/verbs/who.dm
  modular_skyrat/sound/effects/duckhonk.ogg
  tgstation.dme
Labels: Feature

#538 Adds in a lewd verbs sound toggle
  modular_skyrat/code/_DEFINES/preferences.dm
  modular_skyrat/code/interactions/lewd/_lewd.dm
  modular_skyrat/code/modules/client/preferences_toggles.dm
  tgstation.dme
Labels: Feature

#548 Fixes revenant LPM
  modular_skyrat/code/modules/antagonists/revenant/revenant.dm
Labels: Fix

#564 Fixes /who on light mode cause I borked it
  modular_skyrat/code/modules/client/verbs/who.dm
Labels: Fix

#566 Muzzled, digi and taur alternate_worn_icon.
  code/modules/mob/living/carbon/human/update_icons.dm
  modular_skyrat/code/game/objects/items.dm
  modular_skyrat/code/modules/clothing/spacesuits/hardsuit.dm
  modular_skyrat/code/modules/clothing/suits/armor.dm
  modular_skyrat/code/modules/clothing/under/jobs/security.dm
  modular_skyrat/code/modules/mob/living/simple_animal/hostile/megafauna/bubblegumhard.dm
Labels: Feature, Tweak

#571 fixes gun grabbing text
  modular_skyrat/code/game/objects/items.dm
Labels: Fix

#567 Fixed the engi instructor cloak's description.
  modular_skyrat/code/modules/clothing/suits/cloaks.dm
Labels: Grammar and Formatting

#605 [Modular] station-locked to off-station pin
  code/modules/projectiles/pins.dm
  modular_skyrat/code/modules/projectiles/pins.dm
  tgstation.dme
Labels: Tweak

#612 Fixes our modular snouts
  modular_skyrat/code/modules/mob/dead/new_player/sprite_accessories/snouts.dm
Labels: Fix

#613 Updates the lewd verb ass slap sound
  modular_skyrat/code/interactions/lewd/lewd_interactions.dm
Labels: Sound

#615 SSD and Typing indicator improvements
  modular_skyrat/code/modules/mob/living/ssd_indicator.dm
  modular_skyrat/code/modules/mob/typing_indicator.dm
  modular_skyrat/icons/mob/typing_indicator.dmi
Labels: Tweak

#617 Adds a new traitor item: A roblox sword.
  modular_skyrat/code/game/objects/items/weaponry.dm
  modular_skyrat/code/modules/uplink/uplink_dangerous.dm
  modular_skyrat/icons/obj/items/roblox.dmi
  modular_skyrat/sound/roblox/OOF.wav
  modular_skyrat/sound/roblox/equip.wav
  modular_skyrat/sound/roblox/lunge.wav
  tgstation.dme
Labels: Feature, Sprites

#618 Adds catbig and deer ears to the human ears pool
  modular_skyrat/code/modules/mob/dead/new_player/sprite_accessories/ears.dm
  tgstation.dme
Labels: Feature

#633 Even more surgery fixes
  modular_skyrat/code/modules/surgery/surgery_step.dm
Labels: Feature, Fix

#616 Gives Prescription HUDS their own unique sprites.
  modular_skyrat/code/modules/clothing/glasses/hud.dm
  modular_skyrat/icons/mob/eyes.dmi
  modular_skyrat/icons/obj/clothing/glasses.dmi
  tgstation.dme
Labels: Feature, Sprites

#640 Icon hardsync because the PRmirror bot is a whore sometimes.
  icons/mob/inhands/weapons/guns_lefthand.dmi
  icons/mob/inhands/weapons/guns_righthand.dmi
  icons/obj/items_and_weapons.dmi
Labels: Sprites

#648 Added a fugton of new names to the list.
  strings/names/first_female.txt
  strings/names/first_male.txt
  strings/names/last.txt
Labels: Feature

#641 Makes contractor tablets not spawn invisible.
  code/modules/modular_computers/computers/item/tablet.dm
Labels: Fix

#645 [MODULAR] D.A.B. -> E.A.U.
  modular_skyrat/code/modules/client/loadout/head.dm
  modular_skyrat/code/modules/client/loadout/suit.dm
  modular_skyrat/code/modules/clothing/head/misc.dm
  modular_skyrat/code/modules/clothing/suits/miscellaneous.dm
  tgstation.dme
Labels: Tweak

#292 Adds Collar Bans
  code/__DEFINES/admin.dm
  code/game/gamemodes/game_mode.dm
  code/game/machinery/cloning.dm
  code/modules/admin/admin.dm
  code/modules/admin/topic.dm
  modular_skyrat/code/game/objects/items/devices/radio/electropack.dm
  tgstation.dme
Labels: Feature

#614 Comments out the supermatter cut objective
  code/game/gamemodes/objective_items.dm
Labels: Removal

#673 Lesser collar bans
  code/__DEFINES/admin.dm
  code/game/gamemodes/game_mode.dm
  code/modules/admin/admin.dm
  code/modules/admin/topic.dm
  code/modules/mob/living/carbon/human/life.dm
  modular_skyrat/code/game/objects/items/devices/radio/electropack.dm
Labels: Feature, Tweak

#674 Fixes the problem with youtube-dl for the purposes of "Play internet sound" on linux.
  code/modules/admin/verbs/playsound.dm
Labels: Fix

#675 [Fix]Engieborg Upgrade Checks
  modular_skyrat/code/game/objects/items/robot/robot_upgrades.dm
Labels: Fix

#687 Adds Tacticool Skirtleneck to loadout
  modular_skyrat/code/modules/client/loadout/uniform.dm
Labels: Feature

#672 A small bunch of cumulative changes to mining
  modular_skyrat/code/game/turfs/simulated/floor/asteroid.dm
  modular_skyrat/code/modules/mining/equipment/kinetic_crusher.dm
  modular_skyrat/code/modules/mining/equipment/regenerative_core.dm
  modular_skyrat/code/modules/mining/lavaland/necropolis_chests.dm
  modular_skyrat/code/modules/mob/living/simple_animal/hostile/megafauna/bubblegumhard.dm
  modular_skyrat/code/modules/mob/living/simple_animal/hostile/megafauna/megafauna.dm
  modular_skyrat/code/modules/projectiles/guns/energy/kinetic_accelerator.dm
  modular_skyrat/icons/mob/inhands/swords_lefthand.dmi
  modular_skyrat/icons/mob/inhands/swords_righthand.dmi
  modular_skyrat/icons/mob/inhands/weapons/guns_lefthand.dmi
  modular_skyrat/icons/mob/inhands/weapons/guns_righthand.dmi
  modular_skyrat/icons/obj/1x2.dmi
  modular_skyrat/icons/obj/guns/energy.dmi
  modular_skyrat/icons/obj/guns/projectile.dmi
  tgstation.dme
Labels: Balance/Rebalance, Fix, Sprites

#691 yoooo this blade is fucking ugly yoooooooooo
  modular_skyrat/icons/obj/1x2.dmi
Labels: Sprites

#688 Attachable hardsuit blades
  modular_skyrat/code/modules/clothing/spacesuits/hardsuit.dm
  modular_skyrat/icons/obj/items_and_weapons.dmi
Labels: Feature, Sprites

#690 Adds gigantism trait (visual big sprite)
  modular_skyrat/code/_DEFINES/traits.dm
  modular_skyrat/code/datums/traits/neutral.dm
  tgstation.dme
Labels: Feature

#705 Blood-Drunk Accelerator Hotfixes
  modular_skyrat/code/modules/projectiles/guns/energy/kinetic_accelerator.dm
Labels: Fix, Tweak

#710 Removes Life() from lewd verbs, adds the sound toggle to Content Pref…
  code/__DEFINES/preferences.dm
  code/modules/client/preferences.dm
  modular_skyrat/code/_DEFINES/preferences.dm
  modular_skyrat/code/interactions/_interaction.dm
  modular_skyrat/code/interactions/lewd/_lewd.dm
  modular_skyrat/code/interactions/lewd/lewd_datums.dm
  modular_skyrat/code/interactions/lewd/lewd_hud.dm
  modular_skyrat/code/interactions/lewd/lewd_interactions.dm
  modular_skyrat/code/modules/client/preferences_toggles.dm
Labels: Code Improvement, Feature, Removal

#721 [SPEEDMERGE] Revert "Lesser collar bans" and "Collar bans"
  code/__DEFINES/admin.dm
  code/game/gamemodes/game_mode.dm
  code/game/machinery/cloning.dm
  code/modules/admin/admin.dm
  code/modules/admin/topic.dm
  code/modules/mob/living/carbon/human/life.dm
  modular_skyrat/code/game/objects/items/devices/radio/electropack.dm
  tgstation.dme
Labels: Revert

#712 Caps toxin damage on dwarven alcohol gland
  code/modules/mob/living/carbon/human/species_types/dwarves.dm
Labels: Balance/Rebalance

#723 The Elder Scrolls Blades (But actually good)
  _maps/RandomRuins/LavaRuins/lavaland_surface_wrath.dmm
  modular_skyrat/code/datums/ruins/lavaland.dm
  modular_skyrat/code/datums/status_effects/debuffs.dm
  modular_skyrat/code/game/objects/items/weaponry.dm
  modular_skyrat/code/modules/mining/lavaland/necropolis_chests.dm
  modular_skyrat/code/modules/ruins/lavalandruin_code/misc.dm
  modular_skyrat/code/modules/uplink/uplink_dangerous.dm
  modular_skyrat/icons/mob/inhands/weapons/ebonyblade_lefthand.dmi
  modular_skyrat/icons/mob/inhands/weapons/ebonyblade_righthand.dmi
  modular_skyrat/icons/mob/inhands/weapons/goldbrand_lefthand.dmi
  modular_skyrat/icons/mob/inhands/weapons/goldbrand_righthand.dmi
  modular_skyrat/icons/obj/items_and_weapons.dmi
  tgstation.dme
Labels: Feature, Map Edit, Sprites

#729 Adds a new "humanoid" base race
  code/_globalvars/lists/maintenance_loot.dm
  config/game_options.txt
  modular_skyrat/code/modules/clothing/gloves/ring.dm
  modular_skyrat/code/modules/mob/dead/new_player/sprite_accessories/ears.dm
  modular_skyrat/code/modules/mob/living/carbon/human/species_types/humanoid.dm
  modular_skyrat/icons/mob/dunmer_face.dmi
  modular_skyrat/icons/mob/dunmer_parts.dmi
  modular_skyrat/icons/mob/human_parts_greyscale.dmi
  tgstation.dme
Labels: Config Update, Feature

#731 Asynchronous speech with typing indicator
  code/__DEFINES/preferences.dm
  code/modules/client/preferences.dm
  code/modules/keybindings/setup.dm
  code/modules/mob/living/say.dm
  code/modules/mob/say.dm
  modular_skyrat/code/modules/client/preferences_toggles.dm
  modular_skyrat/code/modules/keybindings/bindings_mob.dm
  modular_skyrat/code/modules/mob/emote.dm
  modular_skyrat/code/modules/mob/mob_movement.dm
  tgstation.dme
Labels: Feature

#732 Brings back up the expose temperature temp by a bit
  modular_skyrat/code/modules/atmospherics/environmental/LINDA_fire.dm
Labels: Balance/Rebalance

#745 [Modular] Mining Borg Reverting Nerf
  modular_skyrat/code/game/objects/items/robot/robot_upgrades.dm
  modular_skyrat/code/modules/mob/living/silicon/robot/robot_modules.dm
  modular_skyrat/code/modules/research/designs/mechfabricator_designs.dm
  modular_skyrat/code/modules/research/techweb/all_nodes.dm
Labels: Revert, Tweak

#747 Fixes Ashwalker sprites
  modular_skyrat/code/modules/mob/living/carbon/human/species_types/lizardpeople.dm
  tgstation.dme
Labels: Fix

#760 [READY]The USP is now an U.S.P (Universal Self Protection) pistol.
  modular_skyrat/code/modules/projectiles/boxes_magazines/external/pistol.dm
  modular_skyrat/code/modules/projectiles/guns/ballistic/pistol.dm
  modular_skyrat/icons/obj/guns/usp.dmi
Labels: Needs Review, Sprites, Tweak

#755 Comments out the 50% SM sabotage objective
  code/game/gamemodes/objective_sabotage.dm
Labels: Removal

#706 [READY]Adds argent energy cells to lavaland
  code/controllers/subsystem/research.dm
  modular_skyrat/code/datums/status_effects/buffs.dm
  modular_skyrat/code/modules/mining/lavaland/necropolis_chests.dm
  modular_skyrat/icons/mob/screen_alert.dmi
  modular_skyrat/icons/obj/argentcell.dmi
  modular_skyrat/icons/obj/items_and_weapons.dmi
  tgstation.dme
Labels: Feature, Needs Review, Sprites

#744 [READY]Adds the Golden Mask (haha morrowind) as hard legion loot, nerfs the explorer mask
  modular_skyrat/code/modules/clothing/head/misc.dm
  modular_skyrat/code/modules/mining/equipment/explorer_gear.dm
  modular_skyrat/code/modules/mining/lavaland/necropolis_chests.dm
  modular_skyrat/code/modules/mob/living/simple_animal/hostile/megafauna/king_of_goats.dm
  modular_skyrat/code/modules/ruins/lavalandruin_code/kinggoat.dm
  modular_skyrat/icons/mob/mask.dmi
  modular_skyrat/icons/mob/mask_muzzled.dmi
  modular_skyrat/icons/obj/clothing/masks.dmi
Labels: Balance/Rebalance, Feature, Needs Review, Sprites

#762 [READY]Ports some things from tg.
  config/spaceRuinBlacklist.txt
  modular_skyrat/code/datums/components/crafting/recipes/recipes_weapon_and_ammo.dm
  modular_skyrat/code/datums/ruins/space.dm
  modular_skyrat/code/game/objects/items/cards_ids.dm
  modular_skyrat/code/game/objects/structures/crates_lockers/closets/secure/security.dm
  modular_skyrat/code/game/objects/structures/ghost_role_spawners.dm
  modular_skyrat/code/modules/clothing/head/helmet.dm
  modular_skyrat/code/modules/clothing/refactor.dm
  modular_skyrat/code/modules/clothing/suits/miscellaneous.dm
  modular_skyrat/code/modules/mob/living/simple_animal/corpse.dm
  modular_skyrat/code/modules/mob/living/simple_animal/hostile/nanotrasen.dm
  modular_skyrat/code/modules/ruins/spaceruin_code/forgottenship.dm
  modular_skyrat/icons/mob/head.dmi
  modular_skyrat/icons/mob/head_muzzled.dmi
  modular_skyrat/icons/mob/simple_human.dmi
  modular_skyrat/icons/mob/suit.dmi
  modular_skyrat/icons/mob/suit_digi.dmi
  modular_skyrat/icons/obj/clothing/hats.dmi
  modular_skyrat/icons/obj/clothing/suits.dmi
  tgstation.dme
Labels: Config Update, Feature, Needs Review, Sprites

#765 [READY] [Modular] Added 3 kinds of insect antenna "ears"
  modular_skyrat/code/modules/mob/dead/new_player/sprite_accessories/ears.dm
  modular_skyrat/icons/mob/mam_ears.dmi
Labels: Feature, Needs Review

#769 Ported the changelog compilation action from tg with the hope that it will work.
  .github/workflows/compile_changelogs.yml
Labels: GitHub

#761 [READY]Adds two new crates for the cargo supply console.
  modular_skyrat/code/modules/cargo/packs/special.dm
  tgstation.dme
Labels: Feature, Needs Review

#771 [READY] Removes the dots from the USP
  modular_skyrat/code/modules/projectiles/guns/ballistic/pistol.dm
Labels: Needs Review, Removal, Tweak

#592 [Modular][READY] Bluespace Miners
  modular_skyrat/code/game/objects/items/circuitboards/machine_circuitboards.dm
  modular_skyrat/code/modules/mining/machine_bluespaceminer.dm
  modular_skyrat/code/modules/research/designs/machine_designs.dm
  modular_skyrat/code/modules/research/techweb/all_nodes.dm
  tgstation.dme
Labels: Do Not Merge, Feature, Needs Review

#772 [READY]Cybersun operative ghost role and ruin fixes
  _maps/RandomRuins/SpaceRuins/forgottenship.dmm
Labels: Feature, Map Edit, Needs Review

#779 [Modular][Ready] Reverts Laser Icon
  modular_skyrat/code/modules/projectiles/guns/energy/laser.dm
  modular_skyrat/icons/obj/guns/energy.dmi
  tgstation.dme
Labels: Needs Review, Revert, Tweak

#773 [READY]Surgeon Simulator 2560
  modular_skyrat/code/modules/surgery/organ_manipulation.dm
  tgstation.dme
Labels: Needs Review, Tweak

#785 [READY]Mace of Molag Bal + Nerfs Fargoth
  code/_globalvars/lists/maintenance_loot.dm
  modular_skyrat/code/game/objects/items/weaponry.dm
  modular_skyrat/code/modules/clothing/gloves/ring.dm
  modular_skyrat/code/modules/uplink/uplink_dangerous.dm
  modular_skyrat/icons/mob/inhands/mace_lefthand.dmi
  modular_skyrat/icons/mob/inhands/mace_righthand.dmi
  modular_skyrat/icons/obj/molagmace.dmi
Labels: Feature, Fix, Needs Review, Sprites

#763 [READY]Collar Bans 2: Electric Boogaloo
  code/__DEFINES/admin.dm
  code/game/gamemodes/game_mode.dm
  code/game/machinery/cloning.dm
  code/modules/admin/admin.dm
  code/modules/admin/topic.dm
  modular_skyrat/code/controllers/subsystem/collarbans.dm
  modular_skyrat/code/game/objects/items/devices/radio/electropack.dm
  tgstation.dme
Labels: Administration, Feature, Needs Review

#676 [READY] Changes a few ruins in space and lavaland, along with spawntext changes for the lavaland syndis.
  code/modules/ruins/lavaland_ruin_code.dm
  modular_skyrat/_maps/RandomRuins/LavaRuins/lavaland_biodome_beach.dmm
  modular_skyrat/_maps/RandomRuins/LavaRuins/lavaland_surface_hermit.dmm
  modular_skyrat/_maps/RandomRuins/LavaRuins/lavaland_surface_syndicate_base1.dmm
  modular_skyrat/_maps/RandomRuins/SpaceRuins/listeningstation.dmm
  modular_skyrat/code/datums/ruins/lavaland.dm
  modular_skyrat/code/datums/ruins/space.dm
Labels: Feature, Needs Review, Tweak

#791 [SPEEDMERGE][READY][FUCK]Fixes the USP accepting lethal rounds without being emagged. Makes security powergamers cry.
  modular_skyrat/code/modules/projectiles/ammunition/ballistic/pistol.dm
  modular_skyrat/code/modules/projectiles/boxes_magazines/external/pistol.dm
Labels: Fix, Needs Review

#778 [READY]Lavaland Eternal
  modular_skyrat/code/game/objects/structures/lavaland/necropolis_tendril.dm
  modular_skyrat/code/game/turfs/simulated/floor/asteroid.dm
  modular_skyrat/code/modules/mining/equipment/kinetic_crusher.dm
  modular_skyrat/code/modules/mob/living/simple_animal/hostile/mining_mobs/imp.dm
  modular_skyrat/icons/mob/lavaland/lavaland_monsters.dmi
  modular_skyrat/icons/obj/lavaland/artefacts.dmi
  modular_skyrat/sound/misc/cyberdemonrocket.wav
  modular_skyrat/sound/misc/imp.wav
  modular_skyrat/sound/misc/impdies.wav
  tgstation.dme
Labels: Feature, Needs Review, Sound, Sprites

#787 [READY]The Skeleton Key
  modular_skyrat/code/game/objects/items/cards_ids.dm
  modular_skyrat/code/modules/uplink/uplink_devices.dm
  modular_skyrat/icons/obj/items/skeletonkey.dmi
  tgstation.dme
Labels: Feature, Needs Review, Sprites

#788 [READY]Make the rapier great again
  modular_skyrat/code/game/objects/items/melee/misc.dm
  modular_skyrat/code/modules/uplink/uplink_dangerous.dm
  modular_skyrat/icons/mob/inhands/weapons/rapier_lefthand.dmi
  modular_skyrat/icons/mob/inhands/weapons/rapier_righthand.dmi
  modular_skyrat/icons/obj/rapier.dmi
  tgstation.dme
Labels: Feature, Needs Review, Sprites

#798 [Important] Fixes to lewd verbs, interactions, async say and overlays
  code/modules/mob/living/death.dm
  code/modules/mob/living/say.dm
  code/modules/mob/say.dm
  modular_skyrat/code/interactions/_interaction.dm
  modular_skyrat/code/interactions/lewd/_lewd.dm
  modular_skyrat/code/interactions/lewd/lewd_interactions.dm
  modular_skyrat/code/modules/client/preferences_toggles.dm
  modular_skyrat/code/modules/mob/living/ssd_indicator.dm
  modular_skyrat/code/modules/mob/typing_indicator.dm
Labels: Fix

#807 [PLS SPEEDMERGE]Comments out cybersun ruin
  modular_skyrat/code/datums/ruins/space.dm
Labels: Removal

#817 [READY]Massively buffs virology
  modular_skyrat/code/datums/diseases/advance/presets.dm
  modular_skyrat/code/datums/diseases/advance/symptoms/genetics.dm
  modular_skyrat/code/datums/diseases/advance/symptoms/heal.dm
  modular_skyrat/code/datums/diseases/advance/symptoms/sensory.dm
  modular_skyrat/code/datums/diseases/advance/symptoms/viral.dm
  modular_skyrat/code/datums/diseases/fluxitus.dm
  tgstation.dme
Labels: Feature, Needs Review

#826 Fixes metal duplication
  modular_skyrat/code/modules/research/designs/autolathe_designs/autolathe_designs_sec_and_hacked.dm
Labels: Fix

#827 Unfucked a little oopsie regarding changelogs.
  html/templates/header.html
Labels: Fix

#819 [READY]Chaplain now has a MORTIS implant.
  modular_skyrat/code/modules/job/job_types/chaplain.dm
  modular_skyrat/sound/misc/mortis.ogg
  tgstation.dme
Labels: Feature, Needs Review

#840 [SPEEDMERGE][READY]Downgrades the lava imp's difficulty from Nightmare to Ultra-Violence
  modular_skyrat/code/modules/mob/living/simple_animal/hostile/mining_mobs/imp.dm
Labels: Fix, Needs Review

#842 [READY]Adds a new traitor item: Tactical stealth suit
  modular_skyrat/code/datums/status_effects/buffs.dm
  modular_skyrat/code/modules/clothing/under/stealth.dm
  modular_skyrat/code/modules/uplink/uplink_stealth.dm
  modular_skyrat/icons/mob/screen_alert.dmi
  modular_skyrat/icons/mob/stealth.dmi
  modular_skyrat/icons/mob/stealth_digi.dmi
  modular_skyrat/icons/obj/clothing/stealthsuit.dmi
  tgstation.dme
Labels: Feature, Needs Review, Sprites

#849 Optimizes 'get_hearers_in_view'
  code/__HELPERS/game.dm
  modular_skyrat/code/_HELPERS/game.dm
  tgstation.dme
Labels: Tweak

#846 [SPEEDMERGE][READY] Fixes the PANDEMIC virology machine creating errors with certain symptoms
  modular_skyrat/code/datums/diseases/advance/symptoms/heal.dm
Labels: Fix, Needs Review

#820 [ MAP CHANGES (Box Station) ] Departures Rework & Tiny Tweak to Dorms
  _maps/map_files/BoxStation/BoxStation.dmm
Labels: Map Edit, Needs Review

#864 [READY]Organ manipulation healing: Chemistry edition!
  modular_skyrat/code/modules/clothing/gloves/ring.dm
  modular_skyrat/code/modules/surgery/organ_manipulation.dm
Labels: Needs Review

#868 [Fix] Box Departures
  _maps/map_files/BoxStation/BoxStation.dmm
Labels: Fix, Map Edit

#882 [READY]USPs can now be emagged.
  modular_skyrat/code/modules/projectiles/guns/ballistic/pistol.dm
Labels: Needs Review, Tweak

#863 [READY]Fixes the heat resistance symptom not healing you.
  modular_skyrat/code/datums/diseases/advance/symptoms/heal.dm
  modular_skyrat/code/datums/diseases/fluxitus.dm
Labels: Do Not Merge, Fix, Needs Review

#874 [READY][Please review memetainers][PLEASE][FUCK]Better collar bans (and lesser collar bans)
  code/modules/admin/topic.dm
  modular_skyrat/code/game/objects/items/devices/radio/electropack.dm
Labels: Code Improvement, Needs Review

#880 [READY]Infiltrator vest and helmet buff
  modular_skyrat/code/modules/clothing/head/helmet.dm
  modular_skyrat/code/modules/clothing/suits/armor.dm
Labels: Balance/Rebalance, Needs Review

#886 [READY]Ports the revolver conversion kit from Paradise
  modular_skyrat/code/modules/projectiles/guns/ballistic/revolver.dm
  modular_skyrat/code/modules/uplink/uplink_devices.dm
  modular_skyrat/icons/obj/kit.dmi
  tgstation.dme
Labels: Feature, Needs Review, Sprites

#889 [READY] [Map Edit] Box Station Permabrig Changes. (QOL, Issue Fixing etc.)
  _maps/map_files/BoxStation/BoxStation.dmm
Labels: Map Edit, Needs Review

#890 [READY]Stabby cleanbots
  modular_skyrat/code/modules/mob/living/simple_animal/bot/bot.dm
  modular_skyrat/code/modules/mob/living/simple_animal/bot/cleanbot.dm
  tgstation.dme
Labels: Needs Review, Tweak

#892 [READY]Adds a cross, for degenerates like you.
  modular_skyrat/code/datums/components/crafting/recipes/recipeswhat.dm
  modular_skyrat/code/game/objects/structures/kitchen_spike.dm
  modular_skyrat/icons/obj/cross.dmi
  modular_skyrat/sound/misc/crossed.ogg
  tgstation.dme
Labels: Feature, Needs Review, Sound, Sprites

#898 [READY]Macaco soup
  modular_skyrat/code/modules/food_and_drinks/food/snacks/snacks_soup.dm
  modular_skyrat/code/modules/food_and_drinks/recipes/tablecraft/recipes_soup.dm
  modular_skyrat/icons/obj/food/sopa.dmi
  tgstation.dme
Labels: Feature, Needs Review, Sprites

#902 [READY]Manlet and tiny traits
  modular_skyrat/code/_DEFINES/traits.dm
  modular_skyrat/code/datums/traits/neutral.dm
Labels: Feature, Needs Review

#906 Phantom pie? Bugfixing to the supposedly fixed pie
  code/modules/mob/living/carbon/human/human.dm
Labels: Fix

#910 Changes the shambling miner to be butcherable
  modular_skyrat/code/modules/mob/living/simple_animal/hostile/mining_mobs/shamblingminer.dm
Labels: Fix, Tweak

#911 [READY]Ports Hippiestation nooses
  modular_skyrat/code/game/objects/noose.dm
  modular_skyrat/code/modules/power/cable.dm
  modular_skyrat/icons/obj/objects.dmi
  modular_skyrat/sound/effects/noose_idle.ogg
  modular_skyrat/sound/effects/noosed.ogg
  tgstation.dme
Labels: Feature, Needs Review, Sprites

#912 [READY]Sounds of hell
  modular_skyrat/code/modules/mining/equipment/kinetic_crusher.dm
  modular_skyrat/code/modules/mob/living/simple_animal/hostile/mining_mobs/imp.dm
  modular_skyrat/sound/misc/doomdies.wav
  modular_skyrat/sound/misc/doomgibbed.wav
  modular_skyrat/sound/misc/doominjured.wav
  modular_skyrat/sound/misc/doomscream.wav
  modular_skyrat/sound/misc/doomscream2.wav
  modular_skyrat/sound/misc/doomunf.wav
  modular_skyrat/sound/misc/impattacks.wav
  modular_skyrat/sound/misc/impdies.wav
  modular_skyrat/sound/misc/impinjured.wav
  modular_skyrat/sound/misc/impnearby.wav
  modular_skyrat/sound/misc/impranged.wav
  modular_skyrat/sound/misc/impsight.wav
  modular_skyrat/sound/misc/impsight2.wav
Labels: Feature, Needs Review, Sound

#915 [READY] Prisoner Starting Text
  modular_skyrat/code/modules/jobs/job_types/prisoner.dm
Labels: Feature, Needs Review

#916 [READY]Changes the name of "jump boots" to "dashing boots"
  modular_skyrat/code/modules/clothing/shoes/miscellaneous.dm
Labels: Needs Review, Tweak

#917 [READY]Fixes the strange goat plushie being invisible.
  modular_skyrat/icons/obj/plushes.dmi
Labels: Fix, Needs Review

#918 [IMPORTANT] Fixes hearers in view and optimizes it further
  modular_skyrat/code/_HELPERS/game.dm
Labels: Fix

#923 [Fix] Boxstation Security Atmos Fix
  _maps/map_files/BoxStation/BoxStation.dmm
Labels: Fix, Map Edit

#825 Adds a configable age barrier to accounts joining the server
  code/modules/client/client_procs.dm
  config/config.txt
  config/skyrat/skyrat_config.txt
  modular_skyrat/code/controllers/configuration/entries/skyrat_config.dm
  tgstation.dme
Labels: Config Update, Feature

#924 [READY][SPEEDMERGE]That one fucking bug that kills the server because of fucking nooses
  modular_skyrat/code/datums/components/crafting/recipes/recipeswhat.dm
  modular_skyrat/code/modules/power/cable.dm
  tgstation.dme
Labels: Fix, Needs Review, Tweak

#938 Reverts hearers in view
  code/__HELPERS/game.dm
  modular_skyrat/code/_HELPERS/game.dm
  tgstation.dme
Labels: Revert

#944 [READY]Yet another virology bugfix
  modular_skyrat/code/datums/diseases/advance/symptoms/viral.dm
Labels: Fix, Needs Review

#946 [READY]Buffs the immortality talisman, by making it smaller
  modular_skyrat/code/modules/mining/lavaland/necropolis_chests.dm
Labels: Balance/Rebalance, Needs Review

#928 [READY]Moves the ablative coat to the clothing section of crafting
  modular_skyrat/code/datums/components/crafting/recipes/recipes_clothing.dm
  modular_skyrat/code/datums/components/crafting/recipes/recipes_weapon_and_ammo.dm
  tgstation.dme
Labels: Needs Review, Tweak

#934 [READY]Renames "Manlet" trait to "Small". Removes the tiny trait.
  modular_skyrat/code/_DEFINES/traits.dm
  modular_skyrat/code/datums/traits/neutral.dm
Labels: Needs Review, Removal, Tweak

#933 Replaces brigphys clothes with better ones
  modular_skyrat/code/modules/clothing/outfits/plasmaman.dm
  modular_skyrat/code/modules/clothing/spacesuits/plasmamen.dm
  modular_skyrat/code/modules/mob/living/carbon/human/species_types/plasmamen.dm
  modular_skyrat/icons/mob/clothing/head.dmi
  modular_skyrat/icons/mob/clothing/suit.dmi
  modular_skyrat/icons/mob/clothing/under/uniform.dmi
  modular_skyrat/icons/mob/head.dmi
  modular_skyrat/icons/obj/clothing/hats.dmi
  modular_skyrat/icons/obj/clothing/suits.dmi
  modular_skyrat/icons/obj/clothing/uniform.dmi
  tgstation.dme
Labels: Sprites, Tweak

#948 [Fix][Map Edit] Box Perma fixes and changes. Brigphys clothing fixes.
  _maps/map_files/BoxStation/BoxStation.dmm
  modular_skyrat/code/game/machinery/doors/brigdoors.dm
  modular_skyrat/code/modules/clothing/under/jobs/Plasmaman/medsci.dm
  modular_skyrat/code/modules/jobs/job_types/brig_physician.dm
  tgstation.dme
Labels: Feature, Fix, Map Edit

#949 [READY]CBT - Crusher Balancing Trophies
  modular_skyrat/code/modules/mining/equipment/kinetic_crusher.dm
  modular_skyrat/code/modules/mob/living/simple_animal/hostile/megafauna/colossus.dm
Labels: Needs Review

#877 [READY]Solid Gear Metal: Liquid Cardboard Deluxe
  modular_skyrat/code/datums/status_effects/buffs.dm
  modular_skyrat/code/game/objects/items/implants/implant_stealth.dm
  modular_skyrat/code/modules/clothing/under/stealth.dm
  tgstation.dme
Labels: Balance/Rebalance, Needs Review, Tweak

#951 [READY][FUCK]CBT 2 - IT COMPILES EDITION
  modular_skyrat/code/modules/mining/equipment/kinetic_crusher.dm
  modular_skyrat/code/modules/mob/living/simple_animal/hostile/megafauna/colossus.dm
Labels: Needs Review

#953 [READY][ACTUALLY READY]CBT 3 - i pissed my pants edition
  modular_skyrat/code/modules/mining/equipment/kinetic_crusher.dm
Labels: Needs Review

#956 [READY][ACTUALLY TESTED]Muhreen's "Epic" Clothing
  modular_skyrat/code/game/objects/obj.dm
  modular_skyrat/code/modules/clothing/refactor.dm
  modular_skyrat/code/modules/mining/equipment/explorer_gear.dm
  modular_skyrat/icons/mob/chonker.dmi
  modular_skyrat/icons/mob/chonker_digi.dmi
  modular_skyrat/icons/mob/epic_mining.dmi
  modular_skyrat/icons/mob/epic_mining_digi.dmi
  modular_skyrat/icons/mob/epicclothing.dmi
  modular_skyrat/icons/mob/epicclothing_digi.dmi
  modular_skyrat/icons/mob/security_hardsuits.dmi
  modular_skyrat/icons/mob/security_hardsuits_digi.dmi
  modular_skyrat/icons/obj/clothing/chonker.dmi
  modular_skyrat/icons/obj/clothing/epic_mining.dmi
  modular_skyrat/icons/obj/clothing/epicclothing.dmi
  modular_skyrat/icons/obj/clothing/security_hardsuits.dmi
  tgstation.dme
Labels: Code Improvement, Do Not Merge, Feature, Needs Review, Sprites

#960 [Modular]Brig Physician Access and Locker
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/KiloStation/KiloStation.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
  modular_skyrat/code/game/objects/structures/crates_lockers/closets/secure/security.dm
  modular_skyrat/code/modules/jobs/job_types/brig_physician.dm
  modular_skyrat/icons/obj/closet.dmi
  tgstation.dme
Labels: Feature, Map Edit, Tweak

#962 [MAP CHANGES] [READY] Box Station QOL Changes and Tweaks.
  _maps/map_files/BoxStation/BoxStation.dmm
Labels: Map Edit, Needs Review

#955 [READY]Scream bloody murder!
  modular_skyrat/code/modules/mob/emote.dm
  modular_skyrat/sound/emotes/dunmerscreamfemale.ogg
  modular_skyrat/sound/emotes/dunmerscreammale.ogg
  modular_skyrat/sound/emotes/shadowscream.ogg
Labels: Do Not Merge, Feature, Needs Review

#965 [https://en.wikipedia.org/wiki/Semen]Probably fixes most of the reskinning problems caused by that last PR with Muhreen's sprites i don't know if it works no i won't test it fuck you
  modular_skyrat/code/modules/clothing/refactor.dm
Labels: Administration, Balance/Rebalance, Code Improvement, Config Update, Feature, Fix, Grammar and Formatting, Refactor, Removal, Sound, Sprites, Tweak

#976 Im gonna' give it to ya
  tgstation.dme
Labels: Feature

#978 New traitor bundle: The Joker kit.
  modular_skyrat/code/modules/uplink/uplink_bundles.dm
  tgstation.dme
Labels: Feature

#982 [Modular] License Plate Delivery Chute
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/KiloStation/KiloStation.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
  modular_skyrat/code/game/machinery/lpchutes.dm
  modular_skyrat/icons/obj/machines/dwchute.dmi
  tgstation.dme
Labels: Feature, Map Edit, Sprites

#984 Goat Simulator 2020
  modular_skyrat/code/game/machinery/computer/arcade/arcade.dm
  modular_skyrat/code/game/objects/items/plushes/plushes.dm
  tgstation.dme
Labels: Fix

#986 Renames fargoth's ring, again
  modular_skyrat/code/modules/clothing/gloves/ring.dm
Labels: Balance/Rebalance, Tweak

#979 The silence of the lambs
  modular_skyrat/code/game/objects/obj.dm
  modular_skyrat/code/modules/mining/equipment/explorer_gear.dm
  modular_skyrat/code/modules/mob/emote.dm
  modular_skyrat/icons/mob/epic_mining.dmi
  modular_skyrat/icons/mob/epic_mining_digi.dmi
  modular_skyrat/icons/obj/clothing/epic_mining.dmi
Labels: Fix, Needs Review, Removal

#994 [MODULAR] EAU renamed back to DAB, also gets reskins because I'm bored
  modular_skyrat/code/modules/client/loadout/head.dm
  modular_skyrat/code/modules/client/loadout/suit.dm
  modular_skyrat/code/modules/clothing/head/misc.dm
  modular_skyrat/code/modules/clothing/suits/miscellaneous.dm
  modular_skyrat/icons/mob/head.dmi
  modular_skyrat/icons/mob/suit.dmi
  modular_skyrat/icons/mob/suit_digi.dmi
  modular_skyrat/icons/obj/clothing/hats.dmi
  modular_skyrat/icons/obj/clothing/suits.dmi
Labels: Sprites, Tweak

#997 [Modular] More Spawntexts & SO Increase
  code/modules/jobs/job_types/clown.dm
  code/modules/jobs/job_types/security_officer.dm
  config/jobs.txt
  modular_skyrat/code/modules/jobs/job_types/clown.dm
  modular_skyrat/code/modules/jobs/job_types/head_of_security.dm
  modular_skyrat/code/modules/jobs/job_types/security_officer.dm
  modular_skyrat/code/modules/jobs/job_types/warden.dm
  tgstation.dme
Labels: Config Update, Feature, Tweak

#983 Lavaland 2016: Normal Fauna Glory Kills
  modular_skyrat/code/modules/mob/living/simple_animal/hostile/mining_mobs/basilisk.dm
  modular_skyrat/code/modules/mob/living/simple_animal/hostile/mining_mobs/goldgrub.dm
  modular_skyrat/code/modules/mob/living/simple_animal/hostile/mining_mobs/goliath.dm
  modular_skyrat/code/modules/mob/living/simple_animal/hostile/mining_mobs/hivelord.dm
  modular_skyrat/code/modules/mob/living/simple_animal/hostile/mining_mobs/imp.dm
  modular_skyrat/code/modules/mob/living/simple_animal/hostile/mining_mobs/miningmobs.dm
  modular_skyrat/code/modules/mob/living/simple_animal/hostile/mining_mobs/shamblingminer.dm
  tgstation.dme
Labels: Feature, Needs Review

#995 Adds some loudout stuff.
  modular_skyrat/code/modules/client/loadout/_medical.dm
  modular_skyrat/code/modules/client/loadout/head.dm
  modular_skyrat/code/modules/client/loadout/mask.dm
  tgstation.dme
Labels: Feature

#1001 Modularizes all the cool cargo crates that upstream removed
  modular_skyrat/code/modules/cargo/packs/bloat.dm
  modular_skyrat/code/modules/cargo/packs/special.dm
  tgstation.dme
Labels: Feature

#1005 Fixes that one issue with the hierophant
  modular_skyrat/code/modules/mob/living/simple_animal/hostile/megafauna/hierophant.dm
Labels: Fix

#1009 Changes the description of the detective revolver to better reflect how good it is.
  modular_skyrat/code/modules/projectiles/guns/ballistic/revolver.dm
Labels: Tweak

#1010 CAPS LOCK
  modular_skyrat/code/modules/clothing/head/soft_caps.dm
  modular_skyrat/icons/mob/cap.dmi
  modular_skyrat/icons/mob/cap_muzzled.dmi
  modular_skyrat/icons/obj/clothing/caps.dmi
Labels: Feature

#1012 [Fix][Map Edit] Perma Changes for Maps.
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/KiloStation/KiloStation.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
Labels: Feature, Fix, Map Edit

#1017 [FIX]Adds radiation shutters (Floof/Kat)
  _maps/RandomRuins/StationRuins/Box/Engine/engine_am.dmm
  _maps/RandomRuins/StationRuins/Box/Engine/engine_singulo.dmm
  _maps/RandomRuins/StationRuins/Box/Engine/engine_sm.dmm
  _maps/RandomRuins/StationRuins/Box/Engine/engine_sm_1x3.dmm
  _maps/RandomRuins/StationRuins/Box/Engine/engine_sm_3x.dmm
  _maps/RandomRuins/StationRuins/Box/Engine/engine_sm_5x5.dmm
  _maps/RandomRuins/StationRuins/Box/Engine/engine_tesla.dmm
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/KiloStation/KiloStation.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/OmegaStation/OmegaStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
  code/game/machinery/doors/shutters.dm
Labels: Fix, Map Edit

#1025 [Tweak]Prisoner Slots
  _maps/map_files/KiloStation/job_changes.dm
  config/jobs.txt
  modular_skyrat/code/modules/jobs/job_types/prisoner.dm
Labels: Balance/Rebalance, Config Update, Map Edit, Tweak

#1028 Shomtgun Shellms
  modular_skyrat/code/modules/projectiles/ammunition/ballistic/shotgun.dm
  modular_skyrat/icons/obj/shomtgun.dmi
  tgstation.dme
Labels: Sprites, Tweak

#1030 Makes the cross not 2 tiles tall
  modular_skyrat/code/game/objects/structures/kitchen_spike.dm
Labels: Tweak

#1035 [PR FIX]Various ghost role QoL; moving holding facility; removing energy net
  _maps/map_files/generic/CentCom.dmm
  code/__DEFINES/dcs/signals.dm
  code/datums/elements/ghost_role_eligibility.dm
  code/datums/mind.dm
  code/game/gamemodes/objective.dm
  code/game/objects/items/candle.dm
  code/game/objects/items/holy_weapons.dm
  code/game/objects/structures/ghost_role_spawners.dm
  code/modules/events/sentience.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/ninja/suit/n_suit_verbs/energy_net_nets.dm
  code/modules/ninja/suit/suit.dm
Labels: Feature, Map Edit, Removal, Tweak
